// GENERATED by gen/gir.php from GLib.DateTime - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GDateTime (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\GDateTime::__construct(GTimeZone $tz, int $year, int $month, int $day, int $hour, int
 * $minute, float $seconds)
 *
 * Creates a new #GDateTime corresponding to the given date and time in the time zone $tz.
 */
ZEND_METHOD(Gtk4_GDateTime, __construct) {
  zval *tz;
  zend_long year;
  zend_long month;
  zend_long day;
  zend_long hour;
  zend_long minute;
  double seconds;
  ZEND_PARSE_PARAMETERS_START(7, 7)
  Z_PARAM_OBJECT_OF_CLASS(tz, boxed_class_for_type(G_TYPE_TIME_ZONE)->ce)
  Z_PARAM_LONG(year)
  Z_PARAM_LONG(month)
  Z_PARAM_LONG(day)
  Z_PARAM_LONG(hour)
  Z_PARAM_LONG(minute)
  Z_PARAM_DOUBLE(seconds)
  ZEND_PARSE_PARAMETERS_END();
  gpointer tz_b = unwrap_boxed(tz, G_TYPE_TIME_ZONE);
  if (tz_b == nullptr) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(year, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(month, 3)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(day, 4)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(hour, 5)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(minute, 6)) RETURN_THROWS();
  gpointer obj = g_date_time_new(static_cast<GTimeZone *>(tz_b), static_cast<gint>(year),
                                 static_cast<gint>(month), static_cast<gint>(day),
                                 static_cast<gint>(hour), static_cast<gint>(minute), seconds);
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the value (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  boxed_adopt(boxed_from_zval(ZEND_THIS), G_TYPE_DATE_TIME, obj);
}

/**
 * static Gtk4\GDateTime::new_from_iso8601(string $text, ?GTimeZone $default_tz = null): ?GDateTime
 *
 * Creates a #GDateTime corresponding to the given [ISO 8601 formatted
 * string](https://en.wikipedia.org/wiki/ISO_8601) $text. ISO 8601 strings of the form
 * <date><sep><time><tz> are supported, with some extensions from [RFC
 * 3339](https://tools.ietf.org/html/rfc3339) as mentioned below.
 */
ZEND_METHOD(Gtk4_GDateTime, new_from_iso8601) {
  zend_string *text;
  zval *default_tz = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 2)
  Z_PARAM_STR(text)
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(default_tz, boxed_class_for_type(G_TYPE_TIME_ZONE)->ce)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_utf8(text, 1)) RETURN_THROWS();
  gpointer default_tz_b = nullptr;
  if (default_tz != nullptr) {
    default_tz_b = unwrap_boxed(default_tz, G_TYPE_TIME_ZONE);
    if (default_tz_b == nullptr) RETURN_THROWS();
  }
  gpointer phpgtk_ret =
      g_date_time_new_from_iso8601(ZSTR_VAL(text), static_cast<GTimeZone *>(default_tz_b));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_from_unix_local(int $t): ?GDateTime
 *
 * Creates a #GDateTime corresponding to the given Unix time $t in the local time zone.
 */
ZEND_METHOD(Gtk4_GDateTime, new_from_unix_local) {
  zend_long t;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(t)
  ZEND_PARSE_PARAMETERS_END();
  gpointer phpgtk_ret = g_date_time_new_from_unix_local(static_cast<gint64>(t));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_from_unix_local_usec(int $usecs): ?GDateTime
 *
 * Creates a `DateTime` corresponding to the given Unix time $t in the local time zone.
 */
ZEND_METHOD(Gtk4_GDateTime, new_from_unix_local_usec) {
  zend_long usecs;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(usecs)
  ZEND_PARSE_PARAMETERS_END();
  gpointer phpgtk_ret = g_date_time_new_from_unix_local_usec(static_cast<gint64>(usecs));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_from_unix_utc(int $t): ?GDateTime
 *
 * Creates a #GDateTime corresponding to the given Unix time $t in UTC.
 */
ZEND_METHOD(Gtk4_GDateTime, new_from_unix_utc) {
  zend_long t;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(t)
  ZEND_PARSE_PARAMETERS_END();
  gpointer phpgtk_ret = g_date_time_new_from_unix_utc(static_cast<gint64>(t));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_from_unix_utc_usec(int $usecs): ?GDateTime
 *
 * Creates a `DateTime` corresponding to the given Unix time $t in UTC.
 */
ZEND_METHOD(Gtk4_GDateTime, new_from_unix_utc_usec) {
  zend_long usecs;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(usecs)
  ZEND_PARSE_PARAMETERS_END();
  gpointer phpgtk_ret = g_date_time_new_from_unix_utc_usec(static_cast<gint64>(usecs));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_local(int $year, int $month, int $day, int $hour, int $minute, float
 * $seconds): ?GDateTime
 *
 * Creates a new #GDateTime corresponding to the given date and time in the local time zone.
 */
ZEND_METHOD(Gtk4_GDateTime, new_local) {
  zend_long year;
  zend_long month;
  zend_long day;
  zend_long hour;
  zend_long minute;
  double seconds;
  ZEND_PARSE_PARAMETERS_START(6, 6)
  Z_PARAM_LONG(year)
  Z_PARAM_LONG(month)
  Z_PARAM_LONG(day)
  Z_PARAM_LONG(hour)
  Z_PARAM_LONG(minute)
  Z_PARAM_DOUBLE(seconds)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_range<gint>(year, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(month, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(day, 3)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(hour, 4)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(minute, 5)) RETURN_THROWS();
  gpointer phpgtk_ret = g_date_time_new_local(static_cast<gint>(year), static_cast<gint>(month),
                                              static_cast<gint>(day), static_cast<gint>(hour),
                                              static_cast<gint>(minute), seconds);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_now(GTimeZone $tz): ?GDateTime
 *
 * Creates a #GDateTime corresponding to this exact instant in the given time zone $tz. The time is
 * as accurate as the system allows, to a maximum accuracy of 1 microsecond.
 */
ZEND_METHOD(Gtk4_GDateTime, new_now) {
  zval *tz;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(tz, boxed_class_for_type(G_TYPE_TIME_ZONE)->ce)
  ZEND_PARSE_PARAMETERS_END();
  gpointer tz_b = unwrap_boxed(tz, G_TYPE_TIME_ZONE);
  if (tz_b == nullptr) RETURN_THROWS();
  gpointer phpgtk_ret = g_date_time_new_now(static_cast<GTimeZone *>(tz_b));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_now_local(): ?GDateTime
 *
 * Creates a #GDateTime corresponding to this exact instant in the local time zone.
 */
ZEND_METHOD(Gtk4_GDateTime, new_now_local) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer phpgtk_ret = g_date_time_new_now_local();
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_now_utc(): ?GDateTime
 *
 * Creates a #GDateTime corresponding to this exact instant in UTC.
 */
ZEND_METHOD(Gtk4_GDateTime, new_now_utc) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer phpgtk_ret = g_date_time_new_now_utc();
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * static Gtk4\GDateTime::new_utc(int $year, int $month, int $day, int $hour, int $minute, float
 * $seconds): ?GDateTime
 *
 * Creates a new #GDateTime corresponding to the given date and time in UTC.
 */
ZEND_METHOD(Gtk4_GDateTime, new_utc) {
  zend_long year;
  zend_long month;
  zend_long day;
  zend_long hour;
  zend_long minute;
  double seconds;
  ZEND_PARSE_PARAMETERS_START(6, 6)
  Z_PARAM_LONG(year)
  Z_PARAM_LONG(month)
  Z_PARAM_LONG(day)
  Z_PARAM_LONG(hour)
  Z_PARAM_LONG(minute)
  Z_PARAM_DOUBLE(seconds)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_range<gint>(year, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(month, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(day, 3)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(hour, 4)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(minute, 5)) RETURN_THROWS();
  gpointer phpgtk_ret =
      g_date_time_new_utc(static_cast<gint>(year), static_cast<gint>(month), static_cast<gint>(day),
                          static_cast<gint>(hour), static_cast<gint>(minute), seconds);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add(int $timespan): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified timespan to the copy.
 */
ZEND_METHOD(Gtk4_GDateTime, add) {
  zend_long timespan;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(timespan)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<GTimeSpan>(timespan, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add(self, static_cast<GTimeSpan>(timespan));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_days(int $days): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of days to the copy. Add negative
 * values to subtract days.
 */
ZEND_METHOD(Gtk4_GDateTime, add_days) {
  zend_long days;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(days)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(days, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_days(self, static_cast<gint>(days));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_full(int $years, int $months, int $days, int $hours, int $minutes, float
 * $seconds): ?GDateTime
 *
 * Creates a new #GDateTime adding the specified values to the current date and time in $datetime.
 * Add negative values to subtract.
 */
ZEND_METHOD(Gtk4_GDateTime, add_full) {
  zend_long years;
  zend_long months;
  zend_long days;
  zend_long hours;
  zend_long minutes;
  double seconds;
  ZEND_PARSE_PARAMETERS_START(6, 6)
  Z_PARAM_LONG(years)
  Z_PARAM_LONG(months)
  Z_PARAM_LONG(days)
  Z_PARAM_LONG(hours)
  Z_PARAM_LONG(minutes)
  Z_PARAM_DOUBLE(seconds)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(years, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(months, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(days, 3)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(hours, 4)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(minutes, 5)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_full(
      self, static_cast<gint>(years), static_cast<gint>(months), static_cast<gint>(days),
      static_cast<gint>(hours), static_cast<gint>(minutes), seconds);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_hours(int $hours): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of hours. Add negative values to
 * subtract hours.
 */
ZEND_METHOD(Gtk4_GDateTime, add_hours) {
  zend_long hours;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(hours)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(hours, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_hours(self, static_cast<gint>(hours));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_minutes(int $minutes): ?GDateTime
 *
 * Creates a copy of $datetime adding the specified number of minutes. Add negative values to
 * subtract minutes.
 */
ZEND_METHOD(Gtk4_GDateTime, add_minutes) {
  zend_long minutes;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(minutes)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(minutes, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_minutes(self, static_cast<gint>(minutes));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_months(int $months): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of months to the copy. Add negative
 * values to subtract months.
 */
ZEND_METHOD(Gtk4_GDateTime, add_months) {
  zend_long months;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(months)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(months, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_months(self, static_cast<gint>(months));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_seconds(float $seconds): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of seconds. Add negative values to
 * subtract seconds.
 */
ZEND_METHOD(Gtk4_GDateTime, add_seconds) {
  double seconds;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(seconds)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  GDateTime *phpgtk_ret = g_date_time_add_seconds(self, seconds);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_weeks(int $weeks): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of weeks to the copy. Add negative
 * values to subtract weeks.
 */
ZEND_METHOD(Gtk4_GDateTime, add_weeks) {
  zend_long weeks;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(weeks)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(weeks, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_weeks(self, static_cast<gint>(weeks));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::add_years(int $years): ?GDateTime
 *
 * Creates a copy of $datetime and adds the specified number of years to the copy. Add negative
 * values to subtract years.
 */
ZEND_METHOD(Gtk4_GDateTime, add_years) {
  zend_long years;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(years)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_range<gint>(years, 1)) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_add_years(self, static_cast<gint>(years));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::compare(GDateTime $dt2): int
 *
 * A comparison function for #GDateTimes that is suitable as a #GCompareFunc. Both #GDateTimes must
 * be non-`null`.
 */
ZEND_METHOD(Gtk4_GDateTime, compare) {
  zval *dt2;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(dt2, boxed_class_for_type(G_TYPE_DATE_TIME)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  gpointer dt2_b = unwrap_boxed(dt2, G_TYPE_DATE_TIME);
  if (dt2_b == nullptr) RETURN_THROWS();
  RETURN_LONG(static_cast<zend_long>(g_date_time_compare(self, static_cast<GDateTime *>(dt2_b))));
}

/**
 * Gtk4\GDateTime::difference(GDateTime $begin): int
 *
 * Calculates the difference in time between $end and $begin. The #GTimeSpan that is returned is
 * effectively $end - $begin (ie: positive if the first parameter is larger).
 */
ZEND_METHOD(Gtk4_GDateTime, difference) {
  zval *begin;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(begin, boxed_class_for_type(G_TYPE_DATE_TIME)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  gpointer begin_b = unwrap_boxed(begin, G_TYPE_DATE_TIME);
  if (begin_b == nullptr) RETURN_THROWS();
  RETURN_LONG(
      static_cast<zend_long>(g_date_time_difference(self, static_cast<GDateTime *>(begin_b))));
}

/**
 * Gtk4\GDateTime::equal(GDateTime $dt2): bool
 *
 * Checks to see if $dt1 and $dt2 are equal.
 */
ZEND_METHOD(Gtk4_GDateTime, equal) {
  zval *dt2;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(dt2, boxed_class_for_type(G_TYPE_DATE_TIME)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  gpointer dt2_b = unwrap_boxed(dt2, G_TYPE_DATE_TIME);
  if (dt2_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(g_date_time_equal(self, static_cast<GDateTime *>(dt2_b)));
}

/**
 * Gtk4\GDateTime::format(string $format): ?string
 *
 * Creates a newly allocated string representing the requested $format.
 */
ZEND_METHOD(Gtk4_GDateTime, format) {
  zend_string *format;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(format)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  if (!phpgtk::check_utf8(format, 1)) RETURN_THROWS();
  char *phpgtk_ret = g_date_time_format(self, ZSTR_VAL(format));
  if (phpgtk_ret == nullptr) RETURN_NULL();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GDateTime::format_iso8601(): ?string
 *
 * Format $datetime in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601), including the
 * date, time and time zone, and return that as a UTF-8 encoded string.
 */
ZEND_METHOD(Gtk4_GDateTime, format_iso8601) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  char *phpgtk_ret = g_date_time_format_iso8601(self);
  if (phpgtk_ret == nullptr) RETURN_NULL();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GDateTime::get_day_of_month(): int
 *
 * Retrieves the day of the month represented by $datetime in the gregorian calendar.
 */
ZEND_METHOD(Gtk4_GDateTime, get_day_of_month) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_day_of_month(self)));
}

/**
 * Gtk4\GDateTime::get_day_of_week(): int
 *
 * Retrieves the ISO 8601 day of the week on which $datetime falls (1 is Monday, 2 is Tuesday... 7
 * is Sunday).
 */
ZEND_METHOD(Gtk4_GDateTime, get_day_of_week) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_day_of_week(self)));
}

/**
 * Gtk4\GDateTime::get_day_of_year(): int
 *
 * Retrieves the day of the year represented by $datetime in the Gregorian calendar.
 */
ZEND_METHOD(Gtk4_GDateTime, get_day_of_year) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_day_of_year(self)));
}

/**
 * Gtk4\GDateTime::get_hour(): int
 *
 * Retrieves the hour of the day represented by $datetime
 */
ZEND_METHOD(Gtk4_GDateTime, get_hour) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_hour(self)));
}

/**
 * Gtk4\GDateTime::get_microsecond(): int
 *
 * Retrieves the microsecond of the date represented by $datetime
 */
ZEND_METHOD(Gtk4_GDateTime, get_microsecond) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_microsecond(self)));
}

/**
 * Gtk4\GDateTime::get_minute(): int
 *
 * Retrieves the minute of the hour represented by $datetime
 */
ZEND_METHOD(Gtk4_GDateTime, get_minute) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_minute(self)));
}

/**
 * Gtk4\GDateTime::get_month(): int
 *
 * Retrieves the month of the year represented by $datetime in the Gregorian calendar.
 */
ZEND_METHOD(Gtk4_GDateTime, get_month) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_month(self)));
}

/**
 * Gtk4\GDateTime::get_second(): int
 *
 * Retrieves the second of the minute represented by $datetime
 */
ZEND_METHOD(Gtk4_GDateTime, get_second) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_second(self)));
}

/**
 * Gtk4\GDateTime::get_seconds(): float
 *
 * Retrieves the number of seconds since the start of the last minute, including the fractional
 * part.
 */
ZEND_METHOD(Gtk4_GDateTime, get_seconds) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_DOUBLE(g_date_time_get_seconds(self));
}

/**
 * Gtk4\GDateTime::get_timezone(): GTimeZone
 *
 * Get the time zone for this $datetime.
 */
ZEND_METHOD(Gtk4_GDateTime, get_timezone) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  GTimeZone *phpgtk_ret = g_date_time_get_timezone(self);
  wrap_boxed(G_TYPE_TIME_ZONE, phpgtk_ret, return_value);
}

/**
 * Gtk4\GDateTime::get_timezone_abbreviation(): string
 *
 * Determines the time zone abbreviation to be used at the time and in the time zone of $datetime.
 */
ZEND_METHOD(Gtk4_GDateTime, get_timezone_abbreviation) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  const char *phpgtk_ret = g_date_time_get_timezone_abbreviation(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\GDateTime::get_utc_offset(): int
 *
 * Determines the offset to UTC in effect at the time and in the time zone of $datetime.
 */
ZEND_METHOD(Gtk4_GDateTime, get_utc_offset) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_utc_offset(self)));
}

/**
 * Gtk4\GDateTime::get_week_numbering_year(): int
 *
 * Returns the ISO 8601 week-numbering year in which the week containing $datetime falls.
 */
ZEND_METHOD(Gtk4_GDateTime, get_week_numbering_year) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_week_numbering_year(self)));
}

/**
 * Gtk4\GDateTime::get_week_of_year(): int
 *
 * Returns the ISO 8601 week number for the week containing $datetime. The ISO 8601 week number is
 * the same for every day of the week (from Moday through Sunday). That can produce some unusual
 * results (described below).
 */
ZEND_METHOD(Gtk4_GDateTime, get_week_of_year) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_week_of_year(self)));
}

/**
 * Gtk4\GDateTime::get_year(): int
 *
 * Retrieves the year represented by $datetime in the Gregorian calendar.
 */
ZEND_METHOD(Gtk4_GDateTime, get_year) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_get_year(self)));
}

/**
 * Gtk4\GDateTime::get_ymd(): array
 *
 * Retrieves the Gregorian day, month, and year of a given #GDateTime.
 */
ZEND_METHOD(Gtk4_GDateTime, get_ymd) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  gint year = 0;
  gint month = 0;
  gint day = 0;
  g_date_time_get_ymd(self, &year, &month, &day);
  array_init_size(return_value, 3);
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(year));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(month));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(day));
    add_next_index_zval(return_value, &item);
  }
}

/**
 * Gtk4\GDateTime::hash(): int
 *
 * Hashes $datetime into a #guint, suitable for use within #GHashTable.
 */
ZEND_METHOD(Gtk4_GDateTime, hash) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_hash(self)));
}

/**
 * Gtk4\GDateTime::is_daylight_savings(): bool
 *
 * Determines if daylight savings time is in effect at the time and in the time zone of $datetime.
 */
ZEND_METHOD(Gtk4_GDateTime, is_daylight_savings) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_BOOL(g_date_time_is_daylight_savings(self));
}

/**
 * Gtk4\GDateTime::to_local(): ?GDateTime
 *
 * Creates a new #GDateTime corresponding to the same instant in time as $datetime, but in the
 * local time zone.
 */
ZEND_METHOD(Gtk4_GDateTime, to_local) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  GDateTime *phpgtk_ret = g_date_time_to_local(self);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::to_timezone(GTimeZone $tz): ?GDateTime
 *
 * Create a new #GDateTime corresponding to the same instant in time as $datetime, but in the time
 * zone $tz.
 */
ZEND_METHOD(Gtk4_GDateTime, to_timezone) {
  zval *tz;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(tz, boxed_class_for_type(G_TYPE_TIME_ZONE)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  gpointer tz_b = unwrap_boxed(tz, G_TYPE_TIME_ZONE);
  if (tz_b == nullptr) RETURN_THROWS();
  GDateTime *phpgtk_ret = g_date_time_to_timezone(self, static_cast<GTimeZone *>(tz_b));
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

/**
 * Gtk4\GDateTime::to_unix(): int
 *
 * Gives the Unix time corresponding to $datetime, rounding down to the nearest second.
 */
ZEND_METHOD(Gtk4_GDateTime, to_unix) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_to_unix(self)));
}

/**
 * Gtk4\GDateTime::to_unix_usec(): int
 *
 * Gives the Unix time corresponding to $datetime, in microseconds.
 */
ZEND_METHOD(Gtk4_GDateTime, to_unix_usec) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  RETURN_LONG(static_cast<zend_long>(g_date_time_to_unix_usec(self)));
}

/**
 * Gtk4\GDateTime::to_utc(): ?GDateTime
 *
 * Creates a new #GDateTime corresponding to the same instant in time as $datetime, but in UTC.
 */
ZEND_METHOD(Gtk4_GDateTime, to_utc) {
  ZEND_PARSE_PARAMETERS_NONE();
  GDateTime *self = PHPGTK_BOXED_SELF(GDateTime);
  GDateTime *phpgtk_ret = g_date_time_to_utc(self);
  wrap_boxed(G_TYPE_DATE_TIME, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(G_TYPE_DATE_TIME, phpgtk_ret);
}

namespace phpgtk {
// MINIT: bind the PHP class to G_TYPE_DATE_TIME with its field table.
void register_GDateTime(zend_class_entry *ce) {
  register_boxed(BoxedClass{
      .type = G_TYPE_DATE_TIME,
      .ce = ce,
      .fields = fields,
      .read = read,
      .write = write,
      // NOLINTBEGIN(cppcoreguidelines-pro-type-const-cast) g_date_time_equal() takes non-const
      // operands
      .equal =
          [](gconstpointer a, gconstpointer b) {
            return g_date_time_equal(static_cast<GDateTime *>(const_cast<gpointer>(a)),
                                     static_cast<GDateTime *>(const_cast<gpointer>(b))) != FALSE;
          }
      // NOLINTEND(cppcoreguidelines-pro-type-const-cast)
  });
}
}  // namespace phpgtk
