// GENERATED by gen/gir.php from GLib.KeyFile - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GKeyFile (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>
#include "core/collections.h"
#include "core/gerror.h"

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\GKeyFile::__construct()
 *
 * Creates a new empty #GKeyFile object. Use g_key_file_load_from_file(),
 * g_key_file_load_from_data(), g_key_file_load_from_dirs() or g_key_file_load_from_data_dirs() to
 * read an existing key file.
 */
ZEND_METHOD(Gtk4_GKeyFile, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer obj = g_key_file_new();
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the value (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  boxed_adopt(boxed_from_zval(ZEND_THIS), G_TYPE_KEY_FILE, obj);
}

/**
 * Gtk4\GKeyFile::get_boolean(string $group_name, string $key): bool
 *
 * Returns the value associated with $key under $group_name as a boolean.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_boolean) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_get_boolean(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::get_boolean_list(string $group_name, string $key): array
 *
 * Returns the values associated with $key under $group_name as booleans.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_boolean_list) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  gboolean *phpgtk_ret =
      g_key_file_get_boolean_list(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  array_init(return_value);
  for (gsize i = 0; phpgtk_ret != nullptr && i < length; i++) {
    add_next_index_bool(return_value, phpgtk_ret[i] != FALSE);
  }
}

/**
 * Gtk4\GKeyFile::get_comment(?string $group_name, ?string $key): string
 *
 * Retrieves a comment above $key from $group_name. If $key is `null` then $comment will be read
 * from above $group_name. If both $key and $group_name are `null`, then $comment will be read from
 * above the first group in the file.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_comment) {
  zend_string *group_name = nullptr;
  zend_string *key = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(group_name)
  Z_PARAM_STR_OR_NULL(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (group_name != nullptr && !phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (key != nullptr && !phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  char *phpgtk_ret =
      g_key_file_get_comment(self, group_name != nullptr ? ZSTR_VAL(group_name) : nullptr,
                             key != nullptr ? ZSTR_VAL(key) : nullptr, &error);
  if (phpgtk_ret == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::get_double(string $group_name, string $key): float
 *
 * Returns the value associated with $key under $group_name as a double. If $group_name is `null`,
 * the start_group is used.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_double) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const double value = g_key_file_get_double(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_DOUBLE(value);
}

/**
 * Gtk4\GKeyFile::get_double_list(string $group_name, string $key): array
 *
 * Returns the values associated with $key under $group_name as doubles.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_double_list) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  gdouble *phpgtk_ret =
      g_key_file_get_double_list(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  array_init(return_value);
  for (gsize i = 0; phpgtk_ret != nullptr && i < length; i++) {
    add_next_index_double(return_value, phpgtk_ret[i]);
  }
}

/**
 * Gtk4\GKeyFile::get_groups(): array
 *
 * Returns all groups in the key file loaded with $key_file. The array of returned groups will be
 * `null`-terminated, so $length may optionally be `null`.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_groups) {
  ZEND_PARSE_PARAMETERS_NONE();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  gsize length = 0;
  char **phpgtk_ret = g_key_file_get_groups(self, &length);
  strv_to_php(phpgtk_ret, length, Transfer::Full, return_value);
}

/**
 * Gtk4\GKeyFile::get_int64(string $group_name, string $key): int
 *
 * Returns the value associated with $key under $group_name as a signed 64-bit integer. This is
 * similar to g_key_file_get_integer() but can return 64-bit results without truncation.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_int64) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const auto value = static_cast<zend_long>(
      g_key_file_get_int64(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}

/**
 * Gtk4\GKeyFile::get_integer(string $group_name, string $key): int
 *
 * Returns the value associated with $key under $group_name as an integer.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_integer) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const auto value = static_cast<zend_long>(
      g_key_file_get_integer(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}

/**
 * Gtk4\GKeyFile::get_integer_list(string $group_name, string $key): array
 *
 * Returns the values associated with $key under $group_name as integers.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_integer_list) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  gint *phpgtk_ret =
      g_key_file_get_integer_list(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  array_init(return_value);
  for (gsize i = 0; phpgtk_ret != nullptr && i < length; i++) {
    add_next_index_long(return_value, static_cast<zend_long>(phpgtk_ret[i]));
  }
}

/**
 * Gtk4\GKeyFile::get_keys(string $group_name): array
 *
 * Returns all keys for the group name $group_name. The array of returned keys will be
 * `null`-terminated, so $length may optionally be `null`. In the event that the $group_name cannot
 * be found, `null` is returned and $error is set to %G_KEY_FILE_ERROR_GROUP_NOT_FOUND.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_keys) {
  zend_string *group_name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(group_name)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  char **phpgtk_ret = g_key_file_get_keys(self, ZSTR_VAL(group_name), &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  strv_to_php(phpgtk_ret, length, Transfer::Full, return_value);
}

/**
 * Gtk4\GKeyFile::get_locale_for_key(string $group_name, string $key, ?string $locale): ?string
 *
 * Returns the actual locale which the result of g_key_file_get_locale_string() or
 * g_key_file_get_locale_string_list() came from.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_locale_for_key) {
  zend_string *group_name;
  zend_string *key;
  zend_string *locale = nullptr;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR_OR_NULL(locale)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (locale != nullptr && !phpgtk::check_utf8(locale, 3)) RETURN_THROWS();
  char *phpgtk_ret = g_key_file_get_locale_for_key(self, ZSTR_VAL(group_name), ZSTR_VAL(key),
                                                   locale != nullptr ? ZSTR_VAL(locale) : nullptr);
  if (phpgtk_ret == nullptr) RETURN_NULL();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::get_locale_string(string $group_name, string $key, ?string $locale): string
 *
 * Returns the value associated with $key under $group_name translated in the given $locale if
 * available. If $locale is `null` then the current locale is assumed.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_locale_string) {
  zend_string *group_name;
  zend_string *key;
  zend_string *locale = nullptr;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR_OR_NULL(locale)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (locale != nullptr && !phpgtk::check_utf8(locale, 3)) RETURN_THROWS();
  GError *error = nullptr;
  char *phpgtk_ret =
      g_key_file_get_locale_string(self, ZSTR_VAL(group_name), ZSTR_VAL(key),
                                   locale != nullptr ? ZSTR_VAL(locale) : nullptr, &error);
  if (phpgtk_ret == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::get_locale_string_list(string $group_name, string $key, ?string $locale): array
 *
 * Returns the values associated with $key under $group_name translated in the given $locale if
 * available. If $locale is `null` then the current locale is assumed.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_locale_string_list) {
  zend_string *group_name;
  zend_string *key;
  zend_string *locale = nullptr;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR_OR_NULL(locale)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (locale != nullptr && !phpgtk::check_utf8(locale, 3)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  char **phpgtk_ret = g_key_file_get_locale_string_list(
      self, ZSTR_VAL(group_name), ZSTR_VAL(key), locale != nullptr ? ZSTR_VAL(locale) : nullptr,
      &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  strv_to_php(phpgtk_ret, length, Transfer::Full, return_value);
}

/**
 * Gtk4\GKeyFile::get_start_group(): ?string
 *
 * Returns the name of the start group of the file.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_start_group) {
  ZEND_PARSE_PARAMETERS_NONE();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  char *phpgtk_ret = g_key_file_get_start_group(self);
  if (phpgtk_ret == nullptr) RETURN_NULL();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::get_string(string $group_name, string $key): string
 *
 * Returns the string value associated with $key under $group_name. Unlike g_key_file_get_value(),
 * this function handles escape sequences like \s.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_string) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  char *phpgtk_ret = g_key_file_get_string(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (phpgtk_ret == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::get_string_list(string $group_name, string $key): array
 *
 * Returns the values associated with $key under $group_name.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_string_list) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  gsize length = 0;
  GError *error = nullptr;
  char **phpgtk_ret =
      g_key_file_get_string_list(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  strv_to_php(phpgtk_ret, length, Transfer::Full, return_value);
}

/**
 * Gtk4\GKeyFile::get_uint64(string $group_name, string $key): int
 *
 * Returns the value associated with $key under $group_name as an unsigned 64-bit integer. This is
 * similar to g_key_file_get_integer() but can return large positive results without truncation.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_uint64) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const auto value = static_cast<zend_long>(
      g_key_file_get_uint64(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}

/**
 * Gtk4\GKeyFile::get_value(string $group_name, string $key): string
 *
 * Returns the raw value associated with $key under $group_name. Use g_key_file_get_string() to
 * retrieve an unescaped UTF-8 string.
 */
ZEND_METHOD(Gtk4_GKeyFile, get_value) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  char *phpgtk_ret = g_key_file_get_value(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (phpgtk_ret == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GKeyFile::has_group(string $group_name): bool
 *
 * Looks whether the key file has the group $group_name.
 */
ZEND_METHOD(Gtk4_GKeyFile, has_group) {
  zend_string *group_name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(group_name)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  RETURN_BOOL(g_key_file_has_group(self, ZSTR_VAL(group_name)));
}

/**
 * Gtk4\GKeyFile::has_key(string $group_name, string $key): bool
 *
 * Looks whether the key file has the key $key in the group $group_name.
 */
ZEND_METHOD(Gtk4_GKeyFile, has_key) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_has_key(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::load_from_bytes(string $bytes, int $flags): bool
 *
 * Loads a key file from the data in $bytes into an empty #GKeyFile structure. If the object cannot
 * be created then %error is set to a #GKeyFileError.
 */
ZEND_METHOD(Gtk4_GKeyFile, load_from_bytes) {
  zend_string *bytes;
  zend_long flags;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(bytes)
  Z_PARAM_LONG(flags)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  GBytes *bytes_b = g_bytes_new(ZSTR_VAL(bytes), ZSTR_LEN(bytes));
  GError *error = nullptr;
  const gboolean ok =
      g_key_file_load_from_bytes(self, bytes_b, static_cast<GKeyFileFlags>(flags), &error);
  g_bytes_unref(bytes_b);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::load_from_data(string $data, int $length, int $flags): bool
 *
 * Loads a key file from memory into an empty #GKeyFile structure. If the object cannot be created
 * then %error is set to a #GKeyFileError.
 */
ZEND_METHOD(Gtk4_GKeyFile, load_from_data) {
  zend_string *data;
  zend_long length;
  zend_long flags;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(data)
  Z_PARAM_LONG(length)
  Z_PARAM_LONG(flags)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(data, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<gsize>(length, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_load_from_data(self, ZSTR_VAL(data), static_cast<gsize>(length),
                                                static_cast<GKeyFileFlags>(flags), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::load_from_data_dirs(string $file, int $flags): ?string
 *
 * This function looks for a key file named $file in the paths returned from g_get_user_data_dir()
 * and g_get_system_data_dirs(), loads the file into $key_file and returns the file's full path in
 * $full_path. If the file could not be loaded then an %error is set to either a #GFileError or
 * #GKeyFileError.
 */
ZEND_METHOD(Gtk4_GKeyFile, load_from_data_dirs) {
  zend_string *file;
  zend_long flags;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_PATH_STR(file)
  Z_PARAM_LONG(flags)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  const bool precondition_0 = !g_path_is_absolute(ZSTR_VAL(file));
  if (!precondition_0) {
    zend_argument_value_error(1,
                              "must be a relative path: it is looked up in the data directories");
    RETURN_THROWS();
  }
  char *full_path = nullptr;
  GError *error = nullptr;
  if (!g_key_file_load_from_data_dirs(self, ZSTR_VAL(file), &full_path,
                                      static_cast<GKeyFileFlags>(flags), &error))
    RETURN_NULL();
  if (full_path == nullptr) {
    ZVAL_NULL(return_value);
  } else {
    ZVAL_STRING(return_value, full_path);
  }
}

/**
 * Gtk4\GKeyFile::load_from_file(string $file, int $flags): bool
 *
 * Loads a key file into an empty #GKeyFile structure.
 */
ZEND_METHOD(Gtk4_GKeyFile, load_from_file) {
  zend_string *file;
  zend_long flags;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_PATH_STR(file)
  Z_PARAM_LONG(flags)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  zend_string *file_abs = phpgtk::absolute_filename(file, 1);
  if (file_abs == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_load_from_file(self, ZSTR_VAL(file_abs),
                                                static_cast<GKeyFileFlags>(flags), &error);
  if (file_abs != nullptr) zend_string_release(file_abs);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::remove_comment(?string $group_name, ?string $key): bool
 *
 * Removes a comment above $key from $group_name. If $key is `null` then $comment will be removed
 * above $group_name. If both $key and $group_name are `null`, then $comment will be removed above
 * the first group in the file.
 */
ZEND_METHOD(Gtk4_GKeyFile, remove_comment) {
  zend_string *group_name = nullptr;
  zend_string *key = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(group_name)
  Z_PARAM_STR_OR_NULL(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (group_name != nullptr && !phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (key != nullptr && !phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok =
      g_key_file_remove_comment(self, group_name != nullptr ? ZSTR_VAL(group_name) : nullptr,
                                key != nullptr ? ZSTR_VAL(key) : nullptr, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::remove_group(string $group_name): bool
 *
 * Removes the specified group, $group_name, from the key file.
 */
ZEND_METHOD(Gtk4_GKeyFile, remove_group) {
  zend_string *group_name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(group_name)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_remove_group(self, ZSTR_VAL(group_name), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::remove_key(string $group_name, string $key): bool
 *
 * Removes $key in $group_name from the key file.
 */
ZEND_METHOD(Gtk4_GKeyFile, remove_key) {
  zend_string *group_name;
  zend_string *key;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_remove_key(self, ZSTR_VAL(group_name), ZSTR_VAL(key), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::save_to_file(string $filename): bool
 *
 * Writes the contents of $key_file to $filename using g_file_set_contents(). If you need stricter
 * guarantees about durability of the written file than are provided by g_file_set_contents(), use
 * g_file_set_contents_full() with the return value of g_key_file_to_data().
 */
ZEND_METHOD(Gtk4_GKeyFile, save_to_file) {
  zend_string *filename;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(filename)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(filename, 1)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_key_file_save_to_file(self, ZSTR_VAL(filename), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::set_boolean(string $group_name, string $key, bool $value): void
 *
 * Associates a new boolean value with $key under $group_name. If $key cannot be found then it is
 * created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_boolean) {
  zend_string *group_name;
  zend_string *key;
  bool value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_BOOL(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  g_key_file_set_boolean(self, ZSTR_VAL(group_name), ZSTR_VAL(key), value);
}

/**
 * Gtk4\GKeyFile::set_comment(?string $group_name, ?string $key, string $comment): bool
 *
 * Places a comment above $key from $group_name.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_comment) {
  zend_string *group_name = nullptr;
  zend_string *key = nullptr;
  zend_string *comment;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR_OR_NULL(group_name)
  Z_PARAM_STR_OR_NULL(key)
  Z_PARAM_STR(comment)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (group_name != nullptr && !phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (key != nullptr && !phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_utf8(comment, 3)) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok =
      g_key_file_set_comment(self, group_name != nullptr ? ZSTR_VAL(group_name) : nullptr,
                             key != nullptr ? ZSTR_VAL(key) : nullptr, ZSTR_VAL(comment), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GKeyFile::set_double(string $group_name, string $key, float $value): void
 *
 * Associates a new double value with $key under $group_name. If $key cannot be found then it is
 * created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_double) {
  zend_string *group_name;
  zend_string *key;
  double value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_DOUBLE(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  g_key_file_set_double(self, ZSTR_VAL(group_name), ZSTR_VAL(key), value);
}

/**
 * Gtk4\GKeyFile::set_int64(string $group_name, string $key, int $value): void
 *
 * Associates a new integer value with $key under $group_name. If $key cannot be found then it is
 * created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_int64) {
  zend_string *group_name;
  zend_string *key;
  zend_long value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_LONG(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  g_key_file_set_int64(self, ZSTR_VAL(group_name), ZSTR_VAL(key), static_cast<gint64>(value));
}

/**
 * Gtk4\GKeyFile::set_integer(string $group_name, string $key, int $value): void
 *
 * Associates a new integer value with $key under $group_name. If $key cannot be found then it is
 * created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_integer) {
  zend_string *group_name;
  zend_string *key;
  zend_long value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_LONG(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<gint>(value, 3)) RETURN_THROWS();
  g_key_file_set_integer(self, ZSTR_VAL(group_name), ZSTR_VAL(key), static_cast<gint>(value));
}

/**
 * Gtk4\GKeyFile::set_list_separator(int $separator): void
 *
 * Sets the character which is used to separate values in lists. Typically ';' or ',' are used as
 * separators. The default list separator is ';'.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_list_separator) {
  zend_long separator;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(separator)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_range<gchar>(separator, 1)) RETURN_THROWS();
  g_key_file_set_list_separator(self, static_cast<gchar>(separator));
}

/**
 * Gtk4\GKeyFile::set_locale_string(string $group_name, string $key, string $locale, string
 * $string): void
 *
 * Associates a string value for $key and $locale under $group_name. If the translation for $key
 * cannot be found then it is created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_locale_string) {
  zend_string *group_name;
  zend_string *key;
  zend_string *locale;
  zend_string *string;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR(locale)
  Z_PARAM_STR(string)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_utf8(locale, 3)) RETURN_THROWS();
  if (!phpgtk::check_utf8(string, 4)) RETURN_THROWS();
  g_key_file_set_locale_string(self, ZSTR_VAL(group_name), ZSTR_VAL(key), ZSTR_VAL(locale),
                               ZSTR_VAL(string));
}

/**
 * Gtk4\GKeyFile::set_string(string $group_name, string $key, string $string): void
 *
 * Associates a new string value with $key under $group_name. If $key cannot be found then it is
 * created. If $group_name cannot be found then it is created. Unlike g_key_file_set_value(), this
 * function handles characters that need escaping, such as newlines.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_string) {
  zend_string *group_name;
  zend_string *key;
  zend_string *string;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR(string)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_utf8(string, 3)) RETURN_THROWS();
  g_key_file_set_string(self, ZSTR_VAL(group_name), ZSTR_VAL(key), ZSTR_VAL(string));
}

/**
 * Gtk4\GKeyFile::set_uint64(string $group_name, string $key, int $value): void
 *
 * Associates a new integer value with $key under $group_name. If $key cannot be found then it is
 * created.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_uint64) {
  zend_string *group_name;
  zend_string *key;
  zend_long value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_LONG(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<guint64>(value, 3)) RETURN_THROWS();
  g_key_file_set_uint64(self, ZSTR_VAL(group_name), ZSTR_VAL(key), static_cast<guint64>(value));
}

/**
 * Gtk4\GKeyFile::set_value(string $group_name, string $key, string $value): void
 *
 * Associates a new value with $key under $group_name.
 */
ZEND_METHOD(Gtk4_GKeyFile, set_value) {
  zend_string *group_name;
  zend_string *key;
  zend_string *value;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(group_name)
  Z_PARAM_STR(key)
  Z_PARAM_STR(value)
  ZEND_PARSE_PARAMETERS_END();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  if (!phpgtk::check_utf8(group_name, 1)) RETURN_THROWS();
  if (!phpgtk::check_utf8(key, 2)) RETURN_THROWS();
  if (!phpgtk::check_utf8(value, 3)) RETURN_THROWS();
  g_key_file_set_value(self, ZSTR_VAL(group_name), ZSTR_VAL(key), ZSTR_VAL(value));
}

/**
 * Gtk4\GKeyFile::to_data(): string
 *
 * This function outputs $key_file as a string.
 */
ZEND_METHOD(Gtk4_GKeyFile, to_data) {
  ZEND_PARSE_PARAMETERS_NONE();
  GKeyFile *self = PHPGTK_BOXED_SELF(GKeyFile);
  gsize length = 0;
  GError *error = nullptr;
  char *phpgtk_ret = g_key_file_to_data(self, &length, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  if (phpgtk_ret == nullptr) RETURN_NULL();
  RETVAL_STRINGL(phpgtk_ret, static_cast<size_t>(length));
  g_free(phpgtk_ret);
}

/**
 * static Gtk4\GKeyFile::error_quark(): int
 */
ZEND_METHOD(Gtk4_GKeyFile, error_quark) {
  ZEND_PARSE_PARAMETERS_NONE();
  RETURN_LONG(static_cast<zend_long>(g_key_file_error_quark()));
}

namespace phpgtk {
// MINIT: bind the PHP class to G_TYPE_KEY_FILE with its field table.
void register_GKeyFile(zend_class_entry *ce) {
  register_boxed(BoxedClass{
      .type = G_TYPE_KEY_FILE, .ce = ce, .fields = fields, .read = read, .write = write});
}
}  // namespace phpgtk
