<?php

/**
 * GENERATED by gen/gir.php from GLib GIR - do not edit; edit gen/overrides, gen/skip.txt
 * or gen/allowlist.txt and regenerate (./ci.sh --only=gen --fix).
 *
 * @generate-class-entries
 * @generate-legacy-arginfo 80400
 */

namespace Gtk4;

/**
 * `GDateTime` is a structure that combines a Gregorian date and time into a single structure.
 * @not-serializable
 */
final class GDateTime
{
    /** Creates a new #GDateTime corresponding to the given date and time in the time zone $tz. */
    public function __construct(GTimeZone $tz, int $year, int $month, int $day, int $hour, int $minute, float $seconds) {}

    /**
     * Creates a #GDateTime corresponding to the given [ISO 8601 formatted
     * string](https://en.wikipedia.org/wiki/ISO_8601) $text. ISO 8601 strings of the form
     * <date><sep><time><tz> are supported, with some extensions from [RFC
     * 3339](https://tools.ietf.org/html/rfc3339) as mentioned below.
     */
    public static function new_from_iso8601(string $text, ?GTimeZone $default_tz = null): GDateTime {}

    /** Creates a #GDateTime corresponding to the given Unix time $t in the local time zone. */
    public static function new_from_unix_local(int $t): GDateTime {}

    /** Creates a `DateTime` corresponding to the given Unix time $t in the local time zone. */
    public static function new_from_unix_local_usec(int $usecs): GDateTime {}

    /** Creates a #GDateTime corresponding to the given Unix time $t in UTC. */
    public static function new_from_unix_utc(int $t): GDateTime {}

    /** Creates a `DateTime` corresponding to the given Unix time $t in UTC. */
    public static function new_from_unix_utc_usec(int $usecs): GDateTime {}

    /** Creates a new #GDateTime corresponding to the given date and time in the local time zone. */
    public static function new_local(int $year, int $month, int $day, int $hour, int $minute, float $seconds): GDateTime {}

    /**
     * Creates a #GDateTime corresponding to this exact instant in the given time zone $tz. The
     * time is as accurate as the system allows, to a maximum accuracy of 1 microsecond.
     */
    public static function new_now(GTimeZone $tz): GDateTime {}

    /** Creates a #GDateTime corresponding to this exact instant in the local time zone. */
    public static function new_now_local(): GDateTime {}

    /** Creates a #GDateTime corresponding to this exact instant in UTC. */
    public static function new_now_utc(): GDateTime {}

    /** Creates a new #GDateTime corresponding to the given date and time in UTC. */
    public static function new_utc(int $year, int $month, int $day, int $hour, int $minute, float $seconds): GDateTime {}

    /** Creates a copy of $datetime and adds the specified timespan to the copy. */
    public function add(int $timespan): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of days to the copy. Add negative
     * values to subtract days.
     */
    public function add_days(int $days): ?GDateTime {}

    /**
     * Creates a new #GDateTime adding the specified values to the current date and time in
     * $datetime. Add negative values to subtract.
     */
    public function add_full(int $years, int $months, int $days, int $hours, int $minutes, float $seconds): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of hours. Add negative values to
     * subtract hours.
     */
    public function add_hours(int $hours): ?GDateTime {}

    /**
     * Creates a copy of $datetime adding the specified number of minutes. Add negative values to
     * subtract minutes.
     */
    public function add_minutes(int $minutes): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of months to the copy. Add
     * negative values to subtract months.
     */
    public function add_months(int $months): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of seconds. Add negative values to
     * subtract seconds.
     */
    public function add_seconds(float $seconds): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of weeks to the copy. Add negative
     * values to subtract weeks.
     */
    public function add_weeks(int $weeks): ?GDateTime {}

    /**
     * Creates a copy of $datetime and adds the specified number of years to the copy. Add negative
     * values to subtract years.
     */
    public function add_years(int $years): ?GDateTime {}

    /**
     * A comparison function for #GDateTimes that is suitable as a #GCompareFunc. Both #GDateTimes
     * must be non-`null`.
     */
    public function compare(GDateTime $dt2): int {}

    /**
     * Calculates the difference in time between $end and $begin. The #GTimeSpan that is returned
     * is effectively $end - $begin (ie: positive if the first parameter is larger).
     */
    public function difference(GDateTime $begin): int {}

    /** Checks to see if $dt1 and $dt2 are equal. */
    public function equal(GDateTime $dt2): bool {}

    /** Creates a newly allocated string representing the requested $format. */
    public function format(string $format): ?string {}

    /**
     * Format $datetime in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601), including the
     * date, time and time zone, and return that as a UTF-8 encoded string.
     */
    public function format_iso8601(): ?string {}

    /** Retrieves the day of the month represented by $datetime in the gregorian calendar. */
    public function get_day_of_month(): int {}

    /**
     * Retrieves the ISO 8601 day of the week on which $datetime falls (1 is Monday, 2 is
     * Tuesday... 7 is Sunday).
     */
    public function get_day_of_week(): int {}

    /** Retrieves the day of the year represented by $datetime in the Gregorian calendar. */
    public function get_day_of_year(): int {}

    /** Retrieves the hour of the day represented by $datetime */
    public function get_hour(): int {}

    /** Retrieves the microsecond of the date represented by $datetime */
    public function get_microsecond(): int {}

    /** Retrieves the minute of the hour represented by $datetime */
    public function get_minute(): int {}

    /** Retrieves the month of the year represented by $datetime in the Gregorian calendar. */
    public function get_month(): int {}

    /** Retrieves the second of the minute represented by $datetime */
    public function get_second(): int {}

    /**
     * Retrieves the number of seconds since the start of the last minute, including the fractional
     * part.
     */
    public function get_seconds(): float {}

    /** Get the time zone for this $datetime. */
    public function get_timezone(): GTimeZone {}

    /**
     * Determines the time zone abbreviation to be used at the time and in the time zone of
     * $datetime.
     */
    public function get_timezone_abbreviation(): string {}

    /** Determines the offset to UTC in effect at the time and in the time zone of $datetime. */
    public function get_utc_offset(): int {}

    /** Returns the ISO 8601 week-numbering year in which the week containing $datetime falls. */
    public function get_week_numbering_year(): int {}

    /**
     * Returns the ISO 8601 week number for the week containing $datetime. The ISO 8601 week number
     * is the same for every day of the week (from Moday through Sunday). That can produce some
     * unusual results (described below).
     */
    public function get_week_of_year(): int {}

    /** Retrieves the year represented by $datetime in the Gregorian calendar. */
    public function get_year(): int {}

    /**
     * Retrieves the Gregorian day, month, and year of a given #GDateTime.
     *
     * @return array{int, int, int}
     */
    public function get_ymd(): array {}

    /** Hashes $datetime into a #guint, suitable for use within #GHashTable. */
    public function hash(): int {}

    /**
     * Determines if daylight savings time is in effect at the time and in the time zone of
     * $datetime.
     */
    public function is_daylight_savings(): bool {}

    /**
     * Creates a new #GDateTime corresponding to the same instant in time as $datetime, but in the
     * local time zone.
     */
    public function to_local(): ?GDateTime {}

    /**
     * Create a new #GDateTime corresponding to the same instant in time as $datetime, but in the
     * time zone $tz.
     */
    public function to_timezone(GTimeZone $tz): ?GDateTime {}

    /** Gives the Unix time corresponding to $datetime, rounding down to the nearest second. */
    public function to_unix(): int {}

    /** Gives the Unix time corresponding to $datetime, in microseconds. */
    public function to_unix_usec(): int {}

    /**
     * Creates a new #GDateTime corresponding to the same instant in time as $datetime, but in UTC.
     */
    public function to_utc(): ?GDateTime {}
}

/**
 * `GKeyFile` parses .ini-like config files.
 * @not-serializable
 */
final class GKeyFile
{
    /**
     * Creates a new empty #GKeyFile object. Use g_key_file_load_from_file(),
     * g_key_file_load_from_data(), g_key_file_load_from_dirs() or g_key_file_load_from_data_dirs()
     * to read an existing key file.
     */
    public function __construct() {}

    /** Returns the value associated with $key under $group_name as a boolean. */
    public function get_boolean(string $group_name, string $key): bool {}

    /**
     * Returns the values associated with $key under $group_name as booleans.
     *
     * @return list<bool>
     */
    public function get_boolean_list(string $group_name, string $key): array {}

    /**
     * Retrieves a comment above $key from $group_name. If $key is `null` then $comment will be
     * read from above $group_name. If both $key and $group_name are `null`, then $comment will be
     * read from above the first group in the file.
     */
    public function get_comment(?string $group_name, ?string $key): string {}

    /**
     * Returns the value associated with $key under $group_name as a double. If $group_name is
     * `null`, the start_group is used.
     */
    public function get_double(string $group_name, string $key): float {}

    /**
     * Returns the values associated with $key under $group_name as doubles.
     *
     * @return list<float>
     */
    public function get_double_list(string $group_name, string $key): array {}

    /**
     * Returns all groups in the key file loaded with $key_file. The array of returned groups will
     * be `null`-terminated, so $length may optionally be `null`.
     *
     * @return list<string>
     */
    public function get_groups(): array {}

    /**
     * Returns the value associated with $key under $group_name as a signed 64-bit integer. This is
     * similar to g_key_file_get_integer() but can return 64-bit results without truncation.
     */
    public function get_int64(string $group_name, string $key): int {}

    /** Returns the value associated with $key under $group_name as an integer. */
    public function get_integer(string $group_name, string $key): int {}

    /**
     * Returns the values associated with $key under $group_name as integers.
     *
     * @return list<int>
     */
    public function get_integer_list(string $group_name, string $key): array {}

    /**
     * Returns all keys for the group name $group_name. The array of returned keys will be
     * `null`-terminated, so $length may optionally be `null`. In the event that the $group_name
     * cannot be found, `null` is returned and $error is set to %G_KEY_FILE_ERROR_GROUP_NOT_FOUND.
     *
     * @return list<string>
     */
    public function get_keys(string $group_name): array {}

    /**
     * Returns the actual locale which the result of g_key_file_get_locale_string() or
     * g_key_file_get_locale_string_list() came from.
     */
    public function get_locale_for_key(string $group_name, string $key, ?string $locale): ?string {}

    /**
     * Returns the value associated with $key under $group_name translated in the given $locale if
     * available. If $locale is `null` then the current locale is assumed.
     */
    public function get_locale_string(string $group_name, string $key, ?string $locale): string {}

    /**
     * Returns the values associated with $key under $group_name translated in the given $locale if
     * available. If $locale is `null` then the current locale is assumed.
     *
     * @return list<string>
     */
    public function get_locale_string_list(string $group_name, string $key, ?string $locale): array {}

    /** Returns the name of the start group of the file. */
    public function get_start_group(): ?string {}

    /**
     * Returns the string value associated with $key under $group_name. Unlike
     * g_key_file_get_value(), this function handles escape sequences like \s.
     */
    public function get_string(string $group_name, string $key): string {}

    /**
     * Returns the values associated with $key under $group_name.
     *
     * @return list<string>
     */
    public function get_string_list(string $group_name, string $key): array {}

    /**
     * Returns the value associated with $key under $group_name as an unsigned 64-bit integer. This
     * is similar to g_key_file_get_integer() but can return large positive results without
     * truncation.
     */
    public function get_uint64(string $group_name, string $key): int {}

    /**
     * Returns the raw value associated with $key under $group_name. Use g_key_file_get_string() to
     * retrieve an unescaped UTF-8 string.
     */
    public function get_value(string $group_name, string $key): string {}

    /** Looks whether the key file has the group $group_name. */
    public function has_group(string $group_name): bool {}

    /** Looks whether the key file has the key $key in the group $group_name. */
    public function has_key(string $group_name, string $key): bool {}

    /**
     * Loads a key file from the data in $bytes into an empty #GKeyFile structure. If the object
     * cannot be created then %error is set to a #GKeyFileError.
     */
    public function load_from_bytes(string $bytes, int $flags): bool {}

    /**
     * Loads a key file from memory into an empty #GKeyFile structure. If the object cannot be
     * created then %error is set to a #GKeyFileError.
     */
    public function load_from_data(string $data, int $length, int $flags): bool {}

    /**
     * This function looks for a key file named $file in the paths returned from
     * g_get_user_data_dir() and g_get_system_data_dirs(), loads the file into $key_file and
     * returns the file's full path in $full_path. If the file could not be loaded then an %error
     * is set to either a #GFileError or #GKeyFileError.
     */
    public function load_from_data_dirs(string $file, int $flags): ?string {}

    /** Loads a key file into an empty #GKeyFile structure. */
    public function load_from_file(string $file, int $flags): bool {}

    /**
     * Removes a comment above $key from $group_name. If $key is `null` then $comment will be
     * removed above $group_name. If both $key and $group_name are `null`, then $comment will be
     * removed above the first group in the file.
     */
    public function remove_comment(?string $group_name, ?string $key): bool {}

    /** Removes the specified group, $group_name, from the key file. */
    public function remove_group(string $group_name): bool {}

    /** Removes $key in $group_name from the key file. */
    public function remove_key(string $group_name, string $key): bool {}

    /**
     * Writes the contents of $key_file to $filename using g_file_set_contents(). If you need
     * stricter guarantees about durability of the written file than are provided by
     * g_file_set_contents(), use g_file_set_contents_full() with the return value of
     * g_key_file_to_data().
     */
    public function save_to_file(string $filename): bool {}

    /**
     * Associates a new boolean value with $key under $group_name. If $key cannot be found then it
     * is created.
     */
    public function set_boolean(string $group_name, string $key, bool $value): void {}

    /** Places a comment above $key from $group_name. */
    public function set_comment(?string $group_name, ?string $key, string $comment): bool {}

    /**
     * Associates a new double value with $key under $group_name. If $key cannot be found then it
     * is created.
     */
    public function set_double(string $group_name, string $key, float $value): void {}

    /**
     * Associates a new integer value with $key under $group_name. If $key cannot be found then it
     * is created.
     */
    public function set_int64(string $group_name, string $key, int $value): void {}

    /**
     * Associates a new integer value with $key under $group_name. If $key cannot be found then it
     * is created.
     */
    public function set_integer(string $group_name, string $key, int $value): void {}

    /**
     * Sets the character which is used to separate values in lists. Typically ';' or ',' are used
     * as separators. The default list separator is ';'.
     */
    public function set_list_separator(int $separator): void {}

    /**
     * Associates a string value for $key and $locale under $group_name. If the translation for
     * $key cannot be found then it is created.
     */
    public function set_locale_string(string $group_name, string $key, string $locale, string $string): void {}

    /**
     * Associates a new string value with $key under $group_name. If $key cannot be found then it
     * is created. If $group_name cannot be found then it is created. Unlike
     * g_key_file_set_value(), this function handles characters that need escaping, such as
     * newlines.
     */
    public function set_string(string $group_name, string $key, string $string): void {}

    /**
     * Associates a new integer value with $key under $group_name. If $key cannot be found then it
     * is created.
     */
    public function set_uint64(string $group_name, string $key, int $value): void {}

    /** Associates a new value with $key under $group_name. */
    public function set_value(string $group_name, string $key, string $value): void {}

    /** This function outputs $key_file as a string. */
    public function to_data(): string {}

    public static function error_quark(): int {}
}

/**
 * A `GTimeZone` represents a time zone, at no particular point in time.
 * @not-serializable
 */
final class GTimeZone
{
    /** GTimeZone values come from GTK, never from `new`. */
    private function __construct() {}

    /**
     * Creates a #GTimeZone corresponding to $identifier. If $identifier cannot be parsed or
     * loaded, `null` is returned.
     */
    public static function new_identifier(?string $identifier = null): GTimeZone {}

    /**
     * Creates a #GTimeZone corresponding to local time. The local time zone may change between
     * invocations to this function; for example, if the system administrator changes it.
     */
    public static function new_local(): GTimeZone {}

    /** Creates a #GTimeZone corresponding to the given constant offset from UTC, in seconds. */
    public static function new_offset(int $seconds): GTimeZone {}

    /** Creates a #GTimeZone corresponding to UTC. */
    public static function new_utc(): GTimeZone {}

    /**
     * Finds an interval within $tz that corresponds to the given $time_. The meaning of $time_
     * depends on $type.
     */
    public function find_interval(int $type, int $time): int {}

    /**
     * Determines the time zone abbreviation to be used during a particular $interval of time in
     * the time zone $tz.
     */
    public function get_abbreviation(int $interval): string {}

    /**
     * Get the identifier of this #GTimeZone, as passed to g_time_zone_new(). If the identifier
     * passed at construction time was not recognised, `UTC` will be returned. If it was `null`,
     * the identifier of the local timezone at construction time will be returned.
     */
    public function get_identifier(): string {}

    /**
     * Determines the offset to UTC in effect during a particular $interval of time in the time
     * zone $tz.
     */
    public function get_offset(int $interval): int {}

    /**
     * Determines if daylight savings time is in effect during a particular $interval of time in
     * the time zone $tz.
     */
    public function is_dst(int $interval): bool {}
}
