<?php

/**
 * GENERATED by gen/gir.php from Gdk GIR - do not edit; edit gen/overrides, gen/skip.txt
 * or gen/allowlist.txt and regenerate (./ci.sh --only=gen --fix).
 *
 * @generate-class-entries
 * @generate-legacy-arginfo 80400
 */

namespace Gtk4;

/**
 * `GdkDisplay` objects are the GDK representation of a workstation.
 *
 * @property-read ?bool $composited
 * @property-read ?bool $input_shapes
 * @property-read ?bool $rgba
 * @property-read ?bool $shadow_width
 */
class GdkDisplay extends GObject
{
    /** GdkDisplay has no constructor in GTK: instances come from GTK, never from `new`. */
    private function __construct() {}

    /** Gets the default `GdkDisplay`. */
    public static function get_default(): ?GdkDisplay {}

    /** Opens a display. */
    public static function open(?string $display_name = null): ?GdkDisplay {}

    /** Emits a short beep on $display */
    public function beep(): void {}

    /** Closes the connection to the windowing system for the given display. */
    public function close(): void {}

    /** Flushes any requests queued for the windowing system. */
    public function flush(): void {}

    /** Gets the list of monitors associated with this display. */
    public function get_monitors(): GListModel {}

    /** Gets the name of the display. */
    public function get_name(): string {}

    /** Finds out if the display has been closed. */
    public function is_closed(): bool {}

    /**
     * Returns whether surfaces can reasonably be expected to have their alpha channel drawn
     * correctly on the screen.
     */
    public function is_composited(): bool {}

    /** Returns whether surfaces on this $display are created with an alpha channel. */
    public function is_rgba(): bool {}

    /**
     * Checks that OpenGL is available for $self and ensures that it is properly initialized. When
     * this fails, an $error will be set describing the error and this function returns `false`.
     */
    public function prepare_gl(): bool {}

    /** Returns `true` if the display supports input shapes. */
    public function supports_input_shapes(): bool {}

    /** Returns whether it's possible for a surface to draw outside of the window area. */
    public function supports_shadow_width(): bool {}

    /**
     * Flushes any requests queued for the windowing system and waits until all requests have been
     * handled.
     */
    public function sync(): void {}
}

/**
 * `GdkMemoryFormat` describes formats that image data can have in memory.
 */
enum GdkMemoryFormat: int
{
    case B8g8r8a8Premultiplied = 0;
    case A8r8g8b8Premultiplied = 1;
    case R8g8b8a8Premultiplied = 2;
    case B8g8r8a8 = 3;
    case A8r8g8b8 = 4;
    case R8g8b8a8 = 5;
    case A8b8g8r8 = 6;
    case R8g8b8 = 7;
    case B8g8r8 = 8;
    case R16g16b16 = 9;
    case R16g16b16a16Premultiplied = 10;
    case R16g16b16a16 = 11;
    case R16g16b16Float = 12;
    case R16g16b16a16FloatPremultiplied = 13;
    case R16g16b16a16Float = 14;
    case R32g32b32Float = 15;
    case R32g32b32a32FloatPremultiplied = 16;
    case R32g32b32a32Float = 17;
    case G8a8Premultiplied = 18;
    case G8a8 = 19;
    case G8 = 20;
    case G16a16Premultiplied = 21;
    case G16a16 = 22;
    case G16 = 23;
    case A8 = 24;
    case A16 = 25;
    case A16Float = 26;
    case A32Float = 27;
    case A8b8g8r8Premultiplied = 28;
    case B8g8r8x8 = 29;
    case X8r8g8b8 = 30;
    case R8g8b8x8 = 31;
    case X8b8g8r8 = 32;
    case NFormats = 33;
}

/**
 * Flags to indicate the state of modifier keys and mouse buttons in events.
 */
final class GdkModifierType
{
    public const int NO_MODIFIER_MASK = 0;
    public const int SHIFT_MASK = 1;
    public const int LOCK_MASK = 2;
    public const int CONTROL_MASK = 4;
    public const int ALT_MASK = 8;
    public const int BUTTON1_MASK = 256;
    public const int BUTTON2_MASK = 512;
    public const int BUTTON3_MASK = 1024;
    public const int BUTTON4_MASK = 2048;
    public const int BUTTON5_MASK = 4096;
    public const int SUPER_MASK = 67108864;
    public const int HYPER_MASK = 134217728;
    public const int META_MASK = 268435456;
}

/**
 * `GdkTexture` is the basic element used to refer to pixel data.
 *
 * @property ?int $height
 * @property ?int $width
 */
class GdkTexture extends GObject
{
    /** GdkTexture is abstract in GTK: instances come from GTK, never from `new`. */
    private function __construct() {}

    /** Creates a new texture by loading an image from memory, */
    public static function new_from_bytes(string $bytes): GdkTexture {}

    /** Creates a new texture by loading an image from a file. */
    public static function new_from_filename(string $path): GdkTexture {}

    /** Gets the memory format most closely associated with the data of the texture. */
    public function get_format(): GdkMemoryFormat {}

    /** Returns the height of the $texture, in pixels. */
    public function get_height(): int {}

    /** Returns the width of $texture, in pixels. */
    public function get_width(): int {}

    /** Store the given $texture to the $filename as a PNG file. */
    public function save_to_png(string $filename): bool {}

    /** Store the given $texture in memory as a PNG file. */
    public function save_to_png_bytes(): string {}

    /** Store the given $texture to the $filename as a TIFF file. */
    public function save_to_tiff(string $filename): bool {}

    /** Store the given $texture in memory as a TIFF file. */
    public function save_to_tiff_bytes(): string {}
}
