// GENERATED by gen/gir.php from Gdk.Cursor - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GdkCursor
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GdkCursor::__construct()
 *
 * A GdkCursor with default properties (GTK's own constructor is varargs-only; set the
 * properties afterwards).
 */
ZEND_METHOD(Gtk4_GdkCursor, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = static_cast<GObject *>(g_object_new(GDK_TYPE_CURSOR, nullptr));
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * static Gtk4\GdkCursor::new_from_name(string $name, ?GdkCursor $fallback = null): GdkCursor
 *
 * Creates a new cursor by looking up $name in the current cursor theme.
 */
ZEND_METHOD(Gtk4_GdkCursor, new_from_name) {
  zend_string *name;
  zval *fallback = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 2)
  Z_PARAM_STR(name)
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(fallback, class_for_gtype(GDK_TYPE_CURSOR))
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  GObject *fallback_o = nullptr;
  if (fallback != nullptr) {
    fallback_o = unwrap(fallback, GDK_TYPE_CURSOR);
    if (fallback_o == nullptr) RETURN_THROWS();
  }
  GObject *obj = G_OBJECT(gdk_cursor_new_from_name(
      ZSTR_VAL(name), fallback_o != nullptr ? GDK_CURSOR(fallback_o) : nullptr));
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

/**
 * static Gtk4\GdkCursor::new_from_texture(GdkTexture $texture, int $hotspot_x, int $hotspot_y,
 * ?GdkCursor $fallback = null): GdkCursor
 *
 * Creates a new cursor from a `GdkTexture`.
 */
ZEND_METHOD(Gtk4_GdkCursor, new_from_texture) {
  zval *texture;
  zend_long hotspot_x;
  zend_long hotspot_y;
  zval *fallback = nullptr;
  ZEND_PARSE_PARAMETERS_START(3, 4)
  Z_PARAM_OBJECT_OF_CLASS(texture, class_for_gtype(GDK_TYPE_TEXTURE))
  Z_PARAM_LONG(hotspot_x)
  Z_PARAM_LONG(hotspot_y)
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(fallback, class_for_gtype(GDK_TYPE_CURSOR))
  ZEND_PARSE_PARAMETERS_END();
  GObject *texture_o = unwrap(texture, GDK_TYPE_TEXTURE);
  if (texture_o == nullptr) RETURN_THROWS();
  if (!phpgtk::check_range<int>(hotspot_x, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(hotspot_y, 3)) RETURN_THROWS();
  GObject *fallback_o = nullptr;
  if (fallback != nullptr) {
    fallback_o = unwrap(fallback, GDK_TYPE_CURSOR);
    if (fallback_o == nullptr) RETURN_THROWS();
  }
  GObject *obj = G_OBJECT(gdk_cursor_new_from_texture(
      GDK_TEXTURE(texture_o), static_cast<int>(hotspot_x), static_cast<int>(hotspot_y),
      fallback_o != nullptr ? GDK_CURSOR(fallback_o) : nullptr));
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

/**
 * Gtk4\GdkCursor::get_fallback(): ?GdkCursor
 *
 * Returns the fallback for this $cursor.
 */
ZEND_METHOD(Gtk4_GdkCursor, get_fallback) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkCursor *self = PHPGTK_SELF(GdkCursor, GDK_TYPE_CURSOR);
  GdkCursor *phpgtk_ret = gdk_cursor_get_fallback(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkCursor::get_hotspot_x(): int
 *
 * Returns the horizontal offset of the hotspot.
 */
ZEND_METHOD(Gtk4_GdkCursor, get_hotspot_x) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkCursor *self = PHPGTK_SELF(GdkCursor, GDK_TYPE_CURSOR);
  RETURN_LONG(static_cast<zend_long>(gdk_cursor_get_hotspot_x(self)));
}

/**
 * Gtk4\GdkCursor::get_hotspot_y(): int
 *
 * Returns the vertical offset of the hotspot.
 */
ZEND_METHOD(Gtk4_GdkCursor, get_hotspot_y) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkCursor *self = PHPGTK_SELF(GdkCursor, GDK_TYPE_CURSOR);
  RETURN_LONG(static_cast<zend_long>(gdk_cursor_get_hotspot_y(self)));
}

/**
 * Gtk4\GdkCursor::get_name(): ?string
 *
 * Returns the name of the cursor.
 */
ZEND_METHOD(Gtk4_GdkCursor, get_name) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkCursor *self = PHPGTK_SELF(GdkCursor, GDK_TYPE_CURSOR);
  PHPGTK_RETURN_STRING_OR_NULL(gdk_cursor_get_name(self));
}

/**
 * Gtk4\GdkCursor::get_texture(): ?GdkTexture
 *
 * Returns the texture for the cursor.
 */
ZEND_METHOD(Gtk4_GdkCursor, get_texture) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkCursor *self = PHPGTK_SELF(GdkCursor, GDK_TYPE_CURSOR);
  GdkTexture *phpgtk_ret = gdk_cursor_get_texture(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}
