// GENERATED by gen/gir.php from Gdk.ContentFormats - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GdkContentFormats (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

// GIR's C arrays of MIME types and its GType parameters, as PHP lists and type names
// (core/marshal, gtype_from_php_name / php_name_for_gtype).
#include "core/marshal.h"

#include <vector>

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\GdkContentFormats::contain_mime_type(string $mime_type): bool
 *
 * Checks if a given mime type is part of the given $formats.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, contain_mime_type) {
  zend_string *mime_type;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(mime_type)
  ZEND_PARSE_PARAMETERS_END();
  GdkContentFormats *self = PHPGTK_BOXED_SELF(GdkContentFormats);
  if (!phpgtk::check_utf8(mime_type, 1)) RETURN_THROWS();
  RETURN_BOOL(gdk_content_formats_contain_mime_type(self, ZSTR_VAL(mime_type)));
}

/**
 * Gtk4\GdkContentFormats::match(GdkContentFormats $second): bool
 *
 * Checks if $first and $second have any matching formats.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, match) {
  zval *second;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(second, boxed_class_for_type(GDK_TYPE_CONTENT_FORMATS)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GdkContentFormats *self = PHPGTK_BOXED_SELF(GdkContentFormats);
  gpointer second_b = unwrap_boxed(second, GDK_TYPE_CONTENT_FORMATS);
  if (second_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(gdk_content_formats_match(self, static_cast<GdkContentFormats *>(second_b)));
}

/**
 * Gtk4\GdkContentFormats::match_mime_type(GdkContentFormats $second): ?string
 *
 * Finds the first mime type from $first that is also contained in $second.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, match_mime_type) {
  zval *second;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(second, boxed_class_for_type(GDK_TYPE_CONTENT_FORMATS)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GdkContentFormats *self = PHPGTK_BOXED_SELF(GdkContentFormats);
  gpointer second_b = unwrap_boxed(second, GDK_TYPE_CONTENT_FORMATS);
  if (second_b == nullptr) RETURN_THROWS();
  PHPGTK_RETURN_STRING_OR_NULL(
      gdk_content_formats_match_mime_type(self, static_cast<GdkContentFormats *>(second_b)));
}

/**
 * Gtk4\GdkContentFormats::to_string(): string
 *
 * Prints the given $formats into a human-readable string.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, to_string) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkContentFormats *self = PHPGTK_BOXED_SELF(GdkContentFormats);
  char *phpgtk_ret = gdk_content_formats_to_string(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GdkContentFormats::union(GdkContentFormats $second): GdkContentFormats
 *
 * Append all missing types from $second to $first, in the order they had in $second.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, union) {
  zval *second;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(second, boxed_class_for_type(GDK_TYPE_CONTENT_FORMATS)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GdkContentFormats *owned = PHPGTK_BOXED_SELF(GdkContentFormats);
  auto *self = static_cast<GdkContentFormats *>(
      g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, owned));  // the call takes ownership of it
  gpointer second_b = unwrap_boxed(second, GDK_TYPE_CONTENT_FORMATS);
  if (second_b == nullptr) RETURN_THROWS();
  GdkContentFormats *phpgtk_ret =
      gdk_content_formats_union(self, static_cast<GdkContentFormats *>(second_b));
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * Gtk4\GdkContentFormats::union_deserialize_gtypes(): GdkContentFormats
 *
 * Add GTypes for mime types in $formats for which deserializers are registered.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, union_deserialize_gtypes) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkContentFormats *owned = PHPGTK_BOXED_SELF(GdkContentFormats);
  auto *self = static_cast<GdkContentFormats *>(
      g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, owned));  // the call takes ownership of it
  GdkContentFormats *phpgtk_ret = gdk_content_formats_union_deserialize_gtypes(self);
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * Gtk4\GdkContentFormats::union_deserialize_mime_types(): GdkContentFormats
 *
 * Add mime types for GTypes in $formats for which deserializers are registered.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, union_deserialize_mime_types) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkContentFormats *owned = PHPGTK_BOXED_SELF(GdkContentFormats);
  auto *self = static_cast<GdkContentFormats *>(
      g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, owned));  // the call takes ownership of it
  GdkContentFormats *phpgtk_ret = gdk_content_formats_union_deserialize_mime_types(self);
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * Gtk4\GdkContentFormats::union_serialize_gtypes(): GdkContentFormats
 *
 * Add GTypes for the mime types in $formats for which serializers are registered.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, union_serialize_gtypes) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkContentFormats *owned = PHPGTK_BOXED_SELF(GdkContentFormats);
  auto *self = static_cast<GdkContentFormats *>(
      g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, owned));  // the call takes ownership of it
  GdkContentFormats *phpgtk_ret = gdk_content_formats_union_serialize_gtypes(self);
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * Gtk4\GdkContentFormats::union_serialize_mime_types(): GdkContentFormats
 *
 * Add mime types for GTypes in $formats for which serializers are registered.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, union_serialize_mime_types) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkContentFormats *owned = PHPGTK_BOXED_SELF(GdkContentFormats);
  auto *self = static_cast<GdkContentFormats *>(
      g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, owned));  // the call takes ownership of it
  GdkContentFormats *phpgtk_ret = gdk_content_formats_union_serialize_mime_types(self);
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * static Gtk4\GdkContentFormats::parse(string $string): ?GdkContentFormats
 *
 * Parses the given $string into `GdkContentFormats` and returns the formats.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, parse) {
  zend_string *string;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(string)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_utf8(string, 1)) RETURN_THROWS();
  GdkContentFormats *phpgtk_ret = gdk_content_formats_parse(ZSTR_VAL(string));
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GDK_TYPE_CONTENT_FORMATS, phpgtk_ret);
}

/**
 * public function __construct(array $mime_types = [])
 * The set of MIME types a drag or a clipboard offers.
 *
 * GIR's constructor takes a C array; a PHP list of strings is the same thing. An empty set is
 * what GTK's own `gdk_content_formats_new(NULL, 0)` builds, and union_*() grows it.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, __construct) {
  HashTable *mime_types = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_ARRAY_HT(mime_types)
  ZEND_PARSE_PARAMETERS_END();

  std::vector<const char *> types;
  if (mime_types != nullptr) {
    types.reserve(zend_hash_num_elements(mime_types));
    zval *entry = nullptr;
    // NOLINTNEXTLINE(readability-math-missing-parentheses) Zend macro expansion
    ZEND_HASH_FOREACH_VAL(mime_types, entry) {
      if (Z_TYPE_P(entry) != IS_STRING) {
        zend_argument_type_error(1, "must be a list of MIME type strings");
        RETURN_THROWS();
      }
      if (!check_utf8(Z_STR_P(entry), 1)) RETURN_THROWS();
      types.push_back(Z_STRVAL_P(entry));
    }
    ZEND_HASH_FOREACH_END();
  }
  gpointer obj = gdk_content_formats_new(types.empty() ? nullptr : types.data(),
                                         static_cast<guint>(types.size()));
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the value (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  boxed_adopt(boxed_from_zval(ZEND_THIS), GDK_TYPE_CONTENT_FORMATS, obj);
}

/**
 * public function contain_gtype(string $type): bool
 * Whether this set offers $type, named as elsewhere.
 */
ZEND_METHOD(Gtk4_GdkContentFormats, contain_gtype) {
  zend_string *type;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(type)
  ZEND_PARSE_PARAMETERS_END();
  auto *self = static_cast<GdkContentFormats *>(boxed_from_zval(ZEND_THIS)->data);
  const GType t = gtype_from_php_name(type, 1);
  if (t == 0) RETURN_THROWS();
  RETURN_BOOL(gdk_content_formats_contain_gtype(self, t));
}

/**
 * public function get_gtypes(): array
 * The types in this set, named as elsewhere ("string", a registered class name).
 *
 * @return list<string>
 */
ZEND_METHOD(Gtk4_GdkContentFormats, get_gtypes) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GdkContentFormats *>(boxed_from_zval(ZEND_THIS)->data);
  gsize count = 0;
  const GType *types = gdk_content_formats_get_gtypes(self, &count);
  array_init_size(return_value, static_cast<uint32_t>(count));
  for (gsize i = 0; types != nullptr && i < count; i++) {
    add_next_index_str(return_value, php_name_for_gtype(types[i]));
  }
}

/**
 * public function get_mime_types(): array
 * The MIME types in this set.
 *
 * @return list<string>
 */
ZEND_METHOD(Gtk4_GdkContentFormats, get_mime_types) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GdkContentFormats *>(boxed_from_zval(ZEND_THIS)->data);
  gsize count = 0;
  const char *const *types = gdk_content_formats_get_mime_types(self, &count);
  array_init_size(return_value, static_cast<uint32_t>(count));
  for (gsize i = 0; types != nullptr && i < count; i++) {
    add_next_index_string(return_value, types[i]);
  }
}

namespace phpgtk {
// MINIT: bind the PHP class to GDK_TYPE_CONTENT_FORMATS with its field table.
void register_GdkContentFormats(zend_class_entry *ce) {
  register_boxed(BoxedClass{
      .type = GDK_TYPE_CONTENT_FORMATS, .ce = ce, .fields = fields, .read = read, .write = write});
}
}  // namespace phpgtk
