// GENERATED by gen/gir.php from Gdk.Display - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GdkDisplay
#include "php_gtk4.h"
#include "core/object.h"
#include "core/collections.h"
#include "core/gerror.h"

using namespace phpgtk;

/**
 * Gtk4\GdkDisplay::__construct()
 *
 * GdkDisplay has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_GdkDisplay, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * static Gtk4\GdkDisplay::get_default(): ?GdkDisplay
 *
 * Gets the default `GdkDisplay`.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_default) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *phpgtk_ret = gdk_display_get_default();
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * static Gtk4\GdkDisplay::open(?string $display_name = null): ?GdkDisplay
 *
 * Opens a display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, open) {
  zend_string *display_name = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_STR_OR_NULL(display_name)
  ZEND_PARSE_PARAMETERS_END();
  if (display_name != nullptr && !phpgtk::check_utf8(display_name, 1)) RETURN_THROWS();
  GdkDisplay *phpgtk_ret =
      gdk_display_open(display_name != nullptr ? ZSTR_VAL(display_name) : nullptr);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::beep(): void
 *
 * Emits a short beep on $display
 */
ZEND_METHOD(Gtk4_GdkDisplay, beep) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  gdk_display_beep(self);
}

/**
 * Gtk4\GdkDisplay::close(): void
 *
 * Closes the connection to the windowing system for the given display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, close) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  gdk_display_close(self);
}

/**
 * Gtk4\GdkDisplay::device_is_grabbed(GdkDevice $device): bool
 *
 * Returns `true` if there is an ongoing grab on $device for $display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, device_is_grabbed) {
  zval *device;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(device, class_for_gtype(GDK_TYPE_DEVICE))
  ZEND_PARSE_PARAMETERS_END();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GObject *device_o = unwrap(device, GDK_TYPE_DEVICE);
  if (device_o == nullptr) RETURN_THROWS();
  RETURN_BOOL(gdk_display_device_is_grabbed(self, GDK_DEVICE(device_o)));
}

/**
 * Gtk4\GdkDisplay::flush(): void
 *
 * Flushes any requests queued for the windowing system.
 */
ZEND_METHOD(Gtk4_GdkDisplay, flush) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  gdk_display_flush(self);
}

/**
 * Gtk4\GdkDisplay::get_clipboard(): GdkClipboard
 *
 * Gets the clipboard used for copy/paste operations.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_clipboard) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GdkClipboard *phpgtk_ret = gdk_display_get_clipboard(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::get_default_seat(): ?GdkSeat
 *
 * Returns the default `GdkSeat` for this display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_default_seat) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GdkSeat *phpgtk_ret = gdk_display_get_default_seat(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::get_monitor_at_surface(GdkSurface $surface): ?GdkMonitor
 *
 * Gets the monitor in which the largest area of $surface resides.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_monitor_at_surface) {
  zval *surface;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(surface, class_for_gtype(GDK_TYPE_SURFACE))
  ZEND_PARSE_PARAMETERS_END();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GObject *surface_o = unwrap(surface, GDK_TYPE_SURFACE);
  if (surface_o == nullptr) RETURN_THROWS();
  GdkMonitor *phpgtk_ret = gdk_display_get_monitor_at_surface(self, GDK_SURFACE(surface_o));
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::get_monitors(): GListModel
 *
 * Gets the list of monitors associated with this display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_monitors) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GListModel *phpgtk_ret = gdk_display_get_monitors(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::get_name(): string
 *
 * Gets the name of the display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_name) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  const char *phpgtk_ret = gdk_display_get_name(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\GdkDisplay::get_primary_clipboard(): GdkClipboard
 *
 * Gets the clipboard used for the primary selection.
 */
ZEND_METHOD(Gtk4_GdkDisplay, get_primary_clipboard) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GdkClipboard *phpgtk_ret = gdk_display_get_primary_clipboard(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkDisplay::is_closed(): bool
 *
 * Finds out if the display has been closed.
 */
ZEND_METHOD(Gtk4_GdkDisplay, is_closed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  RETURN_BOOL(gdk_display_is_closed(self));
}

/**
 * Gtk4\GdkDisplay::is_composited(): bool
 *
 * Returns whether surfaces can reasonably be expected to have their alpha channel drawn correctly
 * on the screen.
 */
ZEND_METHOD(Gtk4_GdkDisplay, is_composited) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  RETURN_BOOL(gdk_display_is_composited(self));
}

/**
 * Gtk4\GdkDisplay::is_rgba(): bool
 *
 * Returns whether surfaces on this $display are created with an alpha channel.
 */
ZEND_METHOD(Gtk4_GdkDisplay, is_rgba) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  RETURN_BOOL(gdk_display_is_rgba(self));
}

/**
 * Gtk4\GdkDisplay::list_seats(): array
 *
 * Returns the list of seats known to $display.
 */
ZEND_METHOD(Gtk4_GdkDisplay, list_seats) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  glist_to_php(gdk_display_list_seats(self), GDK_TYPE_SEAT, Transfer::Container, return_value);
}

/**
 * Gtk4\GdkDisplay::prepare_gl(): bool
 *
 * Checks that OpenGL is available for $self and ensures that it is properly initialized. When this
 * fails, an $error will be set describing the error and this function returns `false`.
 */
ZEND_METHOD(Gtk4_GdkDisplay, prepare_gl) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  GError *error = nullptr;
  const gboolean ok = gdk_display_prepare_gl(self, &error);
  if (!ok) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GdkDisplay::supports_input_shapes(): bool
 *
 * Returns `true` if the display supports input shapes.
 */
ZEND_METHOD(Gtk4_GdkDisplay, supports_input_shapes) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  RETURN_BOOL(gdk_display_supports_input_shapes(self));
}

/**
 * Gtk4\GdkDisplay::supports_shadow_width(): bool
 *
 * Returns whether it's possible for a surface to draw outside of the window area.
 */
ZEND_METHOD(Gtk4_GdkDisplay, supports_shadow_width) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  RETURN_BOOL(gdk_display_supports_shadow_width(self));
}

/**
 * Gtk4\GdkDisplay::sync(): void
 *
 * Flushes any requests queued for the windowing system and waits until all requests have been
 * handled.
 */
ZEND_METHOD(Gtk4_GdkDisplay, sync) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  gdk_display_sync(self);
}

/**
 * Gtk4\GdkDisplay::translate_key(int $keycode, int $state, int $group): ?array
 *
 * Translates the contents of a `GdkEventKey` into a keyval, effective group, and level.
 */
ZEND_METHOD(Gtk4_GdkDisplay, translate_key) {
  zend_long keycode;
  zend_long state;
  zend_long group;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_LONG(keycode)
  Z_PARAM_LONG(state)
  Z_PARAM_LONG(group)
  ZEND_PARSE_PARAMETERS_END();
  GdkDisplay *self = PHPGTK_SELF(GdkDisplay, GDK_TYPE_DISPLAY);
  if (!phpgtk::check_range<guint>(keycode, 1)) RETURN_THROWS();
  if (!phpgtk::check_flags(GDK_TYPE_MODIFIER_TYPE, state, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(group, 3)) RETURN_THROWS();
  guint keyval = 0;
  int effective_group = 0;
  int level = 0;
  GdkModifierType consumed = static_cast<GdkModifierType>(0);
  if (!gdk_display_translate_key(self, static_cast<guint>(keycode),
                                 static_cast<GdkModifierType>(state), static_cast<int>(group),
                                 &keyval, &effective_group, &level, &consumed))
    RETURN_NULL();
  array_init_size(return_value, 4);
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(keyval));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(effective_group));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(level));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(consumed));
    add_next_index_zval(return_value, &item);
  }
}
