// GENERATED by gen/gir.php from Gdk.Monitor - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GdkMonitor
#include "php_gtk4.h"
#include "core/object.h"
#include "core/enums.h"
#include "core/boxed.h"

using namespace phpgtk;

/**
 * Gtk4\GdkMonitor::__construct()
 *
 * GdkMonitor has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_GdkMonitor, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\GdkMonitor::get_connector(): ?string
 *
 * Gets the name of the monitor's connector, if available.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_connector) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  PHPGTK_RETURN_STRING_OR_NULL(gdk_monitor_get_connector(self));
}

/**
 * Gtk4\GdkMonitor::get_description(): ?string
 *
 * Gets a string describing the monitor, if available.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_description) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  PHPGTK_RETURN_STRING_OR_NULL(gdk_monitor_get_description(self));
}

/**
 * Gtk4\GdkMonitor::get_display(): GdkDisplay
 *
 * Gets the display that this monitor belongs to.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_display) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  GdkDisplay *phpgtk_ret = gdk_monitor_get_display(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkMonitor::get_geometry(): GdkRectangle
 *
 * Retrieves the size and position of the monitor within the display coordinate space.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_geometry) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  GdkRectangle geometry{};
  gdk_monitor_get_geometry(self, &geometry);
  wrap_boxed(GDK_TYPE_RECTANGLE, &geometry, return_value);
}

/**
 * Gtk4\GdkMonitor::get_height_mm(): int
 *
 * Gets the height in millimeters of the monitor.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_height_mm) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_LONG(static_cast<zend_long>(gdk_monitor_get_height_mm(self)));
}

/**
 * Gtk4\GdkMonitor::get_manufacturer(): ?string
 *
 * Gets the name or PNP ID of the monitor's manufacturer.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_manufacturer) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  PHPGTK_RETURN_STRING_OR_NULL(gdk_monitor_get_manufacturer(self));
}

/**
 * Gtk4\GdkMonitor::get_model(): ?string
 *
 * Gets the string identifying the monitor model, if available.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_model) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  PHPGTK_RETURN_STRING_OR_NULL(gdk_monitor_get_model(self));
}

/**
 * Gtk4\GdkMonitor::get_refresh_rate(): int
 *
 * Gets the refresh rate of the monitor, if available.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_refresh_rate) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_LONG(static_cast<zend_long>(gdk_monitor_get_refresh_rate(self)));
}

/**
 * Gtk4\GdkMonitor::get_scale(): float
 *
 * Gets the internal scale factor that maps from monitor coordinates to device pixels.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_scale) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_DOUBLE(gdk_monitor_get_scale(self));
}

/**
 * Gtk4\GdkMonitor::get_scale_factor(): int
 *
 * Gets the internal scale factor that maps from monitor coordinates to device pixels.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_scale_factor) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_LONG(static_cast<zend_long>(gdk_monitor_get_scale_factor(self)));
}

/**
 * Gtk4\GdkMonitor::get_subpixel_layout(): GdkSubpixelLayout
 *
 * Gets information about the layout of red, green and blue primaries for pixels.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_subpixel_layout) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  enum_to_php(GDK_TYPE_SUBPIXEL_LAYOUT, gdk_monitor_get_subpixel_layout(self), return_value);
}

/**
 * Gtk4\GdkMonitor::get_width_mm(): int
 *
 * Gets the width in millimeters of the monitor.
 */
ZEND_METHOD(Gtk4_GdkMonitor, get_width_mm) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_LONG(static_cast<zend_long>(gdk_monitor_get_width_mm(self)));
}

/**
 * Gtk4\GdkMonitor::is_valid(): bool
 *
 * Returns `true` if the $monitor object corresponds to a physical monitor.
 */
ZEND_METHOD(Gtk4_GdkMonitor, is_valid) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkMonitor *self = PHPGTK_SELF(GdkMonitor, GDK_TYPE_MONITOR);
  RETURN_BOOL(gdk_monitor_is_valid(self));
}
