# overtrue/phplint - syntax check. ci.sh passes -j $(nproc).
path:
  - tests
  - examples
  - stubs
  - gen
  - bin
exclude:
  - vendor
  - gen/PHP-Parser-5.0.0
extensions:
  - php
warning: true
cache: .phplint.cache
