#!/usr/bin/env bash
#
# The one QA entry point - same stages as the GitHub workflows (.github/workflows/*.yml):
#
#   version    ./VERSION is the single source of truth; src/php_gtk4.h and src/gtk4.stub.php mirror it
#   stubs      src/gtk4.stub.php -> gen_stub.php (src/gtk4_arginfo.h) + gen/ide-stub.php (stubs/gtk4.php) are current,
#              every C++ function has a comment block (ZEND_METHOD blocks generated by gen/method-comments.php)
#   cpp-lint   clang-format --dry-run + clang-tidy over src/**
#   md-lint    markdownlint-cli2 over **/*.md (.markdownlint-cli2.jsonc)
#   php-qa     phplint -> phpcs -> php-cs-fixer -> phpstan (max)   [tests/ examples/ stubs/ gen/]
#              the two formatters check, or fix with --fix (phpcbf / php-cs-fixer fix) - never both
#   build      phpize + configure + make -> ./gtk4.so
#   load       php -n -dextension=./gtk4.so smoke check
#   test       PHPUnit under xvfb-run via bin/php-gtk4 (gtk3 filtered out)
#   phpt       php-src run-tests.php over tests/phpt (process-level: stderr, fatals, RSHUTDOWN, INI/ENV)
#
# Extra stages, not run by default (opt in with --only=... or --with=...):
#   asan       ASan+UBSan+LSan build (gtk4-asan.so) running tests/scripts/stress.php and the PHPUnit suite
#   coverage   gcov build (gtk4-cov.so), runs the suite + stress script, prints per-file C++ line coverage
#   valgrind   memcheck on the stress script with the normal gtk4.so (uninitialised reads, definite leaks)
#
# Usage:
#   ./ci.sh                          all stages, in that order
#   ./ci.sh --fix                    lint stages fix instead of reporting (clang-tidy/-format, phpcbf, php-cs-fixer, stubs)
#   ./ci.sh --only=test              one stage   (--only=cpp-lint,php-qa for several)
#   ./ci.sh --only=phpt              just the run-tests.php suite (TESTS=tests/phpt/x.phpt for one file)
#   ./ci.sh --skip=cpp-lint,php-qa   fastest edit-build-test loop
#   ./ci.sh --filter SignalTest      common phpunit options pass through; anything else after --
#   ./ci.sh --help                   this text
#   ./ci.sh --no-stan                php-qa without phpstan
#   ./ci.sh --fail-fast              clang-tidy stops at the first failing file
#   ./ci.sh --with=asan,coverage,valgrind   default stages plus the extra ones
#   ./ci.sh --only=asan              just the sanitizer run
#   ./ci.sh --skip=tidy | --skip=format | --skip=stan | --skip=style   sub-steps of cpp-lint / php-qa
#                                    (style = phplint + phpcs + php-cs-fixer, what the pre-commit hook already ran)
#   ./ci.sh --only=md-lint --fix     markdownlint over the docs, applying the fixable rules
#   ./ci.sh --only=version --fix     rewrite the version mirrors from ./VERSION (then --only=stubs --fix)
#   COVERAGE_MIN_LINES=80 ./ci.sh --only=coverage   fail below this line coverage (default 80)
#
# Env: PHP=php8.4 PHP_CONFIG=/usr/bin/php-config8.4 PHPIZE=phpize8.4
#      JOBS=$(nproc) CLANG_TIDY=clang-tidy-20 CLANG_FORMAT=clang-format-20 (default: newest installed)
#      COMPOSER=/usr/local/bin/composer
set -euo pipefail
cd "$(dirname "$0")"

PHP=${PHP:-php8.4}
PHP_CONFIG=${PHP_CONFIG:-/usr/bin/php-config8.4}
PHPIZE=${PHPIZE:-$(dirname "$PHP_CONFIG")/phpize$(basename "$PHP_CONFIG" | sed 's/php-config//')}
JOBS=${JOBS:-$(nproc)}
COMPOSER=${COMPOSER:-/usr/local/bin/composer}
# What the phpt stage hands to run-tests.php; narrow it to one file while iterating.
PHPT_TESTS=${PHPT_TESTS:-tests/phpt}
# Newest installed clang-tidy-N / clang-format-N (Debian naming), else the unversioned
# name from PATH, unless overridden.
newest_tool() {
    local versioned
    versioned=$(ls /usr/bin/"$1"-[0-9]* 2>/dev/null | sort -t- -k2 -V | tail -1)
    if [[ -n "$versioned" ]]; then basename "$versioned"; else echo "$1"; fi
}
CLANG_TIDY=${CLANG_TIDY:-$(newest_tool clang-tidy)}
CLANG_FORMAT=${CLANG_FORMAT:-$(newest_tool clang-format)}

ALL_STAGES="version stubs cpp-lint md-lint php-qa build load test phpt asan coverage valgrind"
DEFAULT_OFF="asan coverage valgrind"
ONLY=""; SKIP=""; WITH=""; FIX=0; STAN=1; FAIL_FAST=0; PHPUNIT_ARGS=()
usage() { sed -n '2,/^set -/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; }
PASSTHRU=0
for arg in "$@"; do
    if [[ $PASSTHRU -eq 1 ]]; then PHPUNIT_ARGS+=("$arg"); continue; fi
    case "$arg" in
        -h|--help)  usage; exit 0 ;;
        --only=*)   ONLY="${arg#--only=}" ;;
        --skip=*)   SKIP="${arg#--skip=}" ;;
        --with=*)   WITH="${arg#--with=}" ;;
        --fix)      FIX=1 ;;
        --no-stan)  STAN=0 ;;
        --fail-fast) FAIL_FAST=1 ;;
        --)         PASSTHRU=1 ;;   # everything after goes to phpunit verbatim
        --filter|--filter=*|--testsuite|--testsuite=*|--group|--group=*|--exclude-group|--exclude-group=*|--stop-on-failure|--testdox|--debug|--display-*|--no-progress|--order-by=*|--random-order-seed=*)
                    PHPUNIT_ARGS+=("$arg") ;;
        --*)        echo "ci.sh: unknown option '$arg' (see --help; phpunit options go after --)" >&2; exit 2 ;;
        *)          PHPUNIT_ARGS+=("$arg") ;;   # bare values (e.g. the argument of --filter)
    esac
done
for stage in ${ONLY//,/ } ${SKIP//,/ } ${WITH//,/ }; do
    case "$stage" in tidy|format|stan|style) ;; *)
        [[ " $ALL_STAGES " == *" $stage "* ]] || { echo "ci.sh: unknown stage '$stage' (stages: $ALL_STAGES)" >&2; exit 2; } ;;
    esac
done

substep() {  # substep <name>: sub-steps (tidy, format, stan, style) only honour --skip
    [[ ",$SKIP," != *",$1,"* ]]
}

enabled() {  # enabled <stage>
    if [[ -n "$ONLY" ]]; then [[ ",$ONLY," == *",$1,"* ]] || return 1; fi
    [[ ",$SKIP," == *",$1,"* ]] && return 1
    if [[ " $DEFAULT_OFF " == *" $1 "* && -z "$ONLY" ]]; then [[ ",$WITH," == *",$1,"* ]] || return 1; fi
    return 0
}

BLUE='\033[1;34m'; RED='\033[1;31m'; GREEN='\033[1;32m'; NC='\033[0m'
step() { printf "\n${BLUE}=== %s ===${NC}\n" "$*"; }
fail() { printf "${RED}FAILED: %s${NC}\n" "$*" >&2; exit 1; }

# ---------------------------------------------------------------- helpers
# ini scan dir with gtk3/gtk4 removed, for tools that must not load GTK
gtk_free_ini_dir() {
    local scan tmp
    scan=$("$PHP" -n -r 'echo PHP_CONFIG_FILE_SCAN_DIR;')
    tmp=$(mktemp -d)
    if [[ -d "$scan" ]]; then
        for ini in "$scan"/*.ini; do
            [[ -e "$ini" ]] || continue
            grep -qE '^\s*extension\s*=\s*"?(php_)?gtk[34]?(\.so)?"?\s*$' "$ini" && continue
            ln -s "$ini" "$tmp/$(basename "$ini")"
        done
    fi
    echo "$tmp"
}

ensure_vendor() {
    if [[ ! -x vendor/bin/phpunit || ! -x vendor/bin/phpstan ]]; then
        step "composer install"
        "$PHP" "$COMPOSER" install --no-interaction --no-progress --prefer-dist || fail "composer install"
    fi
}

# ---------------------------------------------------------------- version
# ./VERSION (one line, e.g. 0.2.0-dev) is the single source of truth for the
# release version. Everything else mirrors it and is checked here:
#   src/php_gtk4.h    PHP_GTK4_VERSION -> zend_module_entry, phpinfo, phpversion('gtk4')
#   src/gtk4.stub.php const VERSION    -> Gtk4\VERSION (and the generated arginfo/IDE stub)
# config.m4 repeats the header check at configure time, so a hand-edited header
# cannot survive a build either; docs/RELEASING.md explains the -dev suffix.
version_file() { tr -d ' \t\r\n' < VERSION; }

stage_version() {
    step "version: ./VERSION mirrored in src/php_gtk4.h and src/gtk4.stub.php"
    local want; want=$(version_file)
    [[ -n "$want" ]] || fail "VERSION is empty"
    # SemVer, optionally with the -dev development suffix this project uses.
    [[ "$want" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-dev)?$ ]] || fail "VERSION must be X.Y.Z or X.Y.Z-dev, got '$want'"

    if [[ $FIX -eq 1 ]]; then
        sed -i -E "s/^(#define PHP_GTK4_VERSION ).*/\\1\"$want\"/" src/php_gtk4.h
        sed -i -E "s/^(const VERSION = ').*(';)/\\1$want\\2/" src/gtk4.stub.php
    fi

    local header stub
    header=$(sed -nE 's/^#define PHP_GTK4_VERSION "(.*)"$/\1/p' src/php_gtk4.h)
    stub=$(sed -nE "s/^const VERSION = '(.*)';$/\1/p" src/gtk4.stub.php)
    [[ "$header" == "$want" ]] || fail "src/php_gtk4.h says '$header', VERSION says '$want' (run ./ci.sh --only=version --fix)"
    [[ "$stub" == "$want" ]] || fail "src/gtk4.stub.php says '$stub', VERSION says '$want' (run ./ci.sh --only=version --fix)"
    if [[ $FIX -eq 1 ]]; then echo "  mirrors rewritten to $want (run ./ci.sh --only=stubs --fix, commit both)"; fi
    echo "  $want"
}

# ---------------------------------------------------------------- stubs
# src/gtk4.stub.php is the API source of truth. Both derived files are
# committed; this stage regenerates them and fails if they changed.
stage_stubs() {
    ensure_vendor
    step "stubs: gen_stub.php src/gtk4.stub.php -> src/gtk4_arginfo.h, ide-stub.php -> stubs/gtk4.php"
    local before; before=$(md5sum src/gtk4_arginfo.h stubs/gtk4.php 2>/dev/null)
    "$PHP" gen/gen_stub.php src/gtk4.stub.php >/dev/null || fail "gen_stub.php"
    "$PHP" gen/ide-stub.php >/dev/null || fail "ide-stub.php"
    # Comment blocks above every ZEND_METHOD are derived from the stub too; other
    # functions must carry a hand-written comment (checked, not generated).
    if [[ $FIX -eq 1 ]]; then "$PHP" gen/method-comments.php >/dev/null || true; fi
    "$PHP" gen/method-comments.php --check || fail "method comments (run: php gen/method-comments.php, then comment the listed functions)"
    local after; after=$(md5sum src/gtk4_arginfo.h stubs/gtk4.php)
    if [[ "$before" != "$after" ]]; then
        if [[ $FIX -eq 1 ]]; then echo "  regenerated (commit the result)"; else fail "generated stubs were out of date (now regenerated - commit them)"; fi
    fi
    echo "  up to date"
}

# ---------------------------------------------------------------- cpp-lint
stage_cpp_lint() {
    local action="checking"; [[ $FIX -eq 1 ]] && action="fixing"
    local -a include_flags=(--extra-arg=-std=c++20 --extra-arg=-I"$PWD" --extra-arg=-I"$PWD/src" --extra-arg=-DHAVE_CONFIG_H)
    while IFS= read -r flag; do
        [[ -n "$flag" ]] && include_flags+=("--extra-arg=$flag")
    done < <(
        { "$PHP_CONFIG" --includes 2>/dev/null || true
          pkg-config --cflags glib-2.0 gobject-2.0 gtk4 2>/dev/null
          pkg-config --cflags webkitgtk-6.0 2>/dev/null || true; } | tr ' ' '\n'
    )
    mapfile -t cpp_files < <(find src -type f -name '*.cpp' | sort)
    # gtk4_arginfo.h is generated by gen_stub.php - not ours to format
    mapfile -t all_files < <(find src -type f \( -name '*.cpp' -o -name '*.h' \) ! -name 'gtk4_arginfo.h' | sort)

    local err_dir; err_dir=$(mktemp -d)
    # shellcheck disable=SC2064
    trap "rm -rf '$err_dir'" RETURN

    if substep tidy; then
        step "clang-tidy ($CLANG_TIDY, $JOBS jobs, $action)"
        local active=0
        for f in "${cpp_files[@]}"; do
            [[ $FAIL_FAST -eq 1 && -f "$err_dir/stop" ]] && break
            (
                echo "  $action: $f"
                local -a args=(--quiet "${include_flags[@]}")
                [[ $FIX -eq 1 ]] && args+=(--fix --fix-errors)
                if ! "$CLANG_TIDY" "$f" "${args[@]}" -- 2>&1; then
                    touch "$err_dir/$(basename "$f").tidy"
                    [[ $FAIL_FAST -eq 1 ]] && touch "$err_dir/stop"
                fi
            ) &
            active=$((active + 1))
            if [[ $active -ge $JOBS ]]; then wait -n || true; active=$((active - 1)); fi  # a failed job is recorded via err_dir
        done
        wait
    fi

    if substep format; then
        step "clang-format ($CLANG_FORMAT, $JOBS jobs, $action)"
        local active=0
        for f in "${all_files[@]}"; do
            (
                if [[ $FIX -eq 1 ]]; then
                    "$CLANG_FORMAT" -i "$f"
                elif ! "$CLANG_FORMAT" --dry-run --Werror "$f" 2>&1; then
                    touch "$err_dir/$(basename "$f").fmt"
                fi
            ) &
            active=$((active + 1))
            if [[ $active -ge $JOBS ]]; then wait -n || true; active=$((active - 1)); fi  # a failed job is recorded via err_dir
        done
        wait
    fi

    local tidy_errors fmt_errors
    tidy_errors=$(find "$err_dir" -name '*.tidy' | wc -l)
    fmt_errors=$(find "$err_dir" -name '*.fmt' | wc -l)
    echo "  clang-tidy errors: $tidy_errors, clang-format errors: $fmt_errors"
    [[ $tidy_errors -eq 0 && $fmt_errors -eq 0 ]] || fail "cpp-lint"
}

# ---------------------------------------------------------------- md-lint
# markdownlint-cli2 over every tracked *.md; rules live in .markdownlint-cli2.jsonc.
# Prefers a global install, falls back to npx (CI has neither pre-installed).
stage_md_lint() {
    local -a md
    if command -v markdownlint-cli2 >/dev/null; then
        md=(markdownlint-cli2)
    elif command -v npx >/dev/null; then
        # Version pinned in package.json (Dependabot bumps it there).
        local pin; pin=$(sed -n 's/.*"markdownlint-cli2": *"\([^"]*\)".*/\1/p' package.json)
        md=(npx --yes "markdownlint-cli2@${pin:-latest}")
    else
        fail "markdownlint-cli2 not found (npm i -g markdownlint-cli2, or install node for npx)"
    fi

    if [[ $FIX -eq 1 ]]; then
        step "markdownlint --fix"
        "${md[@]}" --fix || true   # non-zero when unfixable findings remain; the check below decides
    fi
    step "markdownlint (**/*.md)"
    "${md[@]}" || fail "md-lint (run ./ci.sh --only=md-lint --fix for the auto-fixable rules)"
}

# ---------------------------------------------------------------- php-qa
stage_php_qa() {
    ensure_vendor
    local ini_dir; ini_dir=$(gtk_free_ini_dir)
    # shellcheck disable=SC2064
    trap "rm -rf '$ini_dir'" RETURN
    local -a run=(env PHP_INI_SCAN_DIR="$ini_dir" "$PHP" -d memory_limit=-1)
    local status=0

    # Each formatter is one step that either checks or fixes, like cpp-lint - never
    # both, so --fix applies the fixes instead of printing a diff of them.
    local action="checking"; [[ $FIX -eq 1 ]] && action="fixing"

    if substep style; then
        step "phplint (-j $JOBS)"
        "${run[@]}" vendor/bin/phplint -j "$JOBS" --no-progress || status=1

        # phpcbf exits 1 when it fixed something, so phpcs is what gates either way -
        # and it is the only one that reports what no fixer can repair (line length).
        step "phpcs (--parallel=$JOBS, $action)"
        if [[ $FIX -eq 1 ]]; then
            "${run[@]}" vendor/bin/phpcbf --parallel="$JOBS" || true
        fi
        "${run[@]}" vendor/bin/phpcs --parallel="$JOBS" || status=1

        step "php-cs-fixer (all cores, $action)"
        if [[ $FIX -eq 1 ]]; then
            "${run[@]}" vendor/bin/php-cs-fixer fix --show-progress=none || status=1
        else
            "${run[@]}" vendor/bin/php-cs-fixer check --diff --show-progress=none || status=1
        fi
    fi

    if [[ $STAN -eq 1 ]] && substep stan; then
        step "phpstan (level max, all cores)"
        "${run[@]}" vendor/bin/phpstan analyse --no-progress --memory-limit=-1 || status=1
    fi
    [[ $status -eq 0 ]] || fail "php-qa"
}

# ---------------------------------------------------------------- build
# phpize build. Variants (--configure-args) rebuild in place after a clean,
# so each variant copies modules/gtk4.so to its own file name.
build_variant() {  # build_variant <output.so> [configure args...]
    local out="$1"; shift
    step "build ($PHPIZE / $PHP_CONFIG${*:+ $*}) -> $out"
    # Build artifacts owned by someone else (a build run under sudo) make make fail
    # with "Permission denied" - say so instead of dumping assembler errors.
    local foreign
    foreign=$(find . -path ./vendor -prune -o -path ./.git -prune -o ! -user "$(id -un)" -print 2>/dev/null | head -1)
    if [[ -n "$foreign" ]]; then
        fail "build artifacts owned by $(stat -c %U "$foreign") (e.g. $foreign) - run: sudo chown -R \"\$USER\" ."
    fi
    # NEVER `phpize --clean`: it deletes tests/*.php (php-src assumes .phpt there).
    # And phpize's `make clean` runs `find . -name '*.so' | xargs rm`, which would
    # take the already built variants in the repo root with it - stash them.
    local stash; stash=$(mktemp -d)
    cp -f gtk4*.so "$stash"/ 2>/dev/null || true
    [[ -f Makefile ]] && make clean >/dev/null 2>&1 || true
    cp -f "$stash"/*.so . 2>/dev/null || true
    rm -rf "$stash"
    "$PHPIZE" >/dev/null || fail "phpize"
    mkdir -p .ci
    ./configure --with-php-config="$PHP_CONFIG" "$@" > .ci/configure.log 2>&1 || { tail -20 .ci/configure.log; fail "configure"; }
    make -j"$JOBS" > .ci/make.log 2>&1 || { grep -E 'error|warning' .ci/make.log | head -40; fail "make"; }
    if grep -q 'warning:' .ci/make.log; then grep 'warning:' .ci/make.log | head -20; fail "compiler warnings"; fi
    cp -f modules/gtk4.so "$out"
}

stage_build() {
    build_variant gtk4.so
}

# ---------------------------------------------------------------- asan
# AddressSanitizer + UBSan + LeakSanitizer. The instrumented gtk4-asan.so is
# loaded into an uninstrumented php, so libasan is LD_PRELOADed into php only
# (not into xvfb-run/Xvfb). USE_ZEND_ALLOC=0 makes Zend use malloc so ASan
# sees every allocation. Suppressions: tests/lsan.supp (third-party only).
# tests/asan-dlopen-shim.c is preloaded ahead of libasan to strip RTLD_DEEPBIND
# from php's dlopen() (PHP builds with PHP_USE_RTLD_DEEPBIND, e.g. setup-php's):
# the sanitizer runtime refuses DEEPBIND outright. verify_asan_link_order=0 is
# what lets libasan be second in the preload list.
stage_asan() {
    ensure_vendor
    step "asan build (gtk4-asan.so)"
    local libasan; libasan=$(gcc -print-file-name=libasan.so)
    [[ -f "$libasan" ]] || fail "libasan.so not found (install libasan for your gcc)"
    build_variant gtk4-asan.so --enable-gtk4-sanitize --enable-gtk4-testing
    mkdir -p .ci
    local shim="$PWD/.ci/asan-dlopen-shim.so"
    gcc -shared -fPIC -O2 -o "$shim" tests/asan-dlopen-shim.c || fail "asan dlopen shim"

    local -a env=(LD_PRELOAD="$shim:$libasan" USE_ZEND_ALLOC=0
                  ASAN_OPTIONS="verify_asan_link_order=0:detect_leaks=1:abort_on_error=0:halt_on_error=1:strict_string_checks=1:detect_stack_use_after_return=1"
                  LSAN_OPTIONS="suppressions=$PWD/tests/lsan.supp:print_suppressions=0"
                  UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1")

    step "asan: stress script (tests/scripts/stress.php)"
    xvfb-run -a env "${env[@]}" GSK_RENDERER=cairo GDK_DEBUG=gl-disable GDK_BACKEND=x11 "$PHP" -n -dextension=./gtk4-asan.so tests/scripts/stress.php 300 \
        || fail "asan stress (see report above)"

    # The PHPUnit process also loads dom/mbstring/intl/... from the system ini;
    # those leak at their own shutdown (frames show as <unknown module>), which
    # is not ours to fix. Leak detection therefore runs only on the php -n
    # stress run above (our extension is the only module in that process);
    # here ASan/UBSan still catch memory errors across the whole suite.
    step "asan: phpunit suite (memory errors only, leaks checked by the stress run)"
    local -a env_nolsan=("${env[@]}")
    env_nolsan[2]="ASAN_OPTIONS=verify_asan_link_order=0:detect_leaks=0:abort_on_error=0:halt_on_error=1:strict_string_checks=1:detect_stack_use_after_return=1"
    PHP="$PHP" GTK4_SO=./gtk4-asan.so PHP_GTK4_ENV="${env_nolsan[*]}" ./tests/run.sh "${PHPUNIT_ARGS[@]}" || fail "asan phpunit"
}

# ---------------------------------------------------------------- coverage
# gcov line coverage of the C++ sources, driven by the PHPUnit suite and the
# stress script. Prints a per-file table; gcovr (if installed) writes
# coverage/index.html as well.
stage_coverage() {
    ensure_vendor
    step "coverage build (gtk4-cov.so)"
    find src -name '*.gcda' -delete 2>/dev/null || true
    build_variant gtk4-cov.so --enable-gtk4-coverage --enable-gtk4-testing

    step "coverage: phpunit suite + stress script"
    PHP="$PHP" GTK4_SO=./gtk4-cov.so ./tests/run.sh "${PHPUNIT_ARGS[@]}" || fail "coverage phpunit"
    xvfb-run -a env GSK_RENDERER=cairo GDK_DEBUG=gl-disable GDK_BACKEND=x11 "$PHP" -n -dextension=./gtk4-cov.so tests/scripts/stress.php 50 || fail "coverage stress"

    step "coverage: report (gcovr)"
    command -v gcovr >/dev/null || fail "gcovr not installed"
    mkdir -p coverage
    gcovr -r . -f 'src/' -e 'src/gtk4_arginfo.h' --gcov-ignore-parse-errors=negative_hits.warn \
          --fail-under-line "${COVERAGE_MIN_LINES:-80}" \
          --html-details coverage/index.html --print-summary || fail "gcovr (line coverage below ${COVERAGE_MIN_LINES:-80}%?)"
}

# ---------------------------------------------------------------- load
stage_load() {
    step "extension loads"
    [[ -f gtk4.so ]] || fail "gtk4.so missing (run the build stage)"
    "$PHP" -n -dextension=./gtk4.so -r 'exit(extension_loaded("gtk4") ? 0 : 1);' || fail "gtk4.so does not load"
    # The binary must report the version in ./VERSION - catches a stale build as
    # well as a mirror that drifted after the version stage ran.
    local want built
    want=$(version_file)
    built=$("$PHP" -n -dextension=./gtk4.so -r 'echo phpversion("gtk4"), "|", Gtk4\VERSION;')
    [[ "$built" == "$want|$want" ]] || fail "gtk4.so reports '${built%%|*}' / '${built##*|}', VERSION says '$want' (rebuild)"
    "$PHP" -n -dextension=./gtk4.so -r 'echo "  ", Gtk4\VERSION, " | ", Gtk4\BUILD_INFO, " | ", Gtk4\FEATURES, PHP_EOL;'
}

# ---------------------------------------------------------------- test
stage_test() {
    ensure_vendor
    step "phpunit (xvfb-run + bin/php-gtk4)"
    [[ -f gtk4.so ]] || fail "gtk4.so missing (run the build stage)"
    PHP="$PHP" GTK4_SO=./gtk4.so ./tests/run.sh "${PHPUNIT_ARGS[@]}" || fail "test"
}

# ---------------------------------------------------------------- phpt
# php-src's run-tests.php harness. Complements PHPUnit: each test is its own
# process and the harness compares stdout *and stderr*, so it can assert the
# g_critical fallback text, uncaught fatals, RSHUTDOWN teardown output and
# --INI--/--ENV-- dependent startup - none of which PHPUnit can reach.
# `make test` strips every extension= line from the scanned ini into tmp-php.ini
# and re-adds only modules/gtk4.so, so gtk3 is filtered out without bin/php-gtk4.
stage_phpt() {
    step "run-tests.php (xvfb-run + make test TESTS=$PHPT_TESTS)"
    [[ -f Makefile ]] || fail "no Makefile (run the build stage first)"
    # GTK_A11Y=none: these tests compare stderr, and a session bus without an a11y service (CI
    # runners) makes GTK print "Unable to acquire the address of the accessibility bus".
    GTK_A11Y=none GSK_RENDERER=cairo GDK_DEBUG=gl-disable GDK_BACKEND=x11 xvfb-run -a make --no-print-directory test TESTS="$PHPT_TESTS" \
        || fail "phpt (see the FAILED TEST SUMMARY above; .out/.diff files sit next to each .phpt)"
}

# ---------------------------------------------------------------- valgrind
# memcheck complements ASan (uninitialised reads, which ASan cannot see) on the
# normal, uninstrumented gtk4.so. Only the php -n stress run: valgrind is slow
# and the PHPUnit process would report other extensions' shutdown leaks.
stage_valgrind() {
    step "valgrind memcheck (tests/scripts/stress.php)"
    command -v valgrind >/dev/null || fail "valgrind not installed"
    [[ -f gtk4.so ]] || fail "gtk4.so missing (run the build stage)"
    local glib_supp=/usr/share/glib-2.0/valgrind/glib.supp
    local -a supp=(--suppressions="$PWD/tests/valgrind.supp")
    [[ -f "$glib_supp" ]] && supp+=(--suppressions="$glib_supp")
    # GDK_DEBUG=gl-disable: no Mesa/llvmpipe in the process (its thread pools leak on CI runners).
    # ZEND_DONT_UNLOAD_MODULES: PHP dlclose()s extensions at MSHUTDOWN, which also unloads
    # libgtk-4 - its static caches then lose their roots ("definitely lost" with ??? frames that
    # no suppression can match). Same switch php-src's run-tests.php uses under valgrind;
    # --keep-debuginfo keeps symbols for anything that still gets unloaded.
    # --show-leak-kinds=definite keeps the report readable; the exit code is what matters.
    xvfb-run -a env USE_ZEND_ALLOC=0 ZEND_DONT_UNLOAD_MODULES=1 \
        GSK_RENDERER=cairo GDK_DEBUG=gl-disable GDK_BACKEND=x11 \
        valgrind --quiet --error-exitcode=42 --leak-check=full --errors-for-leak-kinds=definite \
                 --show-leak-kinds=definite --keep-debuginfo=yes --track-origins=yes \
                 --num-callers=16 "${supp[@]}" \
        "$PHP" -n -dextension=./gtk4.so tests/scripts/stress.php 50 || fail "valgrind (see report above)"
}

# ---------------------------------------------------------------- main
ran=""
for stage in $ALL_STAGES; do
    enabled "$stage" || continue
    case "$stage" in
        version)  stage_version ;;
        stubs)    stage_stubs ;;
        cpp-lint) stage_cpp_lint ;;
        md-lint)  stage_md_lint ;;
        php-qa)   stage_php_qa ;;
        build)    stage_build ;;
        load)     stage_load ;;
        test)     stage_test ;;
        phpt)     stage_phpt ;;
        asan)     stage_asan ;;
        coverage) stage_coverage ;;
        valgrind) stage_valgrind ;;
    esac
    ran="$ran $stage"
done
[[ -n "$ran" ]] || fail "no stage selected (stages: $ALL_STAGES)"
printf "\n${GREEN}All checks passed:${NC}%s\n" "$ran"
