// GENERATED by gen/gir.php from GdkPixbuf.PixbufAnimation - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\GdkPixbufAnimation
#include "php_gtk4.h"
#include "core/object.h"
#include "core/gerror.h"
#include "core/callback.h"
#include <array>

using namespace phpgtk;

/**
 * Gtk4\GdkPixbufAnimation::__construct()
 *
 * GdkPixbufAnimation has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * static Gtk4\GdkPixbufAnimation::new_from_file(string $filename): GdkPixbufAnimation
 *
 * Creates a new animation by loading it from a file.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, new_from_file) {
  zend_string *filename;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_PATH_STR(filename)
  ZEND_PARSE_PARAMETERS_END();
  zend_string *filename_abs = phpgtk::absolute_filename(filename, 1);
  if (filename_abs == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  GdkPixbufAnimation *call_result =
      gdk_pixbuf_animation_new_from_file(ZSTR_VAL(filename_abs), &error);
  if (filename_abs != nullptr) zend_string_release(filename_abs);
  GObject *obj = G_OBJECT(call_result);
  if (obj == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

/**
 * static Gtk4\GdkPixbufAnimation::new_from_resource(string $resource_path): GdkPixbufAnimation
 *
 * Creates a new pixbuf animation by loading an image from an resource.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, new_from_resource) {
  zend_string *resource_path;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(resource_path)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_utf8(resource_path, 1)) RETURN_THROWS();
  GError *error = nullptr;
  GObject *obj = G_OBJECT(gdk_pixbuf_animation_new_from_resource(ZSTR_VAL(resource_path), &error));
  if (obj == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

/**
 * static Gtk4\GdkPixbufAnimation::new_from_stream(GInputStream $stream, ?GCancellable $cancellable
 * = null): GdkPixbufAnimation
 *
 * Creates a new animation by loading it from an input stream.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, new_from_stream) {
  zval *stream;
  zval *cancellable = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 2)
  Z_PARAM_OBJECT_OF_CLASS(stream, class_for_gtype(G_TYPE_INPUT_STREAM))
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  ZEND_PARSE_PARAMETERS_END();
  GObject *stream_o = unwrap(stream, G_TYPE_INPUT_STREAM);
  if (stream_o == nullptr) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  GError *error = nullptr;
  GObject *obj = G_OBJECT(gdk_pixbuf_animation_new_from_stream(
      G_INPUT_STREAM(stream_o), cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr,
      &error));
  if (obj == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

/**
 * static Gtk4\GdkPixbufAnimation::new_from_stream_finish(GAsyncResult $async_result):
 * GdkPixbufAnimation
 *
 * Finishes an asynchronous pixbuf animation creation operation started with
 * `new_from_stream_async`.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, new_from_stream_finish) {
  zval *async_result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(async_result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GObject *async_result_o = unwrap(async_result, G_TYPE_ASYNC_RESULT);
  if (async_result_o == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  GObject *obj =
      G_OBJECT(gdk_pixbuf_animation_new_from_stream_finish(G_ASYNC_RESULT(async_result_o), &error));
  if (obj == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  wrap(obj, return_value);
  if (obj != nullptr) g_object_unref(obj);  // the handle took its own reference
}

namespace {
// AsyncReadyCallback trampoline for GdkPixbufAnimation::new_from_stream_async(): wraps the C
// arguments, invokes the PHP callable once and releases it (async scope).
void cb_new_from_stream_async_callback(GObject *source_object, GAsyncResult *res, gpointer data) {
  auto *cb = static_cast<Callback *>(data);
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap(source_object != nullptr ? G_OBJECT(source_object) : nullptr, &argv[0]);
  wrap(res != nullptr ? G_OBJECT(res) : nullptr, &argv[1]);
  zval ret;
  callback_invoke(cb, 2, argv, &ret);
  if (!Z_ISUNDEF(ret)) zval_ptr_dtor(&ret);
  for (zval &arg : args) zval_ptr_dtor(&arg);
  callback_free(cb);
  callback_drain();
}
}  // namespace

/**
 * static Gtk4\GdkPixbufAnimation::new_from_stream_async(GInputStream $stream, ?GCancellable
 * $cancellable = null, ?callable $callback = null): void
 *
 * Creates a new animation by asynchronously loading an image from an input stream.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, new_from_stream_async) {
  zval *stream;
  zval *cancellable = nullptr;
  zend_fcall_info fci_callback = empty_fcall_info;
  zend_fcall_info_cache fcc_callback = empty_fcall_info_cache;
  ZEND_PARSE_PARAMETERS_START(1, 3)
  Z_PARAM_OBJECT_OF_CLASS(stream, class_for_gtype(G_TYPE_INPUT_STREAM))
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  Z_PARAM_FUNC_OR_NULL(fci_callback, fcc_callback)
  ZEND_PARSE_PARAMETERS_END();
  GObject *stream_o = unwrap(stream, G_TYPE_INPUT_STREAM);
  if (stream_o == nullptr) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  Callback *cb_callback =
      ZEND_FCI_INITIALIZED(fci_callback)
          ? callback_new(&fci_callback.function_name, "GdkPixbufAnimation::new_from_stream_async")
          : nullptr;
  gdk_pixbuf_animation_new_from_stream_async(
      G_INPUT_STREAM(stream_o), cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr,
      cb_callback != nullptr ? cb_new_from_stream_async_callback : nullptr, cb_callback);
}

/**
 * Gtk4\GdkPixbufAnimation::get_height(): int
 *
 * Queries the height of the bounding box of a pixbuf animation.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, get_height) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkPixbufAnimation *self = PHPGTK_SELF(GdkPixbufAnimation, GDK_TYPE_PIXBUF_ANIMATION);
  RETURN_LONG(static_cast<zend_long>(gdk_pixbuf_animation_get_height(self)));
}

/**
 * Gtk4\GdkPixbufAnimation::get_static_image(): GdkPixbuf
 *
 * Retrieves a static image for the animation.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, get_static_image) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkPixbufAnimation *self = PHPGTK_SELF(GdkPixbufAnimation, GDK_TYPE_PIXBUF_ANIMATION);
  GdkPixbuf *phpgtk_ret = gdk_pixbuf_animation_get_static_image(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GdkPixbufAnimation::get_width(): int
 *
 * Queries the width of the bounding box of a pixbuf animation.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, get_width) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkPixbufAnimation *self = PHPGTK_SELF(GdkPixbufAnimation, GDK_TYPE_PIXBUF_ANIMATION);
  RETURN_LONG(static_cast<zend_long>(gdk_pixbuf_animation_get_width(self)));
}

/**
 * Gtk4\GdkPixbufAnimation::is_static_image(): bool
 *
 * Checks whether the animation is a static image.
 */
ZEND_METHOD(Gtk4_GdkPixbufAnimation, is_static_image) {
  ZEND_PARSE_PARAMETERS_NONE();
  GdkPixbufAnimation *self = PHPGTK_SELF(GdkPixbufAnimation, GDK_TYPE_PIXBUF_ANIMATION);
  RETURN_BOOL(gdk_pixbuf_animation_is_static_image(self));
}
