// GENERATED by gen/gir.php from Gio.InputStream - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GInputStream
#include "php_gtk4.h"
#include "core/object.h"
#include "core/gerror.h"
#include "core/subtype.h"
#include "core/callback.h"
#include <array>

using namespace phpgtk;

/**
 * Gtk4\GInputStream::__construct()
 *
 * GInputStream is abstract in GTK: `new` only works on a PHP subclass (which gets its own GType).
 */
ZEND_METHOD(Gtk4_GInputStream, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) == nullptr) {
      zend_throw_error(nullptr,
                       "GInputStream is abstract in GTK: subclass it in PHP (new MyClass())");
    }
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GInputStream::clear_pending(): void
 *
 * Clears the pending flag on $stream.
 */
ZEND_METHOD(Gtk4_GInputStream, clear_pending) {
  ZEND_PARSE_PARAMETERS_NONE();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  g_input_stream_clear_pending(self);
}

/**
 * Gtk4\GInputStream::close(?GCancellable $cancellable): bool
 *
 * Closes the stream, releasing resources related to it.
 */
ZEND_METHOD(Gtk4_GInputStream, close) {
  zval *cancellable = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  GError *error = nullptr;
  const gboolean ok = g_input_stream_close(
      self, cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

namespace {
// AsyncReadyCallback trampoline for GInputStream::close_async(): wraps the C arguments, invokes the
// PHP callable once and releases it (async scope).
void cb_close_async_callback(GObject *source_object, GAsyncResult *res, gpointer data) {
  auto *cb = static_cast<Callback *>(data);
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap(source_object != nullptr ? G_OBJECT(source_object) : nullptr, &argv[0]);
  wrap(res != nullptr ? G_OBJECT(res) : nullptr, &argv[1]);
  zval ret;
  callback_invoke(cb, 2, argv, &ret);
  if (!Z_ISUNDEF(ret)) zval_ptr_dtor(&ret);
  for (zval &arg : args) zval_ptr_dtor(&arg);
  callback_free(cb);
  callback_drain();
}
}  // namespace

/**
 * Gtk4\GInputStream::close_async(int $io_priority, ?GCancellable $cancellable, ?callable
 * $callback): void
 *
 * Requests an asynchronous closes of the stream, releasing resources related to it. When the
 * operation is finished $callback will be called. You can then call g_input_stream_close_finish()
 * to get the result of the operation.
 */
ZEND_METHOD(Gtk4_GInputStream, close_async) {
  zend_long io_priority;
  zval *cancellable = nullptr;
  zend_fcall_info fci_callback = empty_fcall_info;
  zend_fcall_info_cache fcc_callback = empty_fcall_info_cache;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_LONG(io_priority)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  Z_PARAM_FUNC_OR_NULL(fci_callback, fcc_callback)
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  if (!phpgtk::check_range<int>(io_priority, 1)) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  Callback *cb_callback =
      ZEND_FCI_INITIALIZED(fci_callback)
          ? callback_new(&fci_callback.function_name, "GInputStream::close_async")
          : nullptr;
  g_input_stream_close_async(self, static_cast<int>(io_priority),
                             cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr,
                             cb_callback != nullptr ? cb_close_async_callback : nullptr,
                             cb_callback);
}

/**
 * Gtk4\GInputStream::close_finish(GAsyncResult $result): bool
 *
 * Finishes closing a stream asynchronously, started from g_input_stream_close_async().
 */
ZEND_METHOD(Gtk4_GInputStream, close_finish) {
  zval *result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *result_o = unwrap(result, G_TYPE_ASYNC_RESULT);
  if (result_o == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  const gboolean ok = g_input_stream_close_finish(self, G_ASYNC_RESULT(result_o), &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GInputStream::has_pending(): bool
 *
 * Checks if an input stream has pending actions.
 */
ZEND_METHOD(Gtk4_GInputStream, has_pending) {
  ZEND_PARSE_PARAMETERS_NONE();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  RETURN_BOOL(g_input_stream_has_pending(self));
}

/**
 * Gtk4\GInputStream::is_closed(): bool
 *
 * Checks if an input stream is closed.
 */
ZEND_METHOD(Gtk4_GInputStream, is_closed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  RETURN_BOOL(g_input_stream_is_closed(self));
}

/**
 * Gtk4\GInputStream::read_all_finish(GAsyncResult $result): ?int
 *
 * Finishes an asynchronous stream read operation started with g_input_stream_read_all_async().
 */
ZEND_METHOD(Gtk4_GInputStream, read_all_finish) {
  zval *result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *result_o = unwrap(result, G_TYPE_ASYNC_RESULT);
  if (result_o == nullptr) RETURN_THROWS();
  gsize bytes_read = 0;
  GError *error = nullptr;
  if (!g_input_stream_read_all_finish(self, G_ASYNC_RESULT(result_o), &bytes_read, &error))
    RETURN_NULL();
  ZVAL_LONG(return_value, static_cast<zend_long>(bytes_read));
}

/**
 * Gtk4\GInputStream::read_bytes(int $count, ?GCancellable $cancellable): string
 *
 * Like g_input_stream_read(), this tries to read $count bytes from the stream in a blocking
 * fashion. However, rather than reading into a user-supplied buffer, this will create a new
 * #GBytes containing the data that was read. This may be easier to use from language bindings.
 */
ZEND_METHOD(Gtk4_GInputStream, read_bytes) {
  zend_long count;
  zval *cancellable = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(count)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  if (!phpgtk::check_range<gsize>(count, 1)) RETURN_THROWS();
  if (!phpgtk::check_domain(count, 0, 2147483647, 1)) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  GError *error = nullptr;
  GBytes *bytes = g_input_stream_read_bytes(
      self, static_cast<gsize>(count),
      cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr, &error);
  if (bytes == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  gsize size = 0;
  const auto *data = static_cast<const char *>(g_bytes_get_data(bytes, &size));
  RETVAL_STRINGL(data, size);
  g_bytes_unref(bytes);
}

namespace {
// AsyncReadyCallback trampoline for GInputStream::read_bytes_async(): wraps the C arguments,
// invokes the PHP callable once and releases it (async scope).
void cb_read_bytes_async_callback(GObject *source_object, GAsyncResult *res, gpointer data) {
  auto *cb = static_cast<Callback *>(data);
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap(source_object != nullptr ? G_OBJECT(source_object) : nullptr, &argv[0]);
  wrap(res != nullptr ? G_OBJECT(res) : nullptr, &argv[1]);
  zval ret;
  callback_invoke(cb, 2, argv, &ret);
  if (!Z_ISUNDEF(ret)) zval_ptr_dtor(&ret);
  for (zval &arg : args) zval_ptr_dtor(&arg);
  callback_free(cb);
  callback_drain();
}
}  // namespace

/**
 * Gtk4\GInputStream::read_bytes_async(int $count, int $io_priority, ?GCancellable $cancellable,
 * ?callable $callback): void
 *
 * Request an asynchronous read of $count bytes from the stream into a new #GBytes. When the
 * operation is finished $callback will be called. You can then call
 * g_input_stream_read_bytes_finish() to get the result of the operation.
 */
ZEND_METHOD(Gtk4_GInputStream, read_bytes_async) {
  zend_long count;
  zend_long io_priority;
  zval *cancellable = nullptr;
  zend_fcall_info fci_callback = empty_fcall_info;
  zend_fcall_info_cache fcc_callback = empty_fcall_info_cache;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_LONG(count)
  Z_PARAM_LONG(io_priority)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  Z_PARAM_FUNC_OR_NULL(fci_callback, fcc_callback)
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  if (!phpgtk::check_range<gsize>(count, 1)) RETURN_THROWS();
  if (!phpgtk::check_domain(count, 0, 2147483647, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(io_priority, 2)) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  Callback *cb_callback =
      ZEND_FCI_INITIALIZED(fci_callback)
          ? callback_new(&fci_callback.function_name, "GInputStream::read_bytes_async")
          : nullptr;
  g_input_stream_read_bytes_async(self, static_cast<gsize>(count), static_cast<int>(io_priority),
                                  cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr,
                                  cb_callback != nullptr ? cb_read_bytes_async_callback : nullptr,
                                  cb_callback);
}

/**
 * Gtk4\GInputStream::read_bytes_finish(GAsyncResult $result): string
 *
 * Finishes an asynchronous stream read-into-#GBytes operation.
 */
ZEND_METHOD(Gtk4_GInputStream, read_bytes_finish) {
  zval *result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *result_o = unwrap(result, G_TYPE_ASYNC_RESULT);
  if (result_o == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  GBytes *bytes = g_input_stream_read_bytes_finish(self, G_ASYNC_RESULT(result_o), &error);
  if (bytes == nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  gsize size = 0;
  const auto *data = static_cast<const char *>(g_bytes_get_data(bytes, &size));
  RETVAL_STRINGL(data, size);
  g_bytes_unref(bytes);
}

/**
 * Gtk4\GInputStream::read_finish(GAsyncResult $result): int
 *
 * Finishes an asynchronous stream read operation.
 */
ZEND_METHOD(Gtk4_GInputStream, read_finish) {
  zval *result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *result_o = unwrap(result, G_TYPE_ASYNC_RESULT);
  if (result_o == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  const auto value =
      static_cast<zend_long>(g_input_stream_read_finish(self, G_ASYNC_RESULT(result_o), &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}

/**
 * Gtk4\GInputStream::set_pending(): bool
 *
 * Sets $stream to have actions pending. If the pending flag is already set or $stream is closed,
 * it will return `false` and set $error.
 */
ZEND_METHOD(Gtk4_GInputStream, set_pending) {
  ZEND_PARSE_PARAMETERS_NONE();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GError *error = nullptr;
  const gboolean ok = g_input_stream_set_pending(self, &error);
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_BOOL(ok);
}

/**
 * Gtk4\GInputStream::skip(int $count, ?GCancellable $cancellable): int
 *
 * Tries to skip $count bytes from the stream. Will block during the operation.
 */
ZEND_METHOD(Gtk4_GInputStream, skip) {
  zend_long count;
  zval *cancellable = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(count)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  if (!phpgtk::check_range<gsize>(count, 1)) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  GError *error = nullptr;
  const auto value = static_cast<zend_long>(g_input_stream_skip(
      self, static_cast<gsize>(count),
      cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr, &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}

namespace {
// AsyncReadyCallback trampoline for GInputStream::skip_async(): wraps the C arguments, invokes the
// PHP callable once and releases it (async scope).
void cb_skip_async_callback(GObject *source_object, GAsyncResult *res, gpointer data) {
  auto *cb = static_cast<Callback *>(data);
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap(source_object != nullptr ? G_OBJECT(source_object) : nullptr, &argv[0]);
  wrap(res != nullptr ? G_OBJECT(res) : nullptr, &argv[1]);
  zval ret;
  callback_invoke(cb, 2, argv, &ret);
  if (!Z_ISUNDEF(ret)) zval_ptr_dtor(&ret);
  for (zval &arg : args) zval_ptr_dtor(&arg);
  callback_free(cb);
  callback_drain();
}
}  // namespace

/**
 * Gtk4\GInputStream::skip_async(int $count, int $io_priority, ?GCancellable $cancellable, ?callable
 * $callback): void
 *
 * Request an asynchronous skip of $count bytes from the stream. When the operation is finished
 * $callback will be called. You can then call g_input_stream_skip_finish() to get the result of
 * the operation.
 */
ZEND_METHOD(Gtk4_GInputStream, skip_async) {
  zend_long count;
  zend_long io_priority;
  zval *cancellable = nullptr;
  zend_fcall_info fci_callback = empty_fcall_info;
  zend_fcall_info_cache fcc_callback = empty_fcall_info_cache;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_LONG(count)
  Z_PARAM_LONG(io_priority)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(cancellable, class_for_gtype(G_TYPE_CANCELLABLE))
  Z_PARAM_FUNC_OR_NULL(fci_callback, fcc_callback)
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  if (!phpgtk::check_range<gsize>(count, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(io_priority, 2)) RETURN_THROWS();
  GObject *cancellable_o = nullptr;
  if (cancellable != nullptr) {
    cancellable_o = unwrap(cancellable, G_TYPE_CANCELLABLE);
    if (cancellable_o == nullptr) RETURN_THROWS();
  }
  Callback *cb_callback =
      ZEND_FCI_INITIALIZED(fci_callback)
          ? callback_new(&fci_callback.function_name, "GInputStream::skip_async")
          : nullptr;
  g_input_stream_skip_async(self, static_cast<gsize>(count), static_cast<int>(io_priority),
                            cancellable_o != nullptr ? G_CANCELLABLE(cancellable_o) : nullptr,
                            cb_callback != nullptr ? cb_skip_async_callback : nullptr, cb_callback);
}

/**
 * Gtk4\GInputStream::skip_finish(GAsyncResult $result): int
 *
 * Finishes a stream skip operation.
 */
ZEND_METHOD(Gtk4_GInputStream, skip_finish) {
  zval *result;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(result, class_for_gtype(G_TYPE_ASYNC_RESULT))
  ZEND_PARSE_PARAMETERS_END();
  GInputStream *self = PHPGTK_SELF(GInputStream, G_TYPE_INPUT_STREAM);
  GObject *result_o = unwrap(result, G_TYPE_ASYNC_RESULT);
  if (result_o == nullptr) RETURN_THROWS();
  GError *error = nullptr;
  const auto value =
      static_cast<zend_long>(g_input_stream_skip_finish(self, G_ASYNC_RESULT(result_o), &error));
  if (error != nullptr) {
    throw_gerror(error);
    RETURN_THROWS();
  }
  RETURN_LONG(value);
}
