// GENERATED by gen/gir.php from Gio.ListStore - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GListStore
#include "php_gtk4.h"
#include "core/object.h"

using namespace phpgtk;

// The item type comes in as a PHP class name (PhpValue::class), not a GType.
namespace {
// Resolve "Gtk4\PhpValue" / "PhpValue" / any registered class name to a GObject GType.
GType item_type_from_string(zend_string *name) {
  const char *s = ZSTR_VAL(name);
  const char *slash = strrchr(s, '\\');
  const char *gtype_name = slash != nullptr ? slash + 1 : s;
  zend_class_entry *ce = class_for_gtype_name(gtype_name);
  GType t = ce != nullptr ? gtype_for_class(ce) : 0;
  if (t == 0 || g_type_is_a(t, G_TYPE_OBJECT) == FALSE) {
    zend_argument_value_error(1, "must name a registered GObject class, \"%s\" given", s);
    return 0;
  }
  return t;
}
}  // namespace

/**
 * Gtk4\GListStore::append(GObject $item): void
 *
 * Appends $item to $store. $item must be of type #GListStore:item-type.
 */
ZEND_METHOD(Gtk4_GListStore, append) {
  zval *item;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_OBJECT))
  ZEND_PARSE_PARAMETERS_END();
  GListStore *self = PHPGTK_SELF(GListStore, G_TYPE_LIST_STORE);
  GObject *item_o = unwrap(item, G_TYPE_OBJECT);
  if (item_o == nullptr) RETURN_THROWS();
  g_list_store_append(self, G_OBJECT(item_o));
}

/**
 * Gtk4\GListStore::find(GObject $item): ?int
 *
 * Looks up the given $item in the list store by looping over the items until the first occurrence
 * of $item. If $item was not found, then $position will not be set, and this method will return
 * `false`.
 */
ZEND_METHOD(Gtk4_GListStore, find) {
  zval *item;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_OBJECT))
  ZEND_PARSE_PARAMETERS_END();
  GListStore *self = PHPGTK_SELF(GListStore, G_TYPE_LIST_STORE);
  GObject *item_o = unwrap(item, G_TYPE_OBJECT);
  if (item_o == nullptr) RETURN_THROWS();
  guint position = 0;
  if (!g_list_store_find(self, G_OBJECT(item_o), &position)) RETURN_NULL();
  ZVAL_LONG(return_value, static_cast<zend_long>(position));
}

/**
 * Gtk4\GListStore::insert(int $position, GObject $item): void
 *
 * Inserts $item into $store at $position. $item must be of type #GListStore:item-type or derived
 * from it. $position must be smaller than the length of the list, or equal to it to append.
 */
ZEND_METHOD(Gtk4_GListStore, insert) {
  zend_long position;
  zval *item;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(position)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_OBJECT))
  ZEND_PARSE_PARAMETERS_END();
  GListStore *self = PHPGTK_SELF(GListStore, G_TYPE_LIST_STORE);
  if (!phpgtk::check_range<guint>(position, 1)) RETURN_THROWS();
  GObject *item_o = unwrap(item, G_TYPE_OBJECT);
  if (item_o == nullptr) RETURN_THROWS();
  const bool precondition_0 = position <= g_list_model_get_n_items(G_LIST_MODEL(self));
  if (!precondition_0) {
    zend_argument_value_error(1, "must not be past the end of the store");
    RETURN_THROWS();
  }
  g_list_store_insert(self, static_cast<guint>(position), G_OBJECT(item_o));
}

/**
 * Gtk4\GListStore::remove(int $position): void
 *
 * Removes the item from $store that is at $position. $position must be smaller than the current
 * length of the list.
 */
ZEND_METHOD(Gtk4_GListStore, remove) {
  zend_long position;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(position)
  ZEND_PARSE_PARAMETERS_END();
  GListStore *self = PHPGTK_SELF(GListStore, G_TYPE_LIST_STORE);
  if (!phpgtk::check_range<guint>(position, 1)) RETURN_THROWS();
  const bool precondition_0 = position < g_list_model_get_n_items(G_LIST_MODEL(self));
  if (!precondition_0) {
    zend_argument_value_error(1, "must be the position of an item");
    RETURN_THROWS();
  }
  g_list_store_remove(self, static_cast<guint>(position));
}

/**
 * Gtk4\GListStore::remove_all(): void
 *
 * Removes all items from $store.
 */
ZEND_METHOD(Gtk4_GListStore, remove_all) {
  ZEND_PARSE_PARAMETERS_NONE();
  GListStore *self = PHPGTK_SELF(GListStore, G_TYPE_LIST_STORE);
  g_list_store_remove_all(self);
}

/**
 * public function __construct(string $item_type = GObject::class)
 * A GListModel backed by an array; items must be instances of $item_type (a PHP class name of
 * a registered GObject class, e.g. PhpValue::class).
 */
ZEND_METHOD(Gtk4_GListStore, __construct) {
  zend_string *type = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_STR(type)
  ZEND_PARSE_PARAMETERS_END();
  GType t = G_TYPE_OBJECT;
  if (type != nullptr) {
    t = item_type_from_string(type);
    if (t == 0) RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), G_OBJECT(g_list_store_new(t)));
}
