// GENERATED by gen/gir.php from Gio.Menu - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GMenu
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GMenu::__construct()
 *
 * Creates a new #GMenu.
 */
ZEND_METHOD(Gtk4_GMenu, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(g_menu_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GMenu::append(?string $label, ?string $detailed_action): void
 *
 * Convenience function for appending a normal menu item to the end of $menu. Combine
 * g_menu_item_new() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, append) {
  zend_string *label = nullptr;
  zend_string *detailed_action = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_STR_OR_NULL(detailed_action)
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  if (detailed_action != nullptr && !phpgtk::check_utf8(detailed_action, 2)) RETURN_THROWS();
  g_menu_append(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                detailed_action != nullptr ? ZSTR_VAL(detailed_action) : nullptr);
}

/**
 * Gtk4\GMenu::append_item(GMenuItem $item): void
 *
 * Appends $item to the end of $menu.
 */
ZEND_METHOD(Gtk4_GMenu, append_item) {
  zval *item;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_MENU_ITEM))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  GObject *item_o = unwrap(item, G_TYPE_MENU_ITEM);
  if (item_o == nullptr) RETURN_THROWS();
  g_menu_append_item(self, G_MENU_ITEM(item_o));
}

/**
 * Gtk4\GMenu::append_section(?string $label, GMenuModel $section): void
 *
 * Convenience function for appending a section menu item to the end of $menu. Combine
 * g_menu_item_new_section() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, append_section) {
  zend_string *label = nullptr;
  zval *section;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(section, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *section_o = unwrap(section, G_TYPE_MENU_MODEL);
  if (section_o == nullptr) RETURN_THROWS();
  g_menu_append_section(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                        G_MENU_MODEL(section_o));
}

/**
 * Gtk4\GMenu::append_submenu(?string $label, GMenuModel $submenu): void
 *
 * Convenience function for appending a submenu menu item to the end of $menu. Combine
 * g_menu_item_new_submenu() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, append_submenu) {
  zend_string *label = nullptr;
  zval *submenu;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(submenu, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *submenu_o = unwrap(submenu, G_TYPE_MENU_MODEL);
  if (submenu_o == nullptr) RETURN_THROWS();
  g_menu_append_submenu(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                        G_MENU_MODEL(submenu_o));
}

/**
 * Gtk4\GMenu::freeze(): void
 *
 * Marks $menu as frozen.
 */
ZEND_METHOD(Gtk4_GMenu, freeze) {
  ZEND_PARSE_PARAMETERS_NONE();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  g_menu_freeze(self);
}

/**
 * Gtk4\GMenu::insert(int $position, ?string $label, ?string $detailed_action): void
 *
 * Convenience function for inserting a normal menu item into $menu. Combine g_menu_item_new() and
 * g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, insert) {
  zend_long position;
  zend_string *label = nullptr;
  zend_string *detailed_action = nullptr;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_LONG(position)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_STR_OR_NULL(detailed_action)
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (!phpgtk::check_range<gint>(position, 1)) RETURN_THROWS();
  if (label != nullptr && !phpgtk::check_utf8(label, 2)) RETURN_THROWS();
  if (detailed_action != nullptr && !phpgtk::check_utf8(detailed_action, 3)) RETURN_THROWS();
  g_menu_insert(self, static_cast<gint>(position), label != nullptr ? ZSTR_VAL(label) : nullptr,
                detailed_action != nullptr ? ZSTR_VAL(detailed_action) : nullptr);
}

/**
 * Gtk4\GMenu::insert_item(int $position, GMenuItem $item): void
 *
 * Inserts $item into $menu.
 */
ZEND_METHOD(Gtk4_GMenu, insert_item) {
  zend_long position;
  zval *item;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(position)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_MENU_ITEM))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (!phpgtk::check_range<gint>(position, 1)) RETURN_THROWS();
  GObject *item_o = unwrap(item, G_TYPE_MENU_ITEM);
  if (item_o == nullptr) RETURN_THROWS();
  g_menu_insert_item(self, static_cast<gint>(position), G_MENU_ITEM(item_o));
}

/**
 * Gtk4\GMenu::insert_section(int $position, ?string $label, GMenuModel $section): void
 *
 * Convenience function for inserting a section menu item into $menu. Combine
 * g_menu_item_new_section() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, insert_section) {
  zend_long position;
  zend_string *label = nullptr;
  zval *section;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_LONG(position)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(section, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (!phpgtk::check_range<gint>(position, 1)) RETURN_THROWS();
  if (label != nullptr && !phpgtk::check_utf8(label, 2)) RETURN_THROWS();
  GObject *section_o = unwrap(section, G_TYPE_MENU_MODEL);
  if (section_o == nullptr) RETURN_THROWS();
  g_menu_insert_section(self, static_cast<gint>(position),
                        label != nullptr ? ZSTR_VAL(label) : nullptr, G_MENU_MODEL(section_o));
}

/**
 * Gtk4\GMenu::insert_submenu(int $position, ?string $label, GMenuModel $submenu): void
 *
 * Convenience function for inserting a submenu menu item into $menu. Combine
 * g_menu_item_new_submenu() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, insert_submenu) {
  zend_long position;
  zend_string *label = nullptr;
  zval *submenu;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_LONG(position)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(submenu, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (!phpgtk::check_range<gint>(position, 1)) RETURN_THROWS();
  if (label != nullptr && !phpgtk::check_utf8(label, 2)) RETURN_THROWS();
  GObject *submenu_o = unwrap(submenu, G_TYPE_MENU_MODEL);
  if (submenu_o == nullptr) RETURN_THROWS();
  g_menu_insert_submenu(self, static_cast<gint>(position),
                        label != nullptr ? ZSTR_VAL(label) : nullptr, G_MENU_MODEL(submenu_o));
}

/**
 * Gtk4\GMenu::prepend(?string $label, ?string $detailed_action): void
 *
 * Convenience function for prepending a normal menu item to the start of $menu. Combine
 * g_menu_item_new() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, prepend) {
  zend_string *label = nullptr;
  zend_string *detailed_action = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_STR_OR_NULL(detailed_action)
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  if (detailed_action != nullptr && !phpgtk::check_utf8(detailed_action, 2)) RETURN_THROWS();
  g_menu_prepend(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                 detailed_action != nullptr ? ZSTR_VAL(detailed_action) : nullptr);
}

/**
 * Gtk4\GMenu::prepend_item(GMenuItem $item): void
 *
 * Prepends $item to the start of $menu.
 */
ZEND_METHOD(Gtk4_GMenu, prepend_item) {
  zval *item;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(item, class_for_gtype(G_TYPE_MENU_ITEM))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  GObject *item_o = unwrap(item, G_TYPE_MENU_ITEM);
  if (item_o == nullptr) RETURN_THROWS();
  g_menu_prepend_item(self, G_MENU_ITEM(item_o));
}

/**
 * Gtk4\GMenu::prepend_section(?string $label, GMenuModel $section): void
 *
 * Convenience function for prepending a section menu item to the start of $menu. Combine
 * g_menu_item_new_section() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, prepend_section) {
  zend_string *label = nullptr;
  zval *section;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(section, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *section_o = unwrap(section, G_TYPE_MENU_MODEL);
  if (section_o == nullptr) RETURN_THROWS();
  g_menu_prepend_section(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                         G_MENU_MODEL(section_o));
}

/**
 * Gtk4\GMenu::prepend_submenu(?string $label, GMenuModel $submenu): void
 *
 * Convenience function for prepending a submenu menu item to the start of $menu. Combine
 * g_menu_item_new_submenu() and g_menu_insert_item() for a more flexible alternative.
 */
ZEND_METHOD(Gtk4_GMenu, prepend_submenu) {
  zend_string *label = nullptr;
  zval *submenu;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(label)
  Z_PARAM_OBJECT_OF_CLASS(submenu, class_for_gtype(G_TYPE_MENU_MODEL))
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *submenu_o = unwrap(submenu, G_TYPE_MENU_MODEL);
  if (submenu_o == nullptr) RETURN_THROWS();
  g_menu_prepend_submenu(self, label != nullptr ? ZSTR_VAL(label) : nullptr,
                         G_MENU_MODEL(submenu_o));
}

/**
 * Gtk4\GMenu::remove(int $position): void
 *
 * Removes an item from the menu.
 */
ZEND_METHOD(Gtk4_GMenu, remove) {
  zend_long position;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(position)
  ZEND_PARSE_PARAMETERS_END();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  if (!phpgtk::check_range<gint>(position, 1)) RETURN_THROWS();
  g_menu_remove(self, static_cast<gint>(position));
}

/**
 * Gtk4\GMenu::remove_all(): void
 *
 * Removes all items in the menu.
 */
ZEND_METHOD(Gtk4_GMenu, remove_all) {
  ZEND_PARSE_PARAMETERS_NONE();
  GMenu *self = PHPGTK_SELF(GMenu, G_TYPE_MENU);
  g_menu_remove_all(self);
}
