// GENERATED by gen/gir.php from Gtk.AspectFrame - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkAspectFrame
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkAspectFrame::__construct(float $xalign, float $yalign, float $ratio, bool $obey_child)
 *
 * Create a new `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, __construct) {
  double xalign;
  double yalign;
  double ratio;
  bool obey_child;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_DOUBLE(xalign)
  Z_PARAM_DOUBLE(yalign)
  Z_PARAM_DOUBLE(ratio)
  Z_PARAM_BOOL(obey_child)
  ZEND_PARSE_PARAMETERS_END();
  GObject *obj = subtype_new(ZEND_THIS, "xalign", static_cast<float>(xalign), "yalign",
                             static_cast<float>(yalign), "ratio", static_cast<float>(ratio),
                             "obey-child", obey_child, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_aspect_frame_new(static_cast<float>(xalign), static_cast<float>(yalign),
                                        static_cast<float>(ratio), obey_child));
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkAspectFrame::get_child(): ?GtkWidget
 *
 * Gets the child widget of $self.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, get_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  GtkWidget *phpgtk_ret = gtk_aspect_frame_get_child(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkAspectFrame::get_obey_child(): bool
 *
 * Returns whether the child's size request should override the set aspect ratio of the
 * `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, get_obey_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  RETURN_BOOL(gtk_aspect_frame_get_obey_child(self));
}

/**
 * Gtk4\GtkAspectFrame::get_ratio(): float
 *
 * Returns the desired aspect ratio of the child.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, get_ratio) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  RETURN_DOUBLE(gtk_aspect_frame_get_ratio(self));
}

/**
 * Gtk4\GtkAspectFrame::get_xalign(): float
 *
 * Returns the horizontal alignment of the child within the allocation of the `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, get_xalign) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  RETURN_DOUBLE(gtk_aspect_frame_get_xalign(self));
}

/**
 * Gtk4\GtkAspectFrame::get_yalign(): float
 *
 * Returns the vertical alignment of the child within the allocation of the `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, get_yalign) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  RETURN_DOUBLE(gtk_aspect_frame_get_yalign(self));
}

/**
 * Gtk4\GtkAspectFrame::set_child(?GtkWidget $child): void
 *
 * Sets the child widget of $self.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, set_child) {
  zval *child = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(child, class_for_gtype(GTK_TYPE_WIDGET))
  ZEND_PARSE_PARAMETERS_END();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  GObject *child_o = nullptr;
  if (child != nullptr) {
    child_o = unwrap(child, GTK_TYPE_WIDGET);
    if (child_o == nullptr) RETURN_THROWS();
  }
  gtk_aspect_frame_set_child(self, child_o != nullptr ? GTK_WIDGET(child_o) : nullptr);
}

/**
 * Gtk4\GtkAspectFrame::set_obey_child(bool $obey_child): void
 *
 * Sets whether the aspect ratio of the child's size request should override the set aspect ratio
 * of the `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, set_obey_child) {
  bool obey_child;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(obey_child)
  ZEND_PARSE_PARAMETERS_END();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  gtk_aspect_frame_set_obey_child(self, obey_child);
}

/**
 * Gtk4\GtkAspectFrame::set_ratio(float $ratio): void
 *
 * Sets the desired aspect ratio of the child.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, set_ratio) {
  double ratio;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(ratio)
  ZEND_PARSE_PARAMETERS_END();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  gtk_aspect_frame_set_ratio(self, static_cast<float>(ratio));
}

/**
 * Gtk4\GtkAspectFrame::set_xalign(float $xalign): void
 *
 * Sets the horizontal alignment of the child within the allocation of the `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, set_xalign) {
  double xalign;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(xalign)
  ZEND_PARSE_PARAMETERS_END();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  gtk_aspect_frame_set_xalign(self, static_cast<float>(xalign));
}

/**
 * Gtk4\GtkAspectFrame::set_yalign(float $yalign): void
 *
 * Sets the vertical alignment of the child within the allocation of the `GtkAspectFrame`.
 */
ZEND_METHOD(Gtk4_GtkAspectFrame, set_yalign) {
  double yalign;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(yalign)
  ZEND_PARSE_PARAMETERS_END();
  GtkAspectFrame *self = PHPGTK_SELF(GtkAspectFrame, GTK_TYPE_ASPECT_FRAME);
  gtk_aspect_frame_set_yalign(self, static_cast<float>(yalign));
}
