// GENERATED by gen/gir.php from Gtk.Button - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkButton
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"
#include "core/error.h"

using namespace phpgtk;

/**
 * Gtk4\GtkButton::__construct()
 *
 * Creates a new `GtkButton` widget.
 */
ZEND_METHOD(Gtk4_GtkButton, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_button_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * static Gtk4\GtkButton::new_from_icon_name(string $icon_name): GtkButton
 *
 * Creates a new button containing an icon from the current icon theme.
 */
ZEND_METHOD(Gtk4_GtkButton, new_from_icon_name) {
  zend_string *icon_name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(icon_name)
  ZEND_PARSE_PARAMETERS_END();
  GObject *obj = G_OBJECT(gtk_button_new_from_icon_name(ZSTR_VAL(icon_name)));
  wrap(obj, return_value);
}

/**
 * static Gtk4\GtkButton::new_with_label(string $label): GtkButton
 *
 * Creates a `GtkButton` widget with a `GtkLabel` child.
 */
ZEND_METHOD(Gtk4_GtkButton, new_with_label) {
  zend_string *label;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(label)
  ZEND_PARSE_PARAMETERS_END();
  GObject *obj = G_OBJECT(gtk_button_new_with_label(ZSTR_VAL(label)));
  wrap(obj, return_value);
}

/**
 * static Gtk4\GtkButton::new_with_mnemonic(string $label): GtkButton
 *
 * Creates a new `GtkButton` containing a label.
 */
ZEND_METHOD(Gtk4_GtkButton, new_with_mnemonic) {
  zend_string *label;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(label)
  ZEND_PARSE_PARAMETERS_END();
  GObject *obj = G_OBJECT(gtk_button_new_with_mnemonic(ZSTR_VAL(label)));
  wrap(obj, return_value);
}

/**
 * Gtk4\GtkButton::get_can_shrink(): bool
 *
 * Retrieves whether the button can be smaller than the natural size of its contents.
 */
ZEND_METHOD(Gtk4_GtkButton, get_can_shrink) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  RETURN_BOOL(gtk_button_get_can_shrink(self));
}

/**
 * Gtk4\GtkButton::get_child(): ?GtkWidget
 *
 * Gets the child widget of $button.
 */
ZEND_METHOD(Gtk4_GtkButton, get_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  GtkWidget *result = gtk_button_get_child(self);
  wrap(result != nullptr ? G_OBJECT(result) : nullptr, return_value);
}

/**
 * Gtk4\GtkButton::get_has_frame(): bool
 *
 * Returns whether the button has a frame.
 */
ZEND_METHOD(Gtk4_GtkButton, get_has_frame) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  RETURN_BOOL(gtk_button_get_has_frame(self));
}

/**
 * Gtk4\GtkButton::get_icon_name(): ?string
 *
 * Returns the icon name of the button.
 */
ZEND_METHOD(Gtk4_GtkButton, get_icon_name) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  PHPGTK_RETURN_STRING_OR_NULL(gtk_button_get_icon_name(self));
}

/**
 * Gtk4\GtkButton::get_label(): ?string
 *
 * Fetches the text from the label of the button.
 */
ZEND_METHOD(Gtk4_GtkButton, get_label) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  PHPGTK_RETURN_STRING_OR_NULL(gtk_button_get_label(self));
}

/**
 * Gtk4\GtkButton::get_use_underline(): bool
 *
 * gets whether underlines are interpreted as mnemonics.
 */
ZEND_METHOD(Gtk4_GtkButton, get_use_underline) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  RETURN_BOOL(gtk_button_get_use_underline(self));
}

/**
 * Gtk4\GtkButton::set_can_shrink(bool $can_shrink): void
 *
 * Sets whether the button size can be smaller than the natural size of its contents.
 */
ZEND_METHOD(Gtk4_GtkButton, set_can_shrink) {
  bool can_shrink;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(can_shrink)
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  gtk_button_set_can_shrink(self, can_shrink);
}

/**
 * Gtk4\GtkButton::set_child(?GtkWidget $child): void
 *
 * Sets the child widget of $button.
 */
ZEND_METHOD(Gtk4_GtkButton, set_child) {
  zval *child = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(child, class_for_gtype(GTK_TYPE_WIDGET))
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  GObject *child_o = nullptr;
  if (child != nullptr) {
    child_o = unwrap(child, GTK_TYPE_WIDGET);
    if (child_o == nullptr) RETURN_THROWS();
  }
  gtk_button_set_child(self, child_o != nullptr ? GTK_WIDGET(child_o) : nullptr);
}

/**
 * Gtk4\GtkButton::set_has_frame(bool $has_frame): void
 *
 * Sets the style of the button.
 */
ZEND_METHOD(Gtk4_GtkButton, set_has_frame) {
  bool has_frame;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(has_frame)
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  gtk_button_set_has_frame(self, has_frame);
}

/**
 * Gtk4\GtkButton::set_icon_name(string $icon_name): void
 *
 * Adds a `GtkImage` with the given icon name as a child.
 */
ZEND_METHOD(Gtk4_GtkButton, set_icon_name) {
  zend_string *icon_name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(icon_name)
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  gtk_button_set_icon_name(self, ZSTR_VAL(icon_name));
}

/**
 * Gtk4\GtkButton::set_label(string $label): void
 *
 * Sets the text of the label of the button to $label.
 */
ZEND_METHOD(Gtk4_GtkButton, set_label) {
  zend_string *label;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(label)
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  gtk_button_set_label(self, ZSTR_VAL(label));
}

/**
 * Gtk4\GtkButton::set_use_underline(bool $use_underline): void
 *
 * Sets whether to use underlines as mnemonics.
 */
ZEND_METHOD(Gtk4_GtkButton, set_use_underline) {
  bool use_underline;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(use_underline)
  ZEND_PARSE_PARAMETERS_END();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  gtk_button_set_use_underline(self, use_underline);
}

// vfunc thunks and installers: file-local, installed by class_init of a PHP subtype
namespace {

// vfunc thunk: GTK_BUTTON_CLASS->activate -> $this->vfunc_activate() on a PHP subclass
void vfunc_thunk_activate(GtkButton *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_activate", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->activate != nullptr) native->activate(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkButton::vfunc_activate");
}

// vfunc installer: GTK_BUTTON_CLASS->activate (called from class_init of a PHP subtype)
void vfunc_install_activate(gpointer klass) {
  GTK_BUTTON_CLASS(klass)->activate = vfunc_thunk_activate;
}

// vfunc thunk: GTK_BUTTON_CLASS->clicked -> $this->vfunc_clicked() on a PHP subclass
void vfunc_thunk_clicked(GtkButton *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_clicked", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->clicked != nullptr) native->clicked(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkButton::vfunc_clicked");
}

// vfunc installer: GTK_BUTTON_CLASS->clicked (called from class_init of a PHP subtype)
void vfunc_install_clicked(gpointer klass) {
  GTK_BUTTON_CLASS(klass)->clicked = vfunc_thunk_clicked;
}

}  // namespace

/**
 * Gtk4\GtkButton::vfunc_activate(): void
 *
 * Native `activate` (ButtonClass.activate): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_activate()` from an override. Signal that causes the button to animate press then
 * release. Applications should never connect to this signal, but use the $clicked signal.
 */
ZEND_METHOD(Gtk4_GtkButton, vfunc_activate) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkButton::vfunc_activate(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->activate == nullptr) {
    return;
  }
  klass->activate(self);
}

/**
 * Gtk4\GtkButton::vfunc_clicked(): void
 *
 * Native `clicked` (ButtonClass.clicked): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_clicked()` from an override. Signal emitted when the button has been activated
 * (pressed and released).
 */
ZEND_METHOD(Gtk4_GtkButton, vfunc_clicked) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkButton *self = PHPGTK_SELF(GtkButton, GTK_TYPE_BUTTON);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(spl_ce_LogicException, 0,
                            "GtkButton::vfunc_clicked(): for parent:: chaining from a PHP subclass "
                            "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->clicked == nullptr) {
    return;
  }
  klass->clicked(self);
}

// MINIT: the vfunc thunks of GtkButton (core/subtype.h).
void register_vfuncs_GtkButton() {
  register_vfunc(GTK_TYPE_BUTTON, "activate", vfunc_install_activate);
  register_vfunc(GTK_TYPE_BUTTON, "clicked", vfunc_install_clicked);
}
