// GENERATED by gen/gir.php from Gtk.CheckButton - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkCheckButton
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"
#include "core/error.h"

using namespace phpgtk;

/**
 * Gtk4\GtkCheckButton::__construct()
 *
 * Creates a new `GtkCheckButton`.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_check_button_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * static Gtk4\GtkCheckButton::new_with_label(?string $label = null): GtkCheckButton
 *
 * Creates a new `GtkCheckButton` with the given text.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, new_with_label) {
  zend_string *label = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_STR_OR_NULL(label)
  ZEND_PARSE_PARAMETERS_END();
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *obj =
      G_OBJECT(gtk_check_button_new_with_label(label != nullptr ? ZSTR_VAL(label) : nullptr));
  wrap(obj, return_value);
}

/**
 * static Gtk4\GtkCheckButton::new_with_mnemonic(?string $label = null): GtkCheckButton
 *
 * Creates a new `GtkCheckButton` with the given text and a mnemonic.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, new_with_mnemonic) {
  zend_string *label = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_STR_OR_NULL(label)
  ZEND_PARSE_PARAMETERS_END();
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *obj =
      G_OBJECT(gtk_check_button_new_with_mnemonic(label != nullptr ? ZSTR_VAL(label) : nullptr));
  wrap(obj, return_value);
}

/**
 * Gtk4\GtkCheckButton::get_active(): bool
 *
 * Returns whether the check button is active.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, get_active) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  RETURN_BOOL(gtk_check_button_get_active(self));
}

/**
 * Gtk4\GtkCheckButton::get_child(): ?GtkWidget
 *
 * Gets the child widget of $button or `NULL` if [property@CheckButton:label] is set.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, get_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  GtkWidget *phpgtk_ret = gtk_check_button_get_child(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkCheckButton::get_inconsistent(): bool
 *
 * Returns whether the check button is in an inconsistent state.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, get_inconsistent) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  RETURN_BOOL(gtk_check_button_get_inconsistent(self));
}

/**
 * Gtk4\GtkCheckButton::get_label(): ?string
 *
 * Returns the label of the check button or `NULL` if [property@CheckButton:child] is set.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, get_label) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  PHPGTK_RETURN_STRING_OR_NULL(gtk_check_button_get_label(self));
}

/**
 * Gtk4\GtkCheckButton::get_use_underline(): bool
 *
 * Returns whether underlines in the label indicate mnemonics.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, get_use_underline) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  RETURN_BOOL(gtk_check_button_get_use_underline(self));
}

/**
 * Gtk4\GtkCheckButton::set_active(bool $setting): void
 *
 * Changes the check buttons active state.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_active) {
  bool setting;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(setting)
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  gtk_check_button_set_active(self, setting);
}

/**
 * Gtk4\GtkCheckButton::set_child(?GtkWidget $child): void
 *
 * Sets the child widget of $button.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_child) {
  zval *child = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(child, class_for_gtype(GTK_TYPE_WIDGET))
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  GObject *child_o = nullptr;
  if (child != nullptr) {
    child_o = unwrap(child, GTK_TYPE_WIDGET);
    if (child_o == nullptr) RETURN_THROWS();
  }
  gtk_check_button_set_child(self, child_o != nullptr ? GTK_WIDGET(child_o) : nullptr);
}

/**
 * Gtk4\GtkCheckButton::set_group(?GtkCheckButton $group): void
 *
 * Adds $self to the group of $group.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_group) {
  zval *group = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(group, class_for_gtype(GTK_TYPE_CHECK_BUTTON))
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  GObject *group_o = nullptr;
  if (group != nullptr) {
    group_o = unwrap(group, GTK_TYPE_CHECK_BUTTON);
    if (group_o == nullptr) RETURN_THROWS();
  }
  gtk_check_button_set_group(self, group_o != nullptr ? GTK_CHECK_BUTTON(group_o) : nullptr);
}

/**
 * Gtk4\GtkCheckButton::set_inconsistent(bool $inconsistent): void
 *
 * Sets the `GtkCheckButton` to inconsistent state.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_inconsistent) {
  bool inconsistent;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(inconsistent)
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  gtk_check_button_set_inconsistent(self, inconsistent);
}

/**
 * Gtk4\GtkCheckButton::set_label(?string $label): void
 *
 * Sets the text of $self.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_label) {
  zend_string *label = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR_OR_NULL(label)
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  if (label != nullptr && !phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  gtk_check_button_set_label(self, label != nullptr ? ZSTR_VAL(label) : nullptr);
}

/**
 * Gtk4\GtkCheckButton::set_use_underline(bool $setting): void
 *
 * Sets whether underlines in the label indicate mnemonics.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, set_use_underline) {
  bool setting;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(setting)
  ZEND_PARSE_PARAMETERS_END();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  gtk_check_button_set_use_underline(self, setting);
}

// vfunc thunks and installers: file-local, installed by class_init of a PHP subtype
namespace {

// vfunc thunk: GTK_CHECK_BUTTON_CLASS->activate -> $this->vfunc_activate() on a PHP subclass
void vfunc_thunk_activate(GtkCheckButton *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_activate", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_CHECK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->activate != nullptr) native->activate(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkCheckButton::vfunc_activate");
}

// vfunc installer: GTK_CHECK_BUTTON_CLASS->activate (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_activate(gpointer klass) {
  GTK_CHECK_BUTTON_CLASS(klass)->activate = vfunc_thunk_activate;
}

// vfunc thunk: GTK_CHECK_BUTTON_CLASS->toggled -> $this->vfunc_toggled() on a PHP subclass
void vfunc_thunk_toggled(GtkCheckButton *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_toggled", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_CHECK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->toggled != nullptr) native->toggled(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkCheckButton::vfunc_toggled");
}

// vfunc installer: GTK_CHECK_BUTTON_CLASS->toggled (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_toggled(gpointer klass) {
  GTK_CHECK_BUTTON_CLASS(klass)->toggled = vfunc_thunk_toggled;
}

}  // namespace

/**
 * Gtk4\GtkCheckButton::vfunc_activate(): void
 *
 * Native `activate` (CheckButtonClass.activate): the GTK implementation below any PHP subclass,
 * for `parent::vfunc_activate()` from an override.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, vfunc_activate) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkCheckButton::vfunc_activate(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_CHECK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->activate == nullptr) {
    return;
  }
  klass->activate(self);
}

/**
 * Gtk4\GtkCheckButton::vfunc_toggled(): void
 *
 * Native `toggled` (CheckButtonClass.toggled): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_toggled()` from an override.
 */
ZEND_METHOD(Gtk4_GtkCheckButton, vfunc_toggled) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkCheckButton *self = PHPGTK_SELF(GtkCheckButton, GTK_TYPE_CHECK_BUTTON);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkCheckButton::vfunc_toggled(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_CHECK_BUTTON_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->toggled == nullptr) {
    return;
  }
  klass->toggled(self);
}

// MINIT: the vfunc thunks of GtkCheckButton (core/subtype.h).
void register_vfuncs_GtkCheckButton() {
  register_vfunc(GTK_TYPE_CHECK_BUTTON, "activate", vfunc_install_activate);
  register_vfunc(GTK_TYPE_CHECK_BUTTON, "toggled", vfunc_install_toggled);
}
