// GENERATED by gen/gir.php from Gtk.DropTargetAsync - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkDropTargetAsync
#include "php_gtk4.h"
#include "core/object.h"
#include "core/boxed.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkDropTargetAsync::__construct(?GdkContentFormats $formats, int $actions)
 *
 * Creates a new `GtkDropTargetAsync` object.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, __construct) {
  zval *formats = nullptr;
  zend_long actions;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(formats, boxed_class_for_type(GDK_TYPE_CONTENT_FORMATS)->ce)
  Z_PARAM_LONG(actions)
  ZEND_PARSE_PARAMETERS_END();
  gpointer formats_b = nullptr;
  if (formats != nullptr) {
    formats_b = unwrap_boxed(formats, GDK_TYPE_CONTENT_FORMATS);
    if (formats_b == nullptr) RETURN_THROWS();
  }
  if (formats_b != nullptr) formats_b = g_boxed_copy(GDK_TYPE_CONTENT_FORMATS, formats_b);
  if (!phpgtk::check_flags(GDK_TYPE_DRAG_ACTION, actions, 2)) RETURN_THROWS();
  GObject *obj = subtype_new(ZEND_THIS, "formats", static_cast<GdkContentFormats *>(formats_b),
                             "actions", static_cast<GdkDragAction>(actions), nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_drop_target_async_new(static_cast<GdkContentFormats *>(formats_b),
                                             static_cast<GdkDragAction>(actions)));
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkDropTargetAsync::get_actions(): int
 *
 * Gets the actions that this drop target supports.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, get_actions) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDropTargetAsync *self = PHPGTK_SELF(GtkDropTargetAsync, GTK_TYPE_DROP_TARGET_ASYNC);
  RETURN_LONG(static_cast<zend_long>(gtk_drop_target_async_get_actions(self)));
}

/**
 * Gtk4\GtkDropTargetAsync::reject_drop(GdkDrop $drop): void
 *
 * Sets the $drop as not accepted on this drag site.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, reject_drop) {
  zval *drop;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(drop, class_for_gtype(GDK_TYPE_DROP))
  ZEND_PARSE_PARAMETERS_END();
  GtkDropTargetAsync *self = PHPGTK_SELF(GtkDropTargetAsync, GTK_TYPE_DROP_TARGET_ASYNC);
  GObject *drop_o = unwrap(drop, GDK_TYPE_DROP);
  if (drop_o == nullptr) RETURN_THROWS();
  gtk_drop_target_async_reject_drop(self, GDK_DROP(drop_o));
}

/**
 * Gtk4\GtkDropTargetAsync::set_actions(int $actions): void
 *
 * Sets the actions that this drop target supports.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, set_actions) {
  zend_long actions;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(actions)
  ZEND_PARSE_PARAMETERS_END();
  GtkDropTargetAsync *self = PHPGTK_SELF(GtkDropTargetAsync, GTK_TYPE_DROP_TARGET_ASYNC);
  if (!phpgtk::check_flags(GDK_TYPE_DRAG_ACTION, actions, 1)) RETURN_THROWS();
  gtk_drop_target_async_set_actions(self, static_cast<GdkDragAction>(actions));
}

/**
 * Gtk4\GtkDropTargetAsync::set_formats(?GdkContentFormats $formats): void
 *
 * Sets the data formats that this drop target will accept.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, set_formats) {
  zval *formats = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(formats, boxed_class_for_type(GDK_TYPE_CONTENT_FORMATS)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkDropTargetAsync *self = PHPGTK_SELF(GtkDropTargetAsync, GTK_TYPE_DROP_TARGET_ASYNC);
  gpointer formats_b = nullptr;
  if (formats != nullptr) {
    formats_b = unwrap_boxed(formats, GDK_TYPE_CONTENT_FORMATS);
    if (formats_b == nullptr) RETURN_THROWS();
  }
  gtk_drop_target_async_set_formats(self, static_cast<GdkContentFormats *>(formats_b));
}

/**
 * public function get_formats(): ?GdkContentFormats
 * The formats this target accepts, or null when it accepts everything.
 *
 * GTK's GIR annotates this `transfer full`, but `gtk_drop_target_async_get_formats()` returns
 * `self->formats` borrowed (its sibling `gtk_drop_target_get_formats()` is annotated correctly).
 * Taking the annotation at its word unrefs GTK's own formats: the first call freed them and the
 * second read freed memory. So this one does not free what it wrapped.
 */
ZEND_METHOD(Gtk4_GtkDropTargetAsync, get_formats) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDropTargetAsync *self = PHPGTK_SELF(GtkDropTargetAsync, GTK_TYPE_DROP_TARGET_ASYNC);
  wrap_boxed(GDK_TYPE_CONTENT_FORMATS, gtk_drop_target_async_get_formats(self), return_value);
}
