// GENERATED by gen/gir.php from Gtk.DragSource - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkDragSource
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkDragSource::__construct()
 *
 * Creates a new `GtkDragSource` object.
 */
ZEND_METHOD(Gtk4_GtkDragSource, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_drag_source_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkDragSource::drag_cancel(): void
 *
 * Cancels a currently ongoing drag operation.
 */
ZEND_METHOD(Gtk4_GtkDragSource, drag_cancel) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  gtk_drag_source_drag_cancel(self);
}

/**
 * Gtk4\GtkDragSource::get_actions(): int
 *
 * Gets the actions that are currently set on the `GtkDragSource`.
 */
ZEND_METHOD(Gtk4_GtkDragSource, get_actions) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  RETURN_LONG(static_cast<zend_long>(gtk_drag_source_get_actions(self)));
}

/**
 * Gtk4\GtkDragSource::get_content(): ?GdkContentProvider
 *
 * Gets the current content provider of a `GtkDragSource`.
 */
ZEND_METHOD(Gtk4_GtkDragSource, get_content) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  GdkContentProvider *phpgtk_ret = gtk_drag_source_get_content(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkDragSource::get_drag(): ?GdkDrag
 *
 * Returns the underlying `GdkDrag` object for an ongoing drag.
 */
ZEND_METHOD(Gtk4_GtkDragSource, get_drag) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  GdkDrag *phpgtk_ret = gtk_drag_source_get_drag(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkDragSource::set_actions(int $actions): void
 *
 * Sets the actions on the `GtkDragSource`.
 */
ZEND_METHOD(Gtk4_GtkDragSource, set_actions) {
  zend_long actions;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(actions)
  ZEND_PARSE_PARAMETERS_END();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  if (!phpgtk::check_flags(GDK_TYPE_DRAG_ACTION, actions, 1)) RETURN_THROWS();
  gtk_drag_source_set_actions(self, static_cast<GdkDragAction>(actions));
}

/**
 * Gtk4\GtkDragSource::set_content(?GdkContentProvider $content): void
 *
 * Sets a content provider on a `GtkDragSource`.
 */
ZEND_METHOD(Gtk4_GtkDragSource, set_content) {
  zval *content = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(content, class_for_gtype(GDK_TYPE_CONTENT_PROVIDER))
  ZEND_PARSE_PARAMETERS_END();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  GObject *content_o = nullptr;
  if (content != nullptr) {
    content_o = unwrap(content, GDK_TYPE_CONTENT_PROVIDER);
    if (content_o == nullptr) RETURN_THROWS();
  }
  gtk_drag_source_set_content(self,
                              content_o != nullptr ? GDK_CONTENT_PROVIDER(content_o) : nullptr);
}

/**
 * Gtk4\GtkDragSource::set_icon(?GdkPaintable $paintable, int $hot_x, int $hot_y): void
 *
 * Sets a paintable to use as icon during DND operations.
 */
ZEND_METHOD(Gtk4_GtkDragSource, set_icon) {
  zval *paintable = nullptr;
  zend_long hot_x;
  zend_long hot_y;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(paintable, class_for_gtype(GDK_TYPE_PAINTABLE))
  Z_PARAM_LONG(hot_x)
  Z_PARAM_LONG(hot_y)
  ZEND_PARSE_PARAMETERS_END();
  GtkDragSource *self = PHPGTK_SELF(GtkDragSource, GTK_TYPE_DRAG_SOURCE);
  GObject *paintable_o = nullptr;
  if (paintable != nullptr) {
    paintable_o = unwrap(paintable, GDK_TYPE_PAINTABLE);
    if (paintable_o == nullptr) RETURN_THROWS();
  }
  if (!phpgtk::check_range<int>(hot_x, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(hot_y, 3)) RETURN_THROWS();
  gtk_drag_source_set_icon(self, paintable_o != nullptr ? GDK_PAINTABLE(paintable_o) : nullptr,
                           static_cast<int>(hot_x), static_cast<int>(hot_y));
}
