// GENERATED by gen/gir.php from Gtk.FixedLayoutChild - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkFixedLayoutChild
#include "php_gtk4.h"
#include "core/object.h"

using namespace phpgtk;

/**
 * Gtk4\GtkFixedLayoutChild::__construct()
 *
 * GtkFixedLayoutChild has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_GtkFixedLayoutChild, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}
