// GENERATED by gen/gir.php from Gtk.ListBoxRow - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkListBoxRow
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"
#include "core/error.h"

using namespace phpgtk;

/**
 * Gtk4\GtkListBoxRow::__construct()
 *
 * Creates a new `GtkListBoxRow`.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_list_box_row_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkListBoxRow::changed(): void
 *
 * Marks $row as changed, causing any state that depends on this to be updated.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, changed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  gtk_list_box_row_changed(self);
}

/**
 * Gtk4\GtkListBoxRow::get_activatable(): bool
 *
 * Gets whether the row is activatable.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, get_activatable) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  RETURN_BOOL(gtk_list_box_row_get_activatable(self));
}

/**
 * Gtk4\GtkListBoxRow::get_child(): ?GtkWidget
 *
 * Gets the child widget of $row.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, get_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  GtkWidget *phpgtk_ret = gtk_list_box_row_get_child(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkListBoxRow::get_header(): ?GtkWidget
 *
 * Returns the current header of the $row.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, get_header) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  GtkWidget *phpgtk_ret = gtk_list_box_row_get_header(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkListBoxRow::get_index(): int
 *
 * Gets the current index of the $row in its `GtkListBox` container.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, get_index) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  RETURN_LONG(static_cast<zend_long>(gtk_list_box_row_get_index(self)));
}

/**
 * Gtk4\GtkListBoxRow::get_selectable(): bool
 *
 * Gets whether the row can be selected.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, get_selectable) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  RETURN_BOOL(gtk_list_box_row_get_selectable(self));
}

/**
 * Gtk4\GtkListBoxRow::is_selected(): bool
 *
 * Returns whether the child is currently selected in its `GtkListBox` container.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, is_selected) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  RETURN_BOOL(gtk_list_box_row_is_selected(self));
}

/**
 * Gtk4\GtkListBoxRow::set_activatable(bool $activatable): void
 *
 * Set whether the row is activatable.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, set_activatable) {
  bool activatable;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(activatable)
  ZEND_PARSE_PARAMETERS_END();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  gtk_list_box_row_set_activatable(self, activatable);
}

/**
 * Gtk4\GtkListBoxRow::set_child(?GtkWidget $child): void
 *
 * Sets the child widget of $self.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, set_child) {
  zval *child = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(child, class_for_gtype(GTK_TYPE_WIDGET))
  ZEND_PARSE_PARAMETERS_END();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  GObject *child_o = nullptr;
  if (child != nullptr) {
    child_o = unwrap(child, GTK_TYPE_WIDGET);
    if (child_o == nullptr) RETURN_THROWS();
  }
  gtk_list_box_row_set_child(self, child_o != nullptr ? GTK_WIDGET(child_o) : nullptr);
}

/**
 * Gtk4\GtkListBoxRow::set_header(?GtkWidget $header): void
 *
 * Sets the current header of the $row.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, set_header) {
  zval *header = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(header, class_for_gtype(GTK_TYPE_WIDGET))
  ZEND_PARSE_PARAMETERS_END();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  GObject *header_o = nullptr;
  if (header != nullptr) {
    header_o = unwrap(header, GTK_TYPE_WIDGET);
    if (header_o == nullptr) RETURN_THROWS();
  }
  gtk_list_box_row_set_header(self, header_o != nullptr ? GTK_WIDGET(header_o) : nullptr);
}

/**
 * Gtk4\GtkListBoxRow::set_selectable(bool $selectable): void
 *
 * Set whether the row can be selected.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, set_selectable) {
  bool selectable;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(selectable)
  ZEND_PARSE_PARAMETERS_END();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  gtk_list_box_row_set_selectable(self, selectable);
}

// vfunc thunks and installers: file-local, installed by class_init of a PHP subtype
namespace {

// vfunc thunk: GTK_LIST_BOX_ROW_CLASS->activate -> $this->vfunc_activate() on a PHP subclass
void vfunc_thunk_activate(GtkListBoxRow *self) {
  zval zself;
  zend_function *fn = subtype_vfunc(G_OBJECT(self), "vfunc_activate", &zself);
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown)
    auto *native = GTK_LIST_BOX_ROW_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->activate != nullptr) native->activate(self);
    return;
  }
  // PHP cannot run with an exception pending, and the default is no answer to
  // give GTK: park it for the call, as Zend does around a __destruct().
  zend_exception_save();
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkListBoxRow::vfunc_activate");
  zend_exception_restore();  // the parked one, previous of whatever this threw
}

// vfunc installer: GTK_LIST_BOX_ROW_CLASS->activate (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_activate(gpointer klass) {
  GTK_LIST_BOX_ROW_CLASS(klass)->activate = vfunc_thunk_activate;
}

}  // namespace

/**
 * Gtk4\GtkListBoxRow::vfunc_activate(): void
 *
 * Native `activate` (ListBoxRowClass.activate): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_activate()` from an override.
 */
ZEND_METHOD(Gtk4_GtkListBoxRow, vfunc_activate) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkListBoxRow *self = PHPGTK_SELF(GtkListBoxRow, GTK_TYPE_LIST_BOX_ROW);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkListBoxRow::vfunc_activate(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_LIST_BOX_ROW_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->activate == nullptr) {
    return;
  }
  klass->activate(self);
}

// MINIT: the vfunc thunks of GtkListBoxRow (core/subtype.h).
void register_vfuncs_GtkListBoxRow() {
  register_vfunc(GTK_TYPE_LIST_BOX_ROW, "activate", vfunc_install_activate);
}
