// GENERATED by gen/gir.php from Gtk.Picture - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkPicture
#include "php_gtk4.h"
#include "core/object.h"
#include "core/enums.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkPicture::__construct()
 *
 * Creates a new empty `GtkPicture` widget.
 */
ZEND_METHOD(Gtk4_GtkPicture, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_picture_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * static Gtk4\GtkPicture::new_for_filename(?string $filename = null): GtkPicture
 *
 * Creates a new `GtkPicture` displaying the file $filename.
 */
ZEND_METHOD(Gtk4_GtkPicture, new_for_filename) {
  zend_string *filename = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_PATH_STR_OR_NULL(filename)
  ZEND_PARSE_PARAMETERS_END();
  GObject *obj =
      G_OBJECT(gtk_picture_new_for_filename(filename != nullptr ? ZSTR_VAL(filename) : nullptr));
  wrap(obj, return_value);
}

/**
 * static Gtk4\GtkPicture::new_for_paintable(?GdkPaintable $paintable = null): GtkPicture
 *
 * Creates a new `GtkPicture` displaying $paintable.
 */
ZEND_METHOD(Gtk4_GtkPicture, new_for_paintable) {
  zval *paintable = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(paintable, class_for_gtype(GDK_TYPE_PAINTABLE))
  ZEND_PARSE_PARAMETERS_END();
  GObject *paintable_o = nullptr;
  if (paintable != nullptr) {
    paintable_o = unwrap(paintable, GDK_TYPE_PAINTABLE);
    if (paintable_o == nullptr) RETURN_THROWS();
  }
  GObject *obj = G_OBJECT(
      gtk_picture_new_for_paintable(paintable_o != nullptr ? GDK_PAINTABLE(paintable_o) : nullptr));
  wrap(obj, return_value);
}

/**
 * static Gtk4\GtkPicture::new_for_resource(?string $resource_path = null): GtkPicture
 *
 * Creates a new `GtkPicture` displaying the resource at $resource_path.
 */
ZEND_METHOD(Gtk4_GtkPicture, new_for_resource) {
  zend_string *resource_path = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_STR_OR_NULL(resource_path)
  ZEND_PARSE_PARAMETERS_END();
  if (resource_path != nullptr && !phpgtk::check_utf8(resource_path, 1)) RETURN_THROWS();
  GObject *obj = G_OBJECT(
      gtk_picture_new_for_resource(resource_path != nullptr ? ZSTR_VAL(resource_path) : nullptr));
  wrap(obj, return_value);
}

/**
 * Gtk4\GtkPicture::get_alternative_text(): ?string
 *
 * Gets the alternative textual description of the picture.
 */
ZEND_METHOD(Gtk4_GtkPicture, get_alternative_text) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  PHPGTK_RETURN_STRING_OR_NULL(gtk_picture_get_alternative_text(self));
}

/**
 * Gtk4\GtkPicture::get_can_shrink(): bool
 *
 * Returns whether the `GtkPicture` respects its contents size.
 */
ZEND_METHOD(Gtk4_GtkPicture, get_can_shrink) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  RETURN_BOOL(gtk_picture_get_can_shrink(self));
}

/**
 * Gtk4\GtkPicture::get_content_fit(): GtkContentFit
 *
 * Returns the fit mode for the content of the `GtkPicture`.
 */
ZEND_METHOD(Gtk4_GtkPicture, get_content_fit) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  enum_to_php(GTK_TYPE_CONTENT_FIT, gtk_picture_get_content_fit(self), return_value);
}

/**
 * Gtk4\GtkPicture::get_paintable(): ?GdkPaintable
 *
 * Gets the `GdkPaintable` being displayed by the `GtkPicture`.
 */
ZEND_METHOD(Gtk4_GtkPicture, get_paintable) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  GdkPaintable *result = gtk_picture_get_paintable(self);
  wrap(result != nullptr ? G_OBJECT(result) : nullptr, return_value);
}

/**
 * Gtk4\GtkPicture::set_alternative_text(?string $alternative_text): void
 *
 * Sets an alternative textual description for the picture contents.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_alternative_text) {
  zend_string *alternative_text = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR_OR_NULL(alternative_text)
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  if (alternative_text != nullptr && !phpgtk::check_utf8(alternative_text, 1)) RETURN_THROWS();
  gtk_picture_set_alternative_text(
      self, alternative_text != nullptr ? ZSTR_VAL(alternative_text) : nullptr);
}

/**
 * Gtk4\GtkPicture::set_can_shrink(bool $can_shrink): void
 *
 * If set to `true`, the $self can be made smaller than its contents.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_can_shrink) {
  bool can_shrink;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(can_shrink)
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  gtk_picture_set_can_shrink(self, can_shrink);
}

/**
 * Gtk4\GtkPicture::set_content_fit(GtkContentFit $content_fit): void
 *
 * Sets how the content should be resized to fit the `GtkPicture`.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_content_fit) {
  zval *content_fit;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(content_fit, enum_class_for_type(GTK_TYPE_CONTENT_FIT))
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  gint content_fit_v = 0;
  if (!enum_from_php(content_fit, GTK_TYPE_CONTENT_FIT, &content_fit_v)) RETURN_THROWS();
  gtk_picture_set_content_fit(self, static_cast<GtkContentFit>(content_fit_v));
}

/**
 * Gtk4\GtkPicture::set_filename(?string $filename): void
 *
 * Makes $self load and display the given $filename.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_filename) {
  zend_string *filename = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_PATH_STR_OR_NULL(filename)
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  gtk_picture_set_filename(self, filename != nullptr ? ZSTR_VAL(filename) : nullptr);
}

/**
 * Gtk4\GtkPicture::set_paintable(?GdkPaintable $paintable): void
 *
 * Makes $self display the given $paintable.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_paintable) {
  zval *paintable = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(paintable, class_for_gtype(GDK_TYPE_PAINTABLE))
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  GObject *paintable_o = nullptr;
  if (paintable != nullptr) {
    paintable_o = unwrap(paintable, GDK_TYPE_PAINTABLE);
    if (paintable_o == nullptr) RETURN_THROWS();
  }
  gtk_picture_set_paintable(self, paintable_o != nullptr ? GDK_PAINTABLE(paintable_o) : nullptr);
}

/**
 * Gtk4\GtkPicture::set_resource(?string $resource_path): void
 *
 * Makes $self load and display the resource at the given $resource_path.
 */
ZEND_METHOD(Gtk4_GtkPicture, set_resource) {
  zend_string *resource_path = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR_OR_NULL(resource_path)
  ZEND_PARSE_PARAMETERS_END();
  GtkPicture *self = PHPGTK_SELF(GtkPicture, GTK_TYPE_PICTURE);
  if (resource_path != nullptr && !phpgtk::check_utf8(resource_path, 1)) RETURN_THROWS();
  gtk_picture_set_resource(self, resource_path != nullptr ? ZSTR_VAL(resource_path) : nullptr);
}
