// GENERATED by gen/gir.php from Gtk.PasswordEntry - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkPasswordEntry
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkPasswordEntry::__construct()
 *
 * Creates a `GtkPasswordEntry`.
 */
ZEND_METHOD(Gtk4_GtkPasswordEntry, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_password_entry_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkPasswordEntry::get_show_peek_icon(): bool
 *
 * Returns whether the entry is showing an icon to reveal the contents.
 */
ZEND_METHOD(Gtk4_GtkPasswordEntry, get_show_peek_icon) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkPasswordEntry *self = PHPGTK_SELF(GtkPasswordEntry, GTK_TYPE_PASSWORD_ENTRY);
  RETURN_BOOL(gtk_password_entry_get_show_peek_icon(self));
}

/**
 * Gtk4\GtkPasswordEntry::set_show_peek_icon(bool $show_peek_icon): void
 *
 * Sets whether the entry should have a clickable icon to reveal the contents.
 */
ZEND_METHOD(Gtk4_GtkPasswordEntry, set_show_peek_icon) {
  bool show_peek_icon;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(show_peek_icon)
  ZEND_PARSE_PARAMETERS_END();
  GtkPasswordEntry *self = PHPGTK_SELF(GtkPasswordEntry, GTK_TYPE_PASSWORD_ENTRY);
  gtk_password_entry_set_show_peek_icon(self, show_peek_icon);
}
