// GENERATED by gen/gir.php from Gtk.Range - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkRange
#include "php_gtk4.h"
#include "core/object.h"
#include "core/enums.h"
#include "core/boxed.h"
#include "core/subtype.h"
#include "core/error.h"
#include <array>

using namespace phpgtk;

/**
 * Gtk4\GtkRange::__construct()
 *
 * A GtkRange with default properties (GTK's own constructor is varargs-only; set the
 * properties afterwards).
 */
ZEND_METHOD(Gtk4_GtkRange, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = static_cast<GObject *>(g_object_new(GTK_TYPE_RANGE, nullptr));
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkRange::get_adjustment(): GtkAdjustment
 *
 * Get the adjustment which is the “model” object for `GtkRange`.
 */
ZEND_METHOD(Gtk4_GtkRange, get_adjustment) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  GtkAdjustment *phpgtk_ret = gtk_range_get_adjustment(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkRange::get_fill_level(): float
 *
 * Gets the current position of the fill level indicator.
 */
ZEND_METHOD(Gtk4_GtkRange, get_fill_level) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_DOUBLE(gtk_range_get_fill_level(self));
}

/**
 * Gtk4\GtkRange::get_flippable(): bool
 *
 * Gets whether the `GtkRange` respects text direction.
 */
ZEND_METHOD(Gtk4_GtkRange, get_flippable) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_BOOL(gtk_range_get_flippable(self));
}

/**
 * Gtk4\GtkRange::get_inverted(): bool
 *
 * Gets whether the range is inverted.
 */
ZEND_METHOD(Gtk4_GtkRange, get_inverted) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_BOOL(gtk_range_get_inverted(self));
}

/**
 * Gtk4\GtkRange::get_range_rect(): GdkRectangle
 *
 * This function returns the area that contains the range’s trough, in coordinates relative to
 * $range's origin.
 */
ZEND_METHOD(Gtk4_GtkRange, get_range_rect) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  GdkRectangle range_rect{};
  gtk_range_get_range_rect(self, &range_rect);
  wrap_boxed(GDK_TYPE_RECTANGLE, &range_rect, return_value);
}

/**
 * Gtk4\GtkRange::get_restrict_to_fill_level(): bool
 *
 * Gets whether the range is restricted to the fill level.
 */
ZEND_METHOD(Gtk4_GtkRange, get_restrict_to_fill_level) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_BOOL(gtk_range_get_restrict_to_fill_level(self));
}

/**
 * Gtk4\GtkRange::get_round_digits(): int
 *
 * Gets the number of digits to round the value to when it changes.
 */
ZEND_METHOD(Gtk4_GtkRange, get_round_digits) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_LONG(static_cast<zend_long>(gtk_range_get_round_digits(self)));
}

/**
 * Gtk4\GtkRange::get_show_fill_level(): bool
 *
 * Gets whether the range displays the fill level graphically.
 */
ZEND_METHOD(Gtk4_GtkRange, get_show_fill_level) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_BOOL(gtk_range_get_show_fill_level(self));
}

/**
 * Gtk4\GtkRange::get_slider_range(): array
 *
 * This function returns sliders range along the long dimension, in widget->window coordinates.
 */
ZEND_METHOD(Gtk4_GtkRange, get_slider_range) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  int slider_start = 0;
  int slider_end = 0;
  gtk_range_get_slider_range(self, &slider_start, &slider_end);
  array_init_size(return_value, 2);
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(slider_start));
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    ZVAL_LONG(&item, static_cast<zend_long>(slider_end));
    add_next_index_zval(return_value, &item);
  }
}

/**
 * Gtk4\GtkRange::get_slider_size_fixed(): bool
 *
 * This function is useful mainly for `GtkRange` subclasses.
 */
ZEND_METHOD(Gtk4_GtkRange, get_slider_size_fixed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_BOOL(gtk_range_get_slider_size_fixed(self));
}

/**
 * Gtk4\GtkRange::get_value(): float
 *
 * Gets the current value of the range.
 */
ZEND_METHOD(Gtk4_GtkRange, get_value) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  RETURN_DOUBLE(gtk_range_get_value(self));
}

/**
 * Gtk4\GtkRange::set_adjustment(GtkAdjustment $adjustment): void
 *
 * Sets the adjustment to be used as the “model” object for the `GtkRange`
 */
ZEND_METHOD(Gtk4_GtkRange, set_adjustment) {
  zval *adjustment;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(adjustment, class_for_gtype(GTK_TYPE_ADJUSTMENT))
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  GObject *adjustment_o = unwrap(adjustment, GTK_TYPE_ADJUSTMENT);
  if (adjustment_o == nullptr) RETURN_THROWS();
  gtk_range_set_adjustment(self, GTK_ADJUSTMENT(adjustment_o));
}

/**
 * Gtk4\GtkRange::set_fill_level(float $fill_level): void
 *
 * Set the new position of the fill level indicator.
 */
ZEND_METHOD(Gtk4_GtkRange, set_fill_level) {
  double fill_level;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(fill_level)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_fill_level(self, fill_level);
}

/**
 * Gtk4\GtkRange::set_flippable(bool $flippable): void
 *
 * Sets whether the `GtkRange` respects text direction.
 */
ZEND_METHOD(Gtk4_GtkRange, set_flippable) {
  bool flippable;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(flippable)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_flippable(self, flippable);
}

/**
 * Gtk4\GtkRange::set_increments(float $step, float $page): void
 *
 * Sets the step and page sizes for the range.
 */
ZEND_METHOD(Gtk4_GtkRange, set_increments) {
  double step;
  double page;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_DOUBLE(step)
  Z_PARAM_DOUBLE(page)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_increments(self, step, page);
}

/**
 * Gtk4\GtkRange::set_inverted(bool $setting): void
 *
 * Sets whether to invert the range.
 */
ZEND_METHOD(Gtk4_GtkRange, set_inverted) {
  bool setting;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(setting)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_inverted(self, setting);
}

/**
 * Gtk4\GtkRange::set_range(float $min, float $max): void
 *
 * Sets the allowable values in the `GtkRange`.
 */
ZEND_METHOD(Gtk4_GtkRange, set_range) {
  double min;
  double max;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_DOUBLE(min)
  Z_PARAM_DOUBLE(max)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  const bool precondition_0 = min <= max;
  if (!precondition_0) {
    zend_argument_value_error(2, "must not be below $min");
    RETURN_THROWS();
  }
  gtk_range_set_range(self, min, max);
}

/**
 * Gtk4\GtkRange::set_restrict_to_fill_level(bool $restrict_to_fill_level): void
 *
 * Sets whether the slider is restricted to the fill level.
 */
ZEND_METHOD(Gtk4_GtkRange, set_restrict_to_fill_level) {
  bool restrict_to_fill_level;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(restrict_to_fill_level)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_restrict_to_fill_level(self, restrict_to_fill_level);
}

/**
 * Gtk4\GtkRange::set_round_digits(int $round_digits): void
 *
 * Sets the number of digits to round the value to when it changes.
 */
ZEND_METHOD(Gtk4_GtkRange, set_round_digits) {
  zend_long round_digits;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(round_digits)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  if (!phpgtk::check_range<int>(round_digits, 1)) RETURN_THROWS();
  gtk_range_set_round_digits(self, static_cast<int>(round_digits));
}

/**
 * Gtk4\GtkRange::set_show_fill_level(bool $show_fill_level): void
 *
 * Sets whether a graphical fill level is show on the trough.
 */
ZEND_METHOD(Gtk4_GtkRange, set_show_fill_level) {
  bool show_fill_level;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(show_fill_level)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_show_fill_level(self, show_fill_level);
}

/**
 * Gtk4\GtkRange::set_slider_size_fixed(bool $size_fixed): void
 *
 * Sets whether the range’s slider has a fixed size, or a size that depends on its adjustment’s
 * page size.
 */
ZEND_METHOD(Gtk4_GtkRange, set_slider_size_fixed) {
  bool size_fixed;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(size_fixed)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_slider_size_fixed(self, size_fixed);
}

/**
 * Gtk4\GtkRange::set_value(float $value): void
 *
 * Sets the current value of the range.
 */
ZEND_METHOD(Gtk4_GtkRange, set_value) {
  double value;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(value)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  gtk_range_set_value(self, value);
}

// vfunc thunks and installers: file-local, installed by class_init of a PHP subtype
namespace {

// vfunc thunk: GTK_RANGE_CLASS->adjust_bounds -> $this->vfunc_adjust_bounds() on a PHP subclass
void vfunc_thunk_adjust_bounds(GtkRange *self, double new_value) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_adjust_bounds", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->adjust_bounds != nullptr) native->adjust_bounds(self, new_value);
    return;
  }
  std::array<zval, 1> args{};
  zval *argv = args.data();
  ZVAL_DOUBLE(&argv[0], new_value);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 1, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkRange::vfunc_adjust_bounds");
}

// vfunc installer: GTK_RANGE_CLASS->adjust_bounds (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_adjust_bounds(gpointer klass) {
  GTK_RANGE_CLASS(klass)->adjust_bounds = vfunc_thunk_adjust_bounds;
}

// vfunc thunk: GTK_RANGE_CLASS->change_value -> $this->vfunc_change_value() on a PHP subclass
gboolean vfunc_thunk_change_value(GtkRange *self, GtkScrollType scroll, double new_value) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_change_value", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
    return native->change_value != nullptr ? native->change_value(self, scroll, new_value) : FALSE;
  }
  std::array<zval, 2> args{};
  zval *argv = args.data();
  ZVAL_LONG(&argv[0], static_cast<zend_long>(scroll));
  ZVAL_DOUBLE(&argv[1], new_value);
  zval ret;
  ZVAL_UNDEF(&ret);
  gboolean result = FALSE;
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 2, args.data());
  if (EG(exception) == nullptr && !Z_ISUNDEF(ret)) {
    result = zend_is_true(&ret) ? TRUE : FALSE;
  }
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkRange::vfunc_change_value");
  return result;
}

// vfunc installer: GTK_RANGE_CLASS->change_value (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_change_value(gpointer klass) {
  GTK_RANGE_CLASS(klass)->change_value = vfunc_thunk_change_value;
}

// vfunc thunk: GTK_RANGE_CLASS->move_slider -> $this->vfunc_move_slider() on a PHP subclass
void vfunc_thunk_move_slider(GtkRange *self, GtkScrollType scroll) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_move_slider", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->move_slider != nullptr) native->move_slider(self, scroll);
    return;
  }
  std::array<zval, 1> args{};
  zval *argv = args.data();
  ZVAL_LONG(&argv[0], static_cast<zend_long>(scroll));
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 1, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkRange::vfunc_move_slider");
}

// vfunc installer: GTK_RANGE_CLASS->move_slider (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_move_slider(gpointer klass) {
  GTK_RANGE_CLASS(klass)->move_slider = vfunc_thunk_move_slider;
}

// vfunc thunk: GTK_RANGE_CLASS->value_changed -> $this->vfunc_value_changed() on a PHP subclass
void vfunc_thunk_value_changed(GtkRange *self) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_value_changed", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->value_changed != nullptr) native->value_changed(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkRange::vfunc_value_changed");
}

// vfunc installer: GTK_RANGE_CLASS->value_changed (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_value_changed(gpointer klass) {
  GTK_RANGE_CLASS(klass)->value_changed = vfunc_thunk_value_changed;
}

}  // namespace

/**
 * Gtk4\GtkRange::vfunc_adjust_bounds(float $new_value): void
 *
 * Native `adjust_bounds` (RangeClass.adjust_bounds): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_adjust_bounds()` from an override.
 */
ZEND_METHOD(Gtk4_GtkRange, vfunc_adjust_bounds) {
  double new_value;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(new_value)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkRange::vfunc_adjust_bounds(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->adjust_bounds == nullptr) {
    return;
  }
  klass->adjust_bounds(self, new_value);
}

/**
 * Gtk4\GtkRange::vfunc_change_value(int $scroll, float $new_value): bool
 *
 * Native `change_value` (RangeClass.change_value): the GTK implementation below any PHP subclass,
 * for `parent::vfunc_change_value()` from an override.
 */
ZEND_METHOD(Gtk4_GtkRange, vfunc_change_value) {
  zend_long scroll;
  double new_value;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(scroll)
  Z_PARAM_DOUBLE(new_value)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkRange::vfunc_change_value(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->change_value == nullptr) {
    RETURN_FALSE;
  }
  if (!phpgtk::check_enum_member(GTK_TYPE_SCROLL_TYPE, scroll, 1)) RETURN_THROWS();
  RETURN_BOOL(klass->change_value(self, static_cast<GtkScrollType>(scroll), new_value));
}

/**
 * Gtk4\GtkRange::vfunc_move_slider(int $scroll): void
 *
 * Native `move_slider` (RangeClass.move_slider): the GTK implementation below any PHP subclass,
 * for `parent::vfunc_move_slider()` from an override.
 */
ZEND_METHOD(Gtk4_GtkRange, vfunc_move_slider) {
  zend_long scroll;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(scroll)
  ZEND_PARSE_PARAMETERS_END();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkRange::vfunc_move_slider(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->move_slider == nullptr) {
    return;
  }
  if (!phpgtk::check_enum_member(GTK_TYPE_SCROLL_TYPE, scroll, 1)) RETURN_THROWS();
  klass->move_slider(self, static_cast<GtkScrollType>(scroll));
}

/**
 * Gtk4\GtkRange::vfunc_value_changed(): void
 *
 * Native `value_changed` (RangeClass.value_changed): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_value_changed()` from an override.
 */
ZEND_METHOD(Gtk4_GtkRange, vfunc_value_changed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkRange *self = PHPGTK_SELF(GtkRange, GTK_TYPE_RANGE);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkRange::vfunc_value_changed(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_RANGE_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->value_changed == nullptr) {
    return;
  }
  klass->value_changed(self);
}

// MINIT: the vfunc thunks of GtkRange (core/subtype.h).
void register_vfuncs_GtkRange() {
  register_vfunc(GTK_TYPE_RANGE, "adjust_bounds", vfunc_install_adjust_bounds);
  register_vfunc(GTK_TYPE_RANGE, "change_value", vfunc_install_change_value);
  register_vfunc(GTK_TYPE_RANGE, "move_slider", vfunc_install_move_slider);
  register_vfunc(GTK_TYPE_RANGE, "value_changed", vfunc_install_value_changed);
}
