// GENERATED by gen/gir.php from Gtk.ScrollInfo - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkScrollInfo (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: coerces to the field's C type.
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\GtkScrollInfo::__construct()
 *
 * Creates a new scroll info for scrolling an element into view.
 */
ZEND_METHOD(Gtk4_GtkScrollInfo, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer obj = gtk_scroll_info_new();
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the value (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  boxed_adopt(boxed_from_zval(ZEND_THIS), GTK_TYPE_SCROLL_INFO, obj);
}

/**
 * Gtk4\GtkScrollInfo::get_enable_horizontal(): bool
 *
 * Checks if horizontal scrolling is enabled.
 */
ZEND_METHOD(Gtk4_GtkScrollInfo, get_enable_horizontal) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkScrollInfo *self = PHPGTK_BOXED_SELF(GtkScrollInfo);
  RETURN_BOOL(gtk_scroll_info_get_enable_horizontal(self));
}

/**
 * Gtk4\GtkScrollInfo::get_enable_vertical(): bool
 *
 * Checks if vertical scrolling is enabled.
 */
ZEND_METHOD(Gtk4_GtkScrollInfo, get_enable_vertical) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkScrollInfo *self = PHPGTK_BOXED_SELF(GtkScrollInfo);
  RETURN_BOOL(gtk_scroll_info_get_enable_vertical(self));
}

/**
 * Gtk4\GtkScrollInfo::set_enable_horizontal(bool $horizontal): void
 *
 * Turns horizontal scrolling on or off.
 */
ZEND_METHOD(Gtk4_GtkScrollInfo, set_enable_horizontal) {
  bool horizontal;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(horizontal)
  ZEND_PARSE_PARAMETERS_END();
  GtkScrollInfo *self = PHPGTK_BOXED_SELF(GtkScrollInfo);
  gtk_scroll_info_set_enable_horizontal(self, horizontal);
}

/**
 * Gtk4\GtkScrollInfo::set_enable_vertical(bool $vertical): void
 *
 * Turns vertical scrolling on or off.
 */
ZEND_METHOD(Gtk4_GtkScrollInfo, set_enable_vertical) {
  bool vertical;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(vertical)
  ZEND_PARSE_PARAMETERS_END();
  GtkScrollInfo *self = PHPGTK_BOXED_SELF(GtkScrollInfo);
  gtk_scroll_info_set_enable_vertical(self, vertical);
}

namespace phpgtk {
// MINIT: bind the PHP class to GTK_TYPE_SCROLL_INFO with its field table.
void register_GtkScrollInfo(zend_class_entry *ce) {
  register_boxed(BoxedClass{
      .type = GTK_TYPE_SCROLL_INFO, .ce = ce, .fields = fields, .read = read, .write = write});
}
}  // namespace phpgtk
