// GENERATED by gen/gir.php from Gtk.Separator - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkSeparator
#include "php_gtk4.h"
#include "core/object.h"
#include "core/enums.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkSeparator::__construct(GtkOrientation $orientation)
 *
 * Creates a new `GtkSeparator` with the given orientation.
 */
ZEND_METHOD(Gtk4_GtkSeparator, __construct) {
  zval *orientation;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(orientation, enum_class_for_type(GTK_TYPE_ORIENTATION))
  ZEND_PARSE_PARAMETERS_END();
  gint orientation_v = 0;
  if (!enum_from_php(orientation, GTK_TYPE_ORIENTATION, &orientation_v)) RETURN_THROWS();
  GObject *obj =
      subtype_new(ZEND_THIS, "orientation", static_cast<GtkOrientation>(orientation_v), nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_separator_new(static_cast<GtkOrientation>(orientation_v)));
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}
