// GENERATED by gen/gir.php from Gtk.TextMark - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkTextMark
#include "php_gtk4.h"
#include "core/object.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\GtkTextMark::__construct(?string $name, bool $left_gravity)
 *
 * Creates a text mark.
 */
ZEND_METHOD(Gtk4_GtkTextMark, __construct) {
  zend_string *name = nullptr;
  bool left_gravity;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR_OR_NULL(name)
  Z_PARAM_BOOL(left_gravity)
  ZEND_PARSE_PARAMETERS_END();
  if (name != nullptr && !phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  GObject *obj = subtype_new(ZEND_THIS, "name", name != nullptr ? ZSTR_VAL(name) : nullptr,
                             "left-gravity", left_gravity, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_text_mark_new(name != nullptr ? ZSTR_VAL(name) : nullptr, left_gravity));
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkTextMark::get_buffer(): ?GtkTextBuffer
 *
 * Gets the buffer this mark is located inside.
 */
ZEND_METHOD(Gtk4_GtkTextMark, get_buffer) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  GtkTextBuffer *phpgtk_ret = gtk_text_mark_get_buffer(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextMark::get_deleted(): bool
 *
 * Returns `true` if the mark has been removed from its buffer.
 */
ZEND_METHOD(Gtk4_GtkTextMark, get_deleted) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  RETURN_BOOL(gtk_text_mark_get_deleted(self));
}

/**
 * Gtk4\GtkTextMark::get_left_gravity(): bool
 *
 * Determines whether the mark has left gravity.
 */
ZEND_METHOD(Gtk4_GtkTextMark, get_left_gravity) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  RETURN_BOOL(gtk_text_mark_get_left_gravity(self));
}

/**
 * Gtk4\GtkTextMark::get_name(): ?string
 *
 * Returns the mark name.
 */
ZEND_METHOD(Gtk4_GtkTextMark, get_name) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  PHPGTK_RETURN_STRING_OR_NULL(gtk_text_mark_get_name(self));
}

/**
 * Gtk4\GtkTextMark::get_visible(): bool
 *
 * Returns `true` if the mark is visible.
 */
ZEND_METHOD(Gtk4_GtkTextMark, get_visible) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  RETURN_BOOL(gtk_text_mark_get_visible(self));
}

/**
 * Gtk4\GtkTextMark::set_visible(bool $setting): void
 */
ZEND_METHOD(Gtk4_GtkTextMark, set_visible) {
  bool setting;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(setting)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextMark *self = PHPGTK_SELF(GtkTextMark, GTK_TYPE_TEXT_MARK);
  gtk_text_mark_set_visible(self, setting);
}
