// GENERATED by gen/gir.php from Gtk.TextBuffer - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GtkTextBuffer
#include "php_gtk4.h"
#include "core/object.h"
#include "core/boxed.h"
#include "core/subtype.h"
#include "core/error.h"
#include <array>

using namespace phpgtk;

// The insert family's (text, len) pairs: GTK reads exactly `len` bytes and trusts them to
// be valid UTF-8, so an unchecked count read past the PHP string (or cut a character in
// half) with nothing to notice. A PHP string knows its length: `len` defaults to -1 (all
// of it) where the signature allows, and any given count must be a prefix length on a
// character boundary.
namespace {

// Validate a byte count against `text` (already check_utf8()d): -1, or a prefix length
// ending on a UTF-8 character boundary. ValueError naming argument `arg` otherwise.
bool check_text_len(const zend_string *text, zend_long len, uint32_t arg) {
  const auto size = static_cast<zend_long>(ZSTR_LEN(text));
  if (len == -1) return true;
  if (len < 0 || len > size) {
    zend_argument_value_error(arg,
                              "must be -1 (all of the text) or between 0 and the text's byte "
                              "length (" ZEND_LONG_FMT ")",
                              size);
    return false;
  }
  if (len < size && (static_cast<unsigned char>(*(ZSTR_VAL(text) + len)) & 0xC0U) == 0x80U) {
    zend_argument_value_error(arg, "must not cut a UTF-8 character in half");
    return false;
  }
  return true;
}

}  // namespace

/**
 * Gtk4\GtkTextBuffer::__construct(?GtkTextTagTable $table = null)
 *
 * Creates a new text buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, __construct) {
  zval *table = nullptr;
  ZEND_PARSE_PARAMETERS_START(0, 1)
  Z_PARAM_OPTIONAL
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(table, class_for_gtype(GTK_TYPE_TEXT_TAG_TABLE))
  ZEND_PARSE_PARAMETERS_END();
  GObject *table_o = nullptr;
  if (table != nullptr) {
    table_o = unwrap(table, GTK_TYPE_TEXT_TAG_TABLE);
    if (table_o == nullptr) RETURN_THROWS();
  }
  GObject *obj = subtype_new(ZEND_THIS, "tag-table",
                             table_o != nullptr ? GTK_TEXT_TAG_TABLE(table_o) : nullptr, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(gtk_text_buffer_new(table_o != nullptr ? GTK_TEXT_TAG_TABLE(table_o) : nullptr));
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\GtkTextBuffer::add_mark(GtkTextMark $mark, GtkTextIter $where): void
 *
 * Adds the mark at position $where.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, add_mark) {
  zval *mark;
  zval *where;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  Z_PARAM_OBJECT_OF_CLASS(where, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  gpointer where_b = unwrap_boxed(where, GTK_TYPE_TEXT_ITER);
  if (where_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_add_mark(self, GTK_TEXT_MARK(mark_o), static_cast<GtkTextIter *>(where_b));
}

/**
 * Gtk4\GtkTextBuffer::apply_tag(GtkTextTag $tag, GtkTextIter $start, GtkTextIter $end): void
 *
 * Emits the “apply-tag” signal on $buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, apply_tag) {
  zval *tag;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(tag, class_for_gtype(GTK_TYPE_TEXT_TAG))
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *tag_o = unwrap(tag, GTK_TYPE_TEXT_TAG);
  if (tag_o == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_apply_tag(self, GTK_TEXT_TAG(tag_o), static_cast<GtkTextIter *>(start_b),
                            static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::apply_tag_by_name(string $name, GtkTextIter $start, GtkTextIter $end): void
 *
 * Emits the “apply-tag” signal on $buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, apply_tag_by_name) {
  zend_string *name;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(name)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_apply_tag_by_name(self, ZSTR_VAL(name), static_cast<GtkTextIter *>(start_b),
                                    static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::backspace(GtkTextIter $iter, bool $interactive, bool $default_editable): bool
 *
 * Performs the appropriate action as if the user hit the delete key with the cursor at the
 * position specified by $iter.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, backspace) {
  zval *iter;
  bool interactive;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(interactive)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(gtk_text_buffer_backspace(self, static_cast<GtkTextIter *>(iter_b), interactive,
                                        default_editable));
}

/**
 * Gtk4\GtkTextBuffer::begin_irreversible_action(): void
 *
 * Denotes the beginning of an action that may not be undone.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, begin_irreversible_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_begin_irreversible_action(self);
}

/**
 * Gtk4\GtkTextBuffer::begin_user_action(): void
 *
 * Called to indicate that the buffer operations between here and a call to
 * gtk_text_buffer_end_user_action() are part of a single user-visible operation.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, begin_user_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_begin_user_action(self);
}

/**
 * Gtk4\GtkTextBuffer::create_mark(?string $mark_name, GtkTextIter $where, bool $left_gravity):
 * GtkTextMark
 *
 * Creates a mark at position $where.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, create_mark) {
  zend_string *mark_name = nullptr;
  zval *where;
  bool left_gravity;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR_OR_NULL(mark_name)
  Z_PARAM_OBJECT_OF_CLASS(where, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(left_gravity)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (mark_name != nullptr && !phpgtk::check_utf8(mark_name, 1)) RETURN_THROWS();
  gpointer where_b = unwrap_boxed(where, GTK_TYPE_TEXT_ITER);
  if (where_b == nullptr) RETURN_THROWS();
  GtkTextMark *phpgtk_ret =
      gtk_text_buffer_create_mark(self, mark_name != nullptr ? ZSTR_VAL(mark_name) : nullptr,
                                  static_cast<GtkTextIter *>(where_b), left_gravity);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextBuffer::delete(GtkTextIter $start, GtkTextIter $end): void
 *
 * Deletes text between $start and $end.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, delete) {
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_delete(self, static_cast<GtkTextIter *>(start_b),
                         static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::delete_interactive(GtkTextIter $start_iter, GtkTextIter $end_iter, bool
 * $default_editable): bool
 *
 * Deletes all editable text in the given range.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, delete_interactive) {
  zval *start_iter;
  zval *end_iter;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(start_iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end_iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer start_iter_b = unwrap_boxed(start_iter, GTK_TYPE_TEXT_ITER);
  if (start_iter_b == nullptr) RETURN_THROWS();
  gpointer end_iter_b = unwrap_boxed(end_iter, GTK_TYPE_TEXT_ITER);
  if (end_iter_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(gtk_text_buffer_delete_interactive(self, static_cast<GtkTextIter *>(start_iter_b),
                                                 static_cast<GtkTextIter *>(end_iter_b),
                                                 default_editable));
}

/**
 * Gtk4\GtkTextBuffer::delete_mark(GtkTextMark $mark): void
 *
 * Deletes $mark, so that it’s no longer located anywhere in the buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, delete_mark) {
  zval *mark;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  gtk_text_buffer_delete_mark(self, GTK_TEXT_MARK(mark_o));
}

/**
 * Gtk4\GtkTextBuffer::delete_mark_by_name(string $name): void
 *
 * Deletes the mark named $name; the mark must exist.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, delete_mark_by_name) {
  zend_string *name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(name)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  gtk_text_buffer_delete_mark_by_name(self, ZSTR_VAL(name));
}

/**
 * Gtk4\GtkTextBuffer::delete_selection(bool $interactive, bool $default_editable): bool
 *
 * Deletes the range between the “insert” and “selection_bound” marks, that is, the
 * currently-selected text.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, delete_selection) {
  bool interactive;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_BOOL(interactive)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_delete_selection(self, interactive, default_editable));
}

/**
 * Gtk4\GtkTextBuffer::end_irreversible_action(): void
 *
 * Denotes the end of an action that may not be undone.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, end_irreversible_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_end_irreversible_action(self);
}

/**
 * Gtk4\GtkTextBuffer::end_user_action(): void
 *
 * Ends a user-visible operation.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, end_user_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_end_user_action(self);
}

/**
 * Gtk4\GtkTextBuffer::get_bounds(): array
 *
 * Retrieves the first and last iterators in the buffer, i.e. the entire buffer lies within the
 * range [$start,$end).
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_bounds) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextIter start{};
  GtkTextIter end{};
  gtk_text_buffer_get_bounds(self, &start, &end);
  array_init_size(return_value, 2);
  {
    zval item;
    wrap_boxed(GTK_TYPE_TEXT_ITER, &start, &item);
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    wrap_boxed(GTK_TYPE_TEXT_ITER, &end, &item);
    add_next_index_zval(return_value, &item);
  }
}

/**
 * Gtk4\GtkTextBuffer::get_can_redo(): bool
 *
 * Gets whether there is a redoable action in the history.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_can_redo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_get_can_redo(self));
}

/**
 * Gtk4\GtkTextBuffer::get_can_undo(): bool
 *
 * Gets whether there is an undoable action in the history.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_can_undo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_get_can_undo(self));
}

/**
 * Gtk4\GtkTextBuffer::get_char_count(): int
 *
 * Gets the number of characters in the buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_char_count) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_LONG(static_cast<zend_long>(gtk_text_buffer_get_char_count(self)));
}

/**
 * Gtk4\GtkTextBuffer::get_enable_undo(): bool
 *
 * Gets whether the buffer is saving modifications to the buffer to allow for undo and redo
 * actions.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_enable_undo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_get_enable_undo(self));
}

/**
 * Gtk4\GtkTextBuffer::get_end_iter(): GtkTextIter
 *
 * Initializes $iter with the “end iterator,” one past the last valid character in the text
 * buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_end_iter) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextIter iter{};
  gtk_text_buffer_get_end_iter(self, &iter);
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_has_selection(): bool
 *
 * Indicates whether the buffer has some text currently selected.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_has_selection) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_get_has_selection(self));
}

/**
 * Gtk4\GtkTextBuffer::get_insert(): GtkTextMark
 *
 * Returns the mark that represents the cursor (insertion point).
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_insert) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextMark *phpgtk_ret = gtk_text_buffer_get_insert(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_iter_at_line(int $line_number): ?GtkTextIter
 *
 * Initializes $iter to the start of the given line.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_iter_at_line) {
  zend_long line_number;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(line_number)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_range<int>(line_number, 1)) RETURN_THROWS();
  GtkTextIter iter{};
  if (!gtk_text_buffer_get_iter_at_line(self, &iter, static_cast<int>(line_number))) RETURN_NULL();
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_iter_at_line_index(int $line_number, int $byte_index): ?GtkTextIter
 *
 * Obtains an iterator pointing to $byte_index within the given line.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_iter_at_line_index) {
  zend_long line_number;
  zend_long byte_index;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(line_number)
  Z_PARAM_LONG(byte_index)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_range<int>(line_number, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(byte_index, 2)) RETURN_THROWS();
  GtkTextIter iter{};
  if (!gtk_text_buffer_get_iter_at_line_index(self, &iter, static_cast<int>(line_number),
                                              static_cast<int>(byte_index)))
    RETURN_NULL();
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_iter_at_line_offset(int $line_number, int $char_offset): ?GtkTextIter
 *
 * Obtains an iterator pointing to $char_offset within the given line.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_iter_at_line_offset) {
  zend_long line_number;
  zend_long char_offset;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(line_number)
  Z_PARAM_LONG(char_offset)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_range<int>(line_number, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(char_offset, 2)) RETURN_THROWS();
  GtkTextIter iter{};
  if (!gtk_text_buffer_get_iter_at_line_offset(self, &iter, static_cast<int>(line_number),
                                               static_cast<int>(char_offset)))
    RETURN_NULL();
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_iter_at_mark(GtkTextMark $mark): GtkTextIter
 *
 * Initializes $iter with the current position of $mark.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_iter_at_mark) {
  zval *mark;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  GtkTextIter iter{};
  gtk_text_buffer_get_iter_at_mark(self, &iter, GTK_TEXT_MARK(mark_o));
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_iter_at_offset(int $char_offset): GtkTextIter
 *
 * Initializes $iter to a position $char_offset chars from the start of the entire buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_iter_at_offset) {
  zend_long char_offset;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(char_offset)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_range<int>(char_offset, 1)) RETURN_THROWS();
  GtkTextIter iter{};
  gtk_text_buffer_get_iter_at_offset(self, &iter, static_cast<int>(char_offset));
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_line_count(): int
 *
 * Obtains the number of lines in the buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_line_count) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_LONG(static_cast<zend_long>(gtk_text_buffer_get_line_count(self)));
}

/**
 * Gtk4\GtkTextBuffer::get_mark(string $name): ?GtkTextMark
 *
 * Returns the mark named $name in buffer $buffer, or `null` if no such mark exists in the buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_mark) {
  zend_string *name;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_STR(name)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  GtkTextMark *phpgtk_ret = gtk_text_buffer_get_mark(self, ZSTR_VAL(name));
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_max_undo_levels(): int
 *
 * Gets the maximum number of undo levels to perform.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_max_undo_levels) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_LONG(static_cast<zend_long>(gtk_text_buffer_get_max_undo_levels(self)));
}

/**
 * Gtk4\GtkTextBuffer::get_modified(): bool
 *
 * Indicates whether the buffer has been modified since the last call to `set_modified` set the
 * modification flag to `false`.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_modified) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  RETURN_BOOL(gtk_text_buffer_get_modified(self));
}

/**
 * Gtk4\GtkTextBuffer::get_selection_bound(): GtkTextMark
 *
 * Returns the mark that represents the selection bound.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_selection_bound) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextMark *phpgtk_ret = gtk_text_buffer_get_selection_bound(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_selection_bounds(): ?array
 *
 * Returns `true` if some text is selected; places the bounds of the selection in $start and $end.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_selection_bounds) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextIter start{};
  GtkTextIter end{};
  if (!gtk_text_buffer_get_selection_bounds(self, &start, &end)) RETURN_NULL();
  array_init_size(return_value, 2);
  {
    zval item;
    wrap_boxed(GTK_TYPE_TEXT_ITER, &start, &item);
    add_next_index_zval(return_value, &item);
  }
  {
    zval item;
    wrap_boxed(GTK_TYPE_TEXT_ITER, &end, &item);
    add_next_index_zval(return_value, &item);
  }
}

/**
 * Gtk4\GtkTextBuffer::get_slice(GtkTextIter $start, GtkTextIter $end, bool $include_hidden_chars):
 * string
 *
 * Returns the text in the range [$start,$end).
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_slice) {
  zval *start;
  zval *end;
  bool include_hidden_chars;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(include_hidden_chars)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  char *phpgtk_ret =
      gtk_text_buffer_get_slice(self, static_cast<GtkTextIter *>(start_b),
                                static_cast<GtkTextIter *>(end_b), include_hidden_chars);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GtkTextBuffer::get_start_iter(): GtkTextIter
 *
 * Initialized $iter with the first position in the text buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_start_iter) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextIter iter{};
  gtk_text_buffer_get_start_iter(self, &iter);
  wrap_boxed(GTK_TYPE_TEXT_ITER, &iter, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_tag_table(): GtkTextTagTable
 *
 * Get the `GtkTextTagTable` associated with this buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_tag_table) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GtkTextTagTable *phpgtk_ret = gtk_text_buffer_get_tag_table(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\GtkTextBuffer::get_text(GtkTextIter $start, GtkTextIter $end, bool $include_hidden_chars):
 * string
 *
 * Returns the text in the range [$start,$end).
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, get_text) {
  zval *start;
  zval *end;
  bool include_hidden_chars;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(include_hidden_chars)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  char *phpgtk_ret =
      gtk_text_buffer_get_text(self, static_cast<GtkTextIter *>(start_b),
                               static_cast<GtkTextIter *>(end_b), include_hidden_chars);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETVAL_STRING(phpgtk_ret);
  g_free(phpgtk_ret);
}

/**
 * Gtk4\GtkTextBuffer::insert_paintable(GtkTextIter $iter, GdkPaintable $paintable): void
 *
 * Inserts an image into the text buffer at $iter.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_paintable) {
  zval *iter;
  zval *paintable;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(paintable, class_for_gtype(GDK_TYPE_PAINTABLE))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  GObject *paintable_o = unwrap(paintable, GDK_TYPE_PAINTABLE);
  if (paintable_o == nullptr) RETURN_THROWS();
  gtk_text_buffer_insert_paintable(self, static_cast<GtkTextIter *>(iter_b),
                                   GDK_PAINTABLE(paintable_o));
}

/**
 * Gtk4\GtkTextBuffer::insert_range(GtkTextIter $iter, GtkTextIter $start, GtkTextIter $end): void
 *
 * Copies text, tags, and paintables between $start and $end and inserts the copy at $iter.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_range) {
  zval *iter;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_insert_range(self, static_cast<GtkTextIter *>(iter_b),
                               static_cast<GtkTextIter *>(start_b),
                               static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::insert_range_interactive(GtkTextIter $iter, GtkTextIter $start, GtkTextIter
 * $end, bool $default_editable): bool
 *
 * Copies text, tags, and paintables between $start and $end and inserts the copy at $iter.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_range_interactive) {
  zval *iter;
  zval *start;
  zval *end;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(gtk_text_buffer_insert_range_interactive(
      self, static_cast<GtkTextIter *>(iter_b), static_cast<GtkTextIter *>(start_b),
      static_cast<GtkTextIter *>(end_b), default_editable));
}

/**
 * Gtk4\GtkTextBuffer::move_mark(GtkTextMark $mark, GtkTextIter $where): void
 *
 * Moves $mark to the new location $where.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, move_mark) {
  zval *mark;
  zval *where;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  Z_PARAM_OBJECT_OF_CLASS(where, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  gpointer where_b = unwrap_boxed(where, GTK_TYPE_TEXT_ITER);
  if (where_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_move_mark(self, GTK_TEXT_MARK(mark_o), static_cast<GtkTextIter *>(where_b));
}

/**
 * Gtk4\GtkTextBuffer::move_mark_by_name(string $name, GtkTextIter $where): void
 *
 * Moves the mark named $name (which must exist) to location $where.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, move_mark_by_name) {
  zend_string *name;
  zval *where;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(name)
  Z_PARAM_OBJECT_OF_CLASS(where, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  gpointer where_b = unwrap_boxed(where, GTK_TYPE_TEXT_ITER);
  if (where_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_move_mark_by_name(self, ZSTR_VAL(name), static_cast<GtkTextIter *>(where_b));
}

/**
 * Gtk4\GtkTextBuffer::place_cursor(GtkTextIter $where): void
 *
 * This function moves the “insert” and “selection_bound” marks simultaneously.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, place_cursor) {
  zval *where;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(where, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer where_b = unwrap_boxed(where, GTK_TYPE_TEXT_ITER);
  if (where_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_place_cursor(self, static_cast<GtkTextIter *>(where_b));
}

/**
 * Gtk4\GtkTextBuffer::redo(): void
 *
 * Redoes the next redoable action on the buffer, if there is one.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, redo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_redo(self);
}

/**
 * Gtk4\GtkTextBuffer::remove_all_tags(GtkTextIter $start, GtkTextIter $end): void
 *
 * Removes all tags in the range between $start and $end.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, remove_all_tags) {
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_remove_all_tags(self, static_cast<GtkTextIter *>(start_b),
                                  static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::remove_tag(GtkTextTag $tag, GtkTextIter $start, GtkTextIter $end): void
 *
 * Emits the “remove-tag” signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, remove_tag) {
  zval *tag;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(tag, class_for_gtype(GTK_TYPE_TEXT_TAG))
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  GObject *tag_o = unwrap(tag, GTK_TYPE_TEXT_TAG);
  if (tag_o == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_remove_tag(self, GTK_TEXT_TAG(tag_o), static_cast<GtkTextIter *>(start_b),
                             static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::remove_tag_by_name(string $name, GtkTextIter $start, GtkTextIter $end): void
 *
 * Emits the “remove-tag” signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, remove_tag_by_name) {
  zend_string *name;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(name)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(name, 1)) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_remove_tag_by_name(self, ZSTR_VAL(name), static_cast<GtkTextIter *>(start_b),
                                     static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::select_range(GtkTextIter $ins, GtkTextIter $bound): void
 *
 * This function moves the “insert” and “selection_bound” marks simultaneously.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, select_range) {
  zval *ins;
  zval *bound;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(ins, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(bound, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer ins_b = unwrap_boxed(ins, GTK_TYPE_TEXT_ITER);
  if (ins_b == nullptr) RETURN_THROWS();
  gpointer bound_b = unwrap_boxed(bound, GTK_TYPE_TEXT_ITER);
  if (bound_b == nullptr) RETURN_THROWS();
  gtk_text_buffer_select_range(self, static_cast<GtkTextIter *>(ins_b),
                               static_cast<GtkTextIter *>(bound_b));
}

/**
 * Gtk4\GtkTextBuffer::set_enable_undo(bool $enable_undo): void
 *
 * Sets whether or not to enable undoable actions in the text buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, set_enable_undo) {
  bool enable_undo;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(enable_undo)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_set_enable_undo(self, enable_undo);
}

/**
 * Gtk4\GtkTextBuffer::set_max_undo_levels(int $max_undo_levels): void
 *
 * Sets the maximum number of undo levels to perform.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, set_max_undo_levels) {
  zend_long max_undo_levels;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(max_undo_levels)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_range<guint>(max_undo_levels, 1)) RETURN_THROWS();
  gtk_text_buffer_set_max_undo_levels(self, static_cast<guint>(max_undo_levels));
}

/**
 * Gtk4\GtkTextBuffer::set_modified(bool $setting): void
 *
 * Used to keep track of whether the buffer has been modified since the last time it was saved.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, set_modified) {
  bool setting;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_BOOL(setting)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_set_modified(self, setting);
}

/**
 * Gtk4\GtkTextBuffer::undo(): void
 *
 * Undoes the last undoable action on the buffer, if there is one.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, undo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gtk_text_buffer_undo(self);
}

/**
 * public function insert(GtkTextIter $iter, string $text, int $len = -1): void
 * Inserts $len bytes of $text at position $iter (-1, the default, inserts all of it; a
 * given count must end on a UTF-8 character boundary). Emits the "insert-text" signal;
 * $iter is revalidated to point to the end of the inserted text.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert) {
  zval *iter;
  zend_string *text;
  zend_long len = -1;
  ZEND_PARSE_PARAMETERS_START(2, 3)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_STR(text)
  Z_PARAM_OPTIONAL
  Z_PARAM_LONG(len)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  if (!phpgtk::check_utf8(text, 2)) RETURN_THROWS();
  if (!check_text_len(text, len, 3)) RETURN_THROWS();
  gtk_text_buffer_insert(self, static_cast<GtkTextIter *>(iter_b), ZSTR_VAL(text),
                         static_cast<int>(len));
}

/**
 * public function insert_at_cursor(string $text, int $len = -1): void
 * Inserts $len bytes of $text at the cursor (-1, the default, inserts all of it; a given
 * count must end on a UTF-8 character boundary). Calls `insert`, using the current cursor
 * position as the insertion point.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_at_cursor) {
  zend_string *text;
  zend_long len = -1;
  ZEND_PARSE_PARAMETERS_START(1, 2)
  Z_PARAM_STR(text)
  Z_PARAM_OPTIONAL
  Z_PARAM_LONG(len)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(text, 1)) RETURN_THROWS();
  if (!check_text_len(text, len, 2)) RETURN_THROWS();
  gtk_text_buffer_insert_at_cursor(self, ZSTR_VAL(text), static_cast<int>(len));
}

/**
 * public function insert_interactive(GtkTextIter $iter, string $text, int $len, bool
 * $default_editable): bool Inserts $len bytes of $text at $iter like `insert`, but only if the
 * location is editable ($default_editable decides where no tag says). Pass -1 for all of $text; a
 * given count must end on a UTF-8 character boundary.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_interactive) {
  zval *iter;
  zend_string *text;
  zend_long len;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_STR(text)
  Z_PARAM_LONG(len)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  if (!phpgtk::check_utf8(text, 2)) RETURN_THROWS();
  if (!check_text_len(text, len, 3)) RETURN_THROWS();
  RETURN_BOOL(gtk_text_buffer_insert_interactive(self, static_cast<GtkTextIter *>(iter_b),
                                                 ZSTR_VAL(text), static_cast<int>(len),
                                                 default_editable));
}

/**
 * public function insert_interactive_at_cursor(string $text, int $len, bool $default_editable):
 * bool Inserts $len bytes of $text at the cursor like `insert_interactive`, but only if the cursor
 * position is editable. Pass -1 for all of $text; a given count must end on a UTF-8 character
 * boundary.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_interactive_at_cursor) {
  zend_string *text;
  zend_long len;
  bool default_editable;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_STR(text)
  Z_PARAM_LONG(len)
  Z_PARAM_BOOL(default_editable)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(text, 1)) RETURN_THROWS();
  if (!check_text_len(text, len, 2)) RETURN_THROWS();
  RETURN_BOOL(gtk_text_buffer_insert_interactive_at_cursor(
      self, ZSTR_VAL(text), static_cast<int>(len), default_editable));
}

/**
 * public function insert_markup(GtkTextIter $iter, string $markup, int $len = -1): void
 * Inserts $len bytes of Pango markup at position $iter (-1, the default, inserts all of
 * it; a given count must end on a UTF-8 character boundary). $iter is revalidated to
 * point to the end of the inserted text.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, insert_markup) {
  zval *iter;
  zend_string *markup;
  zend_long len = -1;
  ZEND_PARSE_PARAMETERS_START(2, 3)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_STR(markup)
  Z_PARAM_OPTIONAL
  Z_PARAM_LONG(len)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  if (!phpgtk::check_utf8(markup, 2)) RETURN_THROWS();
  if (!check_text_len(markup, len, 3)) RETURN_THROWS();
  gtk_text_buffer_insert_markup(self, static_cast<GtkTextIter *>(iter_b), ZSTR_VAL(markup),
                                static_cast<int>(len));
}

/**
 * public function set_text(string $text, int $len = -1): void
 * Deletes the current contents of the buffer and inserts $text instead. $len is a byte
 * count into $text (-1, the default, inserts all of it) and must end on a UTF-8 character
 * boundary. This is automatically marked as an irreversible action in the undo stack.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, set_text) {
  zend_string *text;
  zend_long len = -1;
  ZEND_PARSE_PARAMETERS_START(1, 2)
  Z_PARAM_STR(text)
  Z_PARAM_OPTIONAL
  Z_PARAM_LONG(len)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!phpgtk::check_utf8(text, 1)) RETURN_THROWS();
  if (!check_text_len(text, len, 2)) RETURN_THROWS();
  gtk_text_buffer_set_text(self, ZSTR_VAL(text), static_cast<int>(len));
}

// vfunc thunks and installers: file-local, installed by class_init of a PHP subtype
namespace {

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->apply_tag -> $this->vfunc_apply_tag() on a PHP subclass
void vfunc_thunk_apply_tag(GtkTextBuffer *self, GtkTextTag *tag, const GtkTextIter *start,
                           const GtkTextIter *end) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_apply_tag", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->apply_tag != nullptr) native->apply_tag(self, tag, start, end);
    return;
  }
  std::array<zval, 3> args{};
  zval *argv = args.data();
  wrap(tag != nullptr ? G_OBJECT(tag) : nullptr, &argv[0]);
  wrap_boxed(GTK_TYPE_TEXT_ITER, start, &argv[1]);
  wrap_boxed(GTK_TYPE_TEXT_ITER, end, &argv[2]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 3, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_apply_tag");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->apply_tag (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_apply_tag(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->apply_tag = vfunc_thunk_apply_tag;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->begin_user_action -> $this->vfunc_begin_user_action() on a
// PHP subclass
void vfunc_thunk_begin_user_action(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_begin_user_action", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->begin_user_action != nullptr) native->begin_user_action(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_begin_user_action");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->begin_user_action (called from class_init / iface_init of
// a PHP subtype)
void vfunc_install_begin_user_action(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->begin_user_action = vfunc_thunk_begin_user_action;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->changed -> $this->vfunc_changed() on a PHP subclass
void vfunc_thunk_changed(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_changed", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->changed != nullptr) native->changed(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_changed");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->changed (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_changed(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->changed = vfunc_thunk_changed;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->delete_range -> $this->vfunc_delete_range() on a PHP subclass
void vfunc_thunk_delete_range(GtkTextBuffer *self, GtkTextIter *start, GtkTextIter *end) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_delete_range", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->delete_range != nullptr) native->delete_range(self, start, end);
    return;
  }
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap_boxed(GTK_TYPE_TEXT_ITER, start, &argv[0]);
  wrap_boxed(GTK_TYPE_TEXT_ITER, end, &argv[1]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 2, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_delete_range");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->delete_range (called from class_init / iface_init of a
// PHP subtype)
void vfunc_install_delete_range(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->delete_range = vfunc_thunk_delete_range;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->end_user_action -> $this->vfunc_end_user_action() on a PHP
// subclass
void vfunc_thunk_end_user_action(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_end_user_action", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->end_user_action != nullptr) native->end_user_action(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_end_user_action");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->end_user_action (called from class_init / iface_init of a
// PHP subtype)
void vfunc_install_end_user_action(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->end_user_action = vfunc_thunk_end_user_action;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->insert_paintable -> $this->vfunc_insert_paintable() on a PHP
// subclass
void vfunc_thunk_insert_paintable(GtkTextBuffer *self, GtkTextIter *iter, GdkPaintable *paintable) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_insert_paintable", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->insert_paintable != nullptr) native->insert_paintable(self, iter, paintable);
    return;
  }
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap_boxed(GTK_TYPE_TEXT_ITER, iter, &argv[0]);
  wrap(paintable != nullptr ? G_OBJECT(paintable) : nullptr, &argv[1]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 2, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_insert_paintable");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->insert_paintable (called from class_init / iface_init of
// a PHP subtype)
void vfunc_install_insert_paintable(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->insert_paintable = vfunc_thunk_insert_paintable;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->insert_text -> $this->vfunc_insert_text() on a PHP subclass
void vfunc_thunk_insert_text(GtkTextBuffer *self, GtkTextIter *pos, const char *new_text,
                             int new_text_length) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_insert_text", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->insert_text != nullptr) native->insert_text(self, pos, new_text, new_text_length);
    return;
  }
  std::array<zval, 3> args{};
  zval *argv = args.data();
  wrap_boxed(GTK_TYPE_TEXT_ITER, pos, &argv[0]);
  if (new_text == nullptr) {
    ZVAL_NULL(&argv[1]);
  } else {
    ZVAL_STRING(&argv[1], new_text);
  }
  ZVAL_LONG(&argv[2], static_cast<zend_long>(new_text_length));
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 3, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_insert_text");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->insert_text (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_insert_text(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->insert_text = vfunc_thunk_insert_text;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->mark_deleted -> $this->vfunc_mark_deleted() on a PHP subclass
void vfunc_thunk_mark_deleted(GtkTextBuffer *self, GtkTextMark *mark) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_mark_deleted", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->mark_deleted != nullptr) native->mark_deleted(self, mark);
    return;
  }
  std::array<zval, 1> args{};
  zval *argv = args.data();
  wrap(mark != nullptr ? G_OBJECT(mark) : nullptr, &argv[0]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 1, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_mark_deleted");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->mark_deleted (called from class_init / iface_init of a
// PHP subtype)
void vfunc_install_mark_deleted(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->mark_deleted = vfunc_thunk_mark_deleted;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->mark_set -> $this->vfunc_mark_set() on a PHP subclass
void vfunc_thunk_mark_set(GtkTextBuffer *self, const GtkTextIter *location, GtkTextMark *mark) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_mark_set", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->mark_set != nullptr) native->mark_set(self, location, mark);
    return;
  }
  std::array<zval, 2> args{};
  zval *argv = args.data();
  wrap_boxed(GTK_TYPE_TEXT_ITER, location, &argv[0]);
  wrap(mark != nullptr ? G_OBJECT(mark) : nullptr, &argv[1]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 2, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_mark_set");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->mark_set (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_mark_set(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->mark_set = vfunc_thunk_mark_set;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->modified_changed -> $this->vfunc_modified_changed() on a PHP
// subclass
void vfunc_thunk_modified_changed(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_modified_changed", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->modified_changed != nullptr) native->modified_changed(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_modified_changed");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->modified_changed (called from class_init / iface_init of
// a PHP subtype)
void vfunc_install_modified_changed(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->modified_changed = vfunc_thunk_modified_changed;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->redo -> $this->vfunc_redo() on a PHP subclass
void vfunc_thunk_redo(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_redo", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->redo != nullptr) native->redo(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_redo");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->redo (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_redo(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->redo = vfunc_thunk_redo;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->remove_tag -> $this->vfunc_remove_tag() on a PHP subclass
void vfunc_thunk_remove_tag(GtkTextBuffer *self, GtkTextTag *tag, const GtkTextIter *start,
                            const GtkTextIter *end) {
  zval zself;
  zend_function *fn = EG(exception) == nullptr
                          ? subtype_vfunc(G_OBJECT(self), "vfunc_remove_tag", &zself)
                          : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->remove_tag != nullptr) native->remove_tag(self, tag, start, end);
    return;
  }
  std::array<zval, 3> args{};
  zval *argv = args.data();
  wrap(tag != nullptr ? G_OBJECT(tag) : nullptr, &argv[0]);
  wrap_boxed(GTK_TYPE_TEXT_ITER, start, &argv[1]);
  wrap_boxed(GTK_TYPE_TEXT_ITER, end, &argv[2]);
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 3, args.data());
  for (zval &arg : args) zval_ptr_dtor(&arg);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_remove_tag");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->remove_tag (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_remove_tag(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->remove_tag = vfunc_thunk_remove_tag;
}

// vfunc thunk: GTK_TEXT_BUFFER_CLASS->undo -> $this->vfunc_undo() on a PHP subclass
void vfunc_thunk_undo(GtkTextBuffer *self) {
  zval zself;
  zend_function *fn =
      EG(exception) == nullptr ? subtype_vfunc(G_OBJECT(self), "vfunc_undo", &zself) : nullptr;
  if (fn == nullptr) {  // no handle (mid-construction, after shutdown) or exception pending
    auto *native = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
    if (native->undo != nullptr) native->undo(self);
    return;
  }
  zval ret;
  ZVAL_UNDEF(&ret);
  zend_call_known_instance_method(fn, Z_OBJ(zself), &ret, 0, nullptr);
  zval_ptr_dtor(&ret);
  zval_ptr_dtor(&zself);
  report_pending_exception("GtkTextBuffer::vfunc_undo");
}

// vfunc installer: GTK_TEXT_BUFFER_CLASS->undo (called from class_init / iface_init of a PHP
// subtype)
void vfunc_install_undo(gpointer klass) {
  GTK_TEXT_BUFFER_CLASS(klass)->undo = vfunc_thunk_undo;
}

}  // namespace

/**
 * Gtk4\GtkTextBuffer::vfunc_apply_tag(GtkTextTag $tag, GtkTextIter $start, GtkTextIter $end): void
 *
 * Native `apply_tag` (TextBufferClass.apply_tag): the GTK implementation below any PHP subclass,
 * for `parent::vfunc_apply_tag()` from an override. Emits the “apply-tag” signal on $buffer.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_apply_tag) {
  zval *tag;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(tag, class_for_gtype(GTK_TYPE_TEXT_TAG))
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_apply_tag(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->apply_tag == nullptr) {
    return;
  }
  GObject *tag_o = unwrap(tag, GTK_TYPE_TEXT_TAG);
  if (tag_o == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  klass->apply_tag(self, GTK_TEXT_TAG(tag_o), static_cast<GtkTextIter *>(start_b),
                   static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_begin_user_action(): void
 *
 * Native `begin_user_action` (TextBufferClass.begin_user_action): the GTK implementation below any
 * PHP subclass, for `parent::vfunc_begin_user_action()` from an override. Called to indicate that
 * the buffer operations between here and a call to gtk_text_buffer_end_user_action() are part of a
 * single user-visible operation.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_begin_user_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_begin_user_action(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->begin_user_action == nullptr) {
    return;
  }
  klass->begin_user_action(self);
}

/**
 * Gtk4\GtkTextBuffer::vfunc_changed(): void
 *
 * Native `changed` (TextBufferClass.changed): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_changed()` from an override. The class handler for the `GtkTextBuffer::changed`
 * signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_changed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_changed(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->changed == nullptr) {
    return;
  }
  klass->changed(self);
}

/**
 * Gtk4\GtkTextBuffer::vfunc_delete_range(GtkTextIter $start, GtkTextIter $end): void
 *
 * Native `delete_range` (TextBufferClass.delete_range): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_delete_range()` from an override. The class handler for the
 * `GtkTextBuffer::delete-range` signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_delete_range) {
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_delete_range(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->delete_range == nullptr) {
    return;
  }
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  klass->delete_range(self, static_cast<GtkTextIter *>(start_b), static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_end_user_action(): void
 *
 * Native `end_user_action` (TextBufferClass.end_user_action): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_end_user_action()` from an override. Ends a user-visible operation.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_end_user_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_end_user_action(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->end_user_action == nullptr) {
    return;
  }
  klass->end_user_action(self);
}

/**
 * Gtk4\GtkTextBuffer::vfunc_insert_paintable(GtkTextIter $iter, GdkPaintable $paintable): void
 *
 * Native `insert_paintable` (TextBufferClass.insert_paintable): the GTK implementation below any
 * PHP subclass, for `parent::vfunc_insert_paintable()` from an override. Inserts an image into the
 * text buffer at $iter.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_insert_paintable) {
  zval *iter;
  zval *paintable;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(iter, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(paintable, class_for_gtype(GDK_TYPE_PAINTABLE))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_insert_paintable(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->insert_paintable == nullptr) {
    return;
  }
  gpointer iter_b = unwrap_boxed(iter, GTK_TYPE_TEXT_ITER);
  if (iter_b == nullptr) RETURN_THROWS();
  GObject *paintable_o = unwrap(paintable, GDK_TYPE_PAINTABLE);
  if (paintable_o == nullptr) RETURN_THROWS();
  klass->insert_paintable(self, static_cast<GtkTextIter *>(iter_b), GDK_PAINTABLE(paintable_o));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_insert_text(GtkTextIter $pos, string $new_text, int $new_text_length):
 * void
 *
 * Native `insert_text` (TextBufferClass.insert_text): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_insert_text()` from an override. The class handler for the
 * `GtkTextBuffer::insert-text` signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_insert_text) {
  zval *pos;
  zend_string *new_text;
  zend_long new_text_length;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(pos, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_STR(new_text)
  Z_PARAM_LONG(new_text_length)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_insert_text(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->insert_text == nullptr) {
    return;
  }
  gpointer pos_b = unwrap_boxed(pos, GTK_TYPE_TEXT_ITER);
  if (pos_b == nullptr) RETURN_THROWS();
  if (!phpgtk::check_utf8(new_text, 2)) RETURN_THROWS();
  if (!phpgtk::check_range<int>(new_text_length, 3)) RETURN_THROWS();
  klass->insert_text(self, static_cast<GtkTextIter *>(pos_b), ZSTR_VAL(new_text),
                     static_cast<int>(new_text_length));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_mark_deleted(GtkTextMark $mark): void
 *
 * Native `mark_deleted` (TextBufferClass.mark_deleted): the GTK implementation below any PHP
 * subclass, for `parent::vfunc_mark_deleted()` from an override. The class handler for the
 * `GtkTextBuffer::mark-deleted` signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_mark_deleted) {
  zval *mark;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_mark_deleted(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->mark_deleted == nullptr) {
    return;
  }
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  klass->mark_deleted(self, GTK_TEXT_MARK(mark_o));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_mark_set(GtkTextIter $location, GtkTextMark $mark): void
 *
 * Native `mark_set` (TextBufferClass.mark_set): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_mark_set()` from an override. The class handler for the `GtkTextBuffer::mark-set`
 * signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_mark_set) {
  zval *location;
  zval *mark;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(location, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(mark, class_for_gtype(GTK_TYPE_TEXT_MARK))
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_mark_set(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->mark_set == nullptr) {
    return;
  }
  gpointer location_b = unwrap_boxed(location, GTK_TYPE_TEXT_ITER);
  if (location_b == nullptr) RETURN_THROWS();
  GObject *mark_o = unwrap(mark, GTK_TYPE_TEXT_MARK);
  if (mark_o == nullptr) RETURN_THROWS();
  klass->mark_set(self, static_cast<GtkTextIter *>(location_b), GTK_TEXT_MARK(mark_o));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_modified_changed(): void
 *
 * Native `modified_changed` (TextBufferClass.modified_changed): the GTK implementation below any
 * PHP subclass, for `parent::vfunc_modified_changed()` from an override. The class handler for the
 * `GtkTextBuffer::modified-changed` signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_modified_changed) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_modified_changed(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->modified_changed == nullptr) {
    return;
  }
  klass->modified_changed(self);
}

/**
 * Gtk4\GtkTextBuffer::vfunc_redo(): void
 *
 * Native `redo` (TextBufferClass.redo): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_redo()` from an override. Redoes the next redoable action on the buffer, if there
 * is one.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_redo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_redo(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->redo == nullptr) {
    return;
  }
  klass->redo(self);
}

/**
 * Gtk4\GtkTextBuffer::vfunc_remove_tag(GtkTextTag $tag, GtkTextIter $start, GtkTextIter $end): void
 *
 * Native `remove_tag` (TextBufferClass.remove_tag): the GTK implementation below any PHP subclass,
 * for `parent::vfunc_remove_tag()` from an override. Emits the “remove-tag” signal.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_remove_tag) {
  zval *tag;
  zval *start;
  zval *end;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(tag, class_for_gtype(GTK_TYPE_TEXT_TAG))
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GTK_TYPE_TEXT_ITER)->ce)
  ZEND_PARSE_PARAMETERS_END();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_remove_tag(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->remove_tag == nullptr) {
    return;
  }
  GObject *tag_o = unwrap(tag, GTK_TYPE_TEXT_TAG);
  if (tag_o == nullptr) RETURN_THROWS();
  gpointer start_b = unwrap_boxed(start, GTK_TYPE_TEXT_ITER);
  if (start_b == nullptr) RETURN_THROWS();
  gpointer end_b = unwrap_boxed(end, GTK_TYPE_TEXT_ITER);
  if (end_b == nullptr) RETURN_THROWS();
  klass->remove_tag(self, GTK_TEXT_TAG(tag_o), static_cast<GtkTextIter *>(start_b),
                    static_cast<GtkTextIter *>(end_b));
}

/**
 * Gtk4\GtkTextBuffer::vfunc_undo(): void
 *
 * Native `undo` (TextBufferClass.undo): the GTK implementation below any PHP subclass, for
 * `parent::vfunc_undo()` from an override. Undoes the last undoable action on the buffer, if there
 * is one.
 */
ZEND_METHOD(Gtk4_GtkTextBuffer, vfunc_undo) {
  ZEND_PARSE_PARAMETERS_NONE();
  GtkTextBuffer *self = PHPGTK_SELF(GtkTextBuffer, GTK_TYPE_TEXT_BUFFER);
  if (!is_php_type(G_OBJECT_TYPE(self))) {
    zend_throw_exception_ex(
        spl_ce_LogicException, 0,
        "GtkTextBuffer::vfunc_undo(): for parent:: chaining from a PHP subclass "
        "only; call the public method instead");
    RETURN_THROWS();
  }
  auto *klass = GTK_TEXT_BUFFER_CLASS(subtype_native_class(G_OBJECT(self)));
  if (klass->undo == nullptr) {
    return;
  }
  klass->undo(self);
}

// MINIT: the vfunc thunks of GtkTextBuffer (core/subtype.h).
void register_vfuncs_GtkTextBuffer() {
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "apply_tag", vfunc_install_apply_tag);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "begin_user_action", vfunc_install_begin_user_action);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "changed", vfunc_install_changed);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "delete_range", vfunc_install_delete_range);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "end_user_action", vfunc_install_end_user_action);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "insert_paintable", vfunc_install_insert_paintable);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "insert_text", vfunc_install_insert_text);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "mark_deleted", vfunc_install_mark_deleted);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "mark_set", vfunc_install_mark_set);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "modified_changed", vfunc_install_modified_changed);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "redo", vfunc_install_redo);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "remove_tag", vfunc_install_remove_tag);
  register_vfunc(GTK_TYPE_TEXT_BUFFER, "undo", vfunc_install_undo);
}
