// GENERATED by gen/gir.php from Gsk.BlendNode - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GskBlendNode (fundamental handle)
#include "php_gtk4.h"
#include "core/fundamental.h"
#include "core/object.h"
#include "core/enums.h"

using namespace phpgtk;

/**
 * Gtk4\GskBlendNode::__construct(GskRenderNode $bottom, GskRenderNode $top, GskBlendMode
 * $blend_mode)
 *
 * Creates a `GskRenderNode` that will use $blend_mode to blend the $top node onto the $bottom
 * node.
 */
ZEND_METHOD(Gtk4_GskBlendNode, __construct) {
  zval *bottom;
  zval *top;
  zval *blend_mode;
  ZEND_PARSE_PARAMETERS_START(3, 3)
  Z_PARAM_OBJECT_OF_CLASS(bottom, fundamental_class_for_type(GSK_TYPE_RENDER_NODE)->ce)
  Z_PARAM_OBJECT_OF_CLASS(top, fundamental_class_for_type(GSK_TYPE_RENDER_NODE)->ce)
  Z_PARAM_OBJECT_OF_CLASS(blend_mode, enum_class_for_type(GSK_TYPE_BLEND_MODE))
  ZEND_PARSE_PARAMETERS_END();
  gpointer bottom_f = unwrap_fundamental(bottom, GSK_TYPE_RENDER_NODE);
  if (bottom_f == nullptr) RETURN_THROWS();
  gpointer top_f = unwrap_fundamental(top, GSK_TYPE_RENDER_NODE);
  if (top_f == nullptr) RETURN_THROWS();
  gint blend_mode_v = 0;
  if (!enum_from_php(blend_mode, GSK_TYPE_BLEND_MODE, &blend_mode_v)) RETURN_THROWS();
  gpointer obj = gsk_blend_node_new(static_cast<GskRenderNode *>(bottom_f),
                                    static_cast<GskRenderNode *>(top_f),
                                    static_cast<GskBlendMode>(blend_mode_v));
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the instance (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  fundamental_adopt(fundamental_from_zval(ZEND_THIS), GSK_TYPE_BLEND_NODE, obj);
}

/**
 * Gtk4\GskBlendNode::get_blend_mode(): GskBlendMode
 *
 * Retrieves the blend mode used by $node.
 */
ZEND_METHOD(Gtk4_GskBlendNode, get_blend_mode) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  enum_to_php(GSK_TYPE_BLEND_MODE, gsk_blend_node_get_blend_mode(self), return_value);
}

/**
 * Gtk4\GskBlendNode::get_bottom_child(): GskRenderNode
 *
 * Retrieves the bottom `GskRenderNode` child of the $node.
 */
ZEND_METHOD(Gtk4_GskBlendNode, get_bottom_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  gpointer phpgtk_ret = gsk_blend_node_get_bottom_child(self);
  wrap_fundamental(GSK_TYPE_RENDER_NODE, phpgtk_ret, return_value);
}

/**
 * Gtk4\GskBlendNode::get_top_child(): GskRenderNode
 *
 * Retrieves the top `GskRenderNode` child of the $node.
 */
ZEND_METHOD(Gtk4_GskBlendNode, get_top_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  gpointer phpgtk_ret = gsk_blend_node_get_top_child(self);
  wrap_fundamental(GSK_TYPE_RENDER_NODE, phpgtk_ret, return_value);
}

namespace {

// gsk_render_node_ref() as the fundamental registry's RefFn.
gpointer fundamental_ref(gpointer p) {
  return gsk_render_node_ref(static_cast<GskRenderNode *>(p));
}

// gsk_render_node_unref() as the fundamental registry's UnrefFn.
void fundamental_unref(gpointer p) {
  gsk_render_node_unref(static_cast<GskRenderNode *>(p));
}

}  // namespace

namespace phpgtk {
// MINIT: bind the PHP class to GSK_TYPE_BLEND_NODE on the fundamental registry.
void register_GskBlendNode(zend_class_entry *ce) {
  register_fundamental(FundamentalClass{
      .type = GSK_TYPE_BLEND_NODE, .ce = ce, .ref = fundamental_ref, .unref = fundamental_unref});
}
}  // namespace phpgtk
