// GENERATED by gen/gir.php from Gsk.LinearGradientNode - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GskLinearGradientNode (fundamental handle)
#include "php_gtk4.h"
#include "core/fundamental.h"
#include "core/object.h"
#include "core/boxed.h"

using namespace phpgtk;

// The colour stops come as a PHP list of [offset, GdkRGBA] pairs (src/Gsk/GskColorStops.h).
#include "Gsk/GskColorStops.h"

#include <vector>

/**
 * Gtk4\GskLinearGradientNode::get_end(): GraphenePoint
 *
 * Retrieves the final point of the linear gradient.
 */
ZEND_METHOD(Gtk4_GskLinearGradientNode, get_end) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  const graphene_point_t *phpgtk_ret = gsk_linear_gradient_node_get_end(self);
  wrap_boxed(GRAPHENE_TYPE_POINT, phpgtk_ret, return_value);
}

/**
 * Gtk4\GskLinearGradientNode::get_n_color_stops(): int
 *
 * Retrieves the number of color stops in the gradient.
 */
ZEND_METHOD(Gtk4_GskLinearGradientNode, get_n_color_stops) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  RETURN_LONG(static_cast<zend_long>(gsk_linear_gradient_node_get_n_color_stops(self)));
}

/**
 * Gtk4\GskLinearGradientNode::get_start(): GraphenePoint
 *
 * Retrieves the initial point of the linear gradient.
 */
ZEND_METHOD(Gtk4_GskLinearGradientNode, get_start) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  const graphene_point_t *phpgtk_ret = gsk_linear_gradient_node_get_start(self);
  wrap_boxed(GRAPHENE_TYPE_POINT, phpgtk_ret, return_value);
}

/**
 * public function __construct(GrapheneRect $bounds, GraphenePoint $start, GraphenePoint $end, array
 * $color_stops) A linear gradient from $start to $end over $bounds, through $color_stops: at least
 * two
 * `[float $offset, GdkRGBA $color]` pairs with offsets ascending from 0.0 to 1.0.
 */
ZEND_METHOD(Gtk4_GskLinearGradientNode, __construct) {
  zval *bounds;
  zval *start;
  zval *end;
  zval *stops;
  ZEND_PARSE_PARAMETERS_START(4, 4)
  Z_PARAM_OBJECT_OF_CLASS(bounds, boxed_class_for_type(GRAPHENE_TYPE_RECT)->ce)
  Z_PARAM_OBJECT_OF_CLASS(start, boxed_class_for_type(GRAPHENE_TYPE_POINT)->ce)
  Z_PARAM_OBJECT_OF_CLASS(end, boxed_class_for_type(GRAPHENE_TYPE_POINT)->ce)
  Z_PARAM_ARRAY(stops)
  ZEND_PARSE_PARAMETERS_END();
  std::vector<GskColorStop> cs;
  if (!color_stops_from_php(stops, 4, cs)) RETURN_THROWS();
  GskRenderNode *self = gsk_linear_gradient_node_new(
      static_cast<graphene_rect_t *>(unwrap_boxed(bounds, GRAPHENE_TYPE_RECT)),
      static_cast<graphene_point_t *>(unwrap_boxed(start, GRAPHENE_TYPE_POINT)),
      static_cast<graphene_point_t *>(unwrap_boxed(end, GRAPHENE_TYPE_POINT)), cs.data(),
      cs.size());
  fundamental_adopt(fundamental_from_zval(ZEND_THIS), GSK_TYPE_LINEAR_GRADIENT_NODE, self);
}

/**
 * public function get_color_stops(): array
 * The colour stops, as the `[float $offset, GdkRGBA $color]` pairs the constructor took.
 *
 * @return list<array{float, GdkRGBA}>
 */
ZEND_METHOD(Gtk4_GskLinearGradientNode, get_color_stops) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  gsize n = 0;
  const GskColorStop *cs = gsk_linear_gradient_node_get_color_stops(self, &n);
  color_stops_to_php(cs, n, return_value);
}

namespace {

// gsk_render_node_ref() as the fundamental registry's RefFn.
gpointer fundamental_ref(gpointer p) {
  return gsk_render_node_ref(static_cast<GskRenderNode *>(p));
}

// gsk_render_node_unref() as the fundamental registry's UnrefFn.
void fundamental_unref(gpointer p) {
  gsk_render_node_unref(static_cast<GskRenderNode *>(p));
}

}  // namespace

namespace phpgtk {
// MINIT: bind the PHP class to GSK_TYPE_LINEAR_GRADIENT_NODE on the fundamental registry.
void register_GskLinearGradientNode(zend_class_entry *ce) {
  register_fundamental(FundamentalClass{.type = GSK_TYPE_LINEAR_GRADIENT_NODE,
                                        .ce = ce,
                                        .ref = fundamental_ref,
                                        .unref = fundamental_unref});
}
}  // namespace phpgtk
