// GENERATED by gen/gir.php from Gsk.OpacityNode - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GskOpacityNode (fundamental handle)
#include "php_gtk4.h"
#include "core/fundamental.h"
#include "core/object.h"

using namespace phpgtk;

/**
 * Gtk4\GskOpacityNode::__construct(GskRenderNode $child, float $opacity)
 *
 * Creates a `GskRenderNode` that will drawn the $child with reduced $opacity.
 */
ZEND_METHOD(Gtk4_GskOpacityNode, __construct) {
  zval *child;
  double opacity;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(child, fundamental_class_for_type(GSK_TYPE_RENDER_NODE)->ce)
  Z_PARAM_DOUBLE(opacity)
  ZEND_PARSE_PARAMETERS_END();
  gpointer child_f = unwrap_fundamental(child, GSK_TYPE_RENDER_NODE);
  if (child_f == nullptr) RETURN_THROWS();
  gpointer obj =
      gsk_opacity_node_new(static_cast<GskRenderNode *>(child_f), static_cast<float>(opacity));
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the instance (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  fundamental_adopt(fundamental_from_zval(ZEND_THIS), GSK_TYPE_OPACITY_NODE, obj);
}

/**
 * Gtk4\GskOpacityNode::get_child(): GskRenderNode
 *
 * Gets the child node that is getting opacityed by the given $node.
 */
ZEND_METHOD(Gtk4_GskOpacityNode, get_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  gpointer phpgtk_ret = gsk_opacity_node_get_child(self);
  wrap_fundamental(GSK_TYPE_RENDER_NODE, phpgtk_ret, return_value);
}

/**
 * Gtk4\GskOpacityNode::get_opacity(): float
 *
 * Gets the transparency factor for an opacity node.
 */
ZEND_METHOD(Gtk4_GskOpacityNode, get_opacity) {
  ZEND_PARSE_PARAMETERS_NONE();
  auto *self = static_cast<GskRenderNode *>(fundamental_self(execute_data));
  if (self == nullptr) RETURN_THROWS();
  RETURN_DOUBLE(gsk_opacity_node_get_opacity(self));
}

namespace {

// gsk_render_node_ref() as the fundamental registry's RefFn.
gpointer fundamental_ref(gpointer p) {
  return gsk_render_node_ref(static_cast<GskRenderNode *>(p));
}

// gsk_render_node_unref() as the fundamental registry's UnrefFn.
void fundamental_unref(gpointer p) {
  gsk_render_node_unref(static_cast<GskRenderNode *>(p));
}

}  // namespace

namespace phpgtk {
// MINIT: bind the PHP class to GSK_TYPE_OPACITY_NODE on the fundamental registry.
void register_GskOpacityNode(zend_class_entry *ce) {
  register_fundamental(FundamentalClass{
      .type = GSK_TYPE_OPACITY_NODE, .ce = ce, .ref = fundamental_ref, .unref = fundamental_unref});
}
}  // namespace phpgtk
