// GENERATED by gen/gir.php from WebKit.ContextMenuItem - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\WebKitContextMenuItem
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"
#include "core/enums.h"
#include "core/variant.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitContextMenuItem::__construct()
 *
 * WebKitContextMenuItem has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * static Gtk4\WebKitContextMenuItem::new_from_gaction(GAction $action, string $label, mixed $target
 * = null): WebKitContextMenuItem
 *
 * Creates a new #WebKitContextMenuItem for the given $action and $label.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, new_from_gaction) {
  zval *action;
  zend_string *label;
  zval *target = nullptr;
  ZEND_PARSE_PARAMETERS_START(2, 3)
  Z_PARAM_OBJECT_OF_CLASS(action, class_for_gtype(G_TYPE_ACTION))
  Z_PARAM_STR(label)
  Z_PARAM_OPTIONAL
  Z_PARAM_ZVAL(target)
  ZEND_PARSE_PARAMETERS_END();
  GObject *action_o = unwrap(action, G_TYPE_ACTION);
  if (action_o == nullptr) RETURN_THROWS();
  if (!phpgtk::check_utf8(label, 2)) RETURN_THROWS();
  GVariant *target_v = nullptr;
  if (target != nullptr && Z_TYPE_P(target) != IS_NULL) {
    target_v = php_to_variant(target, nullptr);
    if (target_v == nullptr) RETURN_THROWS();
    g_variant_ref_sink(target_v);
  }
  WebKitContextMenuItem *call_result =
      webkit_context_menu_item_new_from_gaction(G_ACTION(action_o), ZSTR_VAL(label), target_v);
  if (target_v != nullptr) g_variant_unref(target_v);
  GObject *obj = G_OBJECT(call_result);
  wrap(obj, return_value);
}

/**
 * static Gtk4\WebKitContextMenuItem::new_from_stock_action(WebKitContextMenuAction $action):
 * WebKitContextMenuItem
 *
 * Creates a new #WebKitContextMenuItem for the given stock action.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, new_from_stock_action) {
  zval *action;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(action, enum_class_for_type(WEBKIT_TYPE_CONTEXT_MENU_ACTION))
  ZEND_PARSE_PARAMETERS_END();
  gint action_v = 0;
  if (!enum_from_php(action, WEBKIT_TYPE_CONTEXT_MENU_ACTION, &action_v)) RETURN_THROWS();
  const bool precondition_0 = action_v > WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION &&
                              action_v < WEBKIT_CONTEXT_MENU_ACTION_CUSTOM;
  if (!precondition_0) {
    zend_argument_value_error(1, "must be a stock action (neither NoAction nor Custom)");
    RETURN_THROWS();
  }
  GObject *obj = G_OBJECT(webkit_context_menu_item_new_from_stock_action(
      static_cast<WebKitContextMenuAction>(action_v)));
  wrap(obj, return_value);
}

/**
 * static Gtk4\WebKitContextMenuItem::new_from_stock_action_with_label(WebKitContextMenuAction
 * $action, string $label): WebKitContextMenuItem
 *
 * Creates a new #WebKitContextMenuItem for the given stock action using the given $label.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, new_from_stock_action_with_label) {
  zval *action;
  zend_string *label;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(action, enum_class_for_type(WEBKIT_TYPE_CONTEXT_MENU_ACTION))
  Z_PARAM_STR(label)
  ZEND_PARSE_PARAMETERS_END();
  gint action_v = 0;
  if (!enum_from_php(action, WEBKIT_TYPE_CONTEXT_MENU_ACTION, &action_v)) RETURN_THROWS();
  if (!phpgtk::check_utf8(label, 2)) RETURN_THROWS();
  const bool precondition_0 = action_v > WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION &&
                              action_v < WEBKIT_CONTEXT_MENU_ACTION_CUSTOM;
  if (!precondition_0) {
    zend_argument_value_error(1, "must be a stock action (neither NoAction nor Custom)");
    RETURN_THROWS();
  }
  GObject *obj = G_OBJECT(webkit_context_menu_item_new_from_stock_action_with_label(
      static_cast<WebKitContextMenuAction>(action_v), ZSTR_VAL(label)));
  wrap(obj, return_value);
}

/**
 * static Gtk4\WebKitContextMenuItem::new_separator(): WebKitContextMenuItem
 *
 * Creates a new #WebKitContextMenuItem representing a separator.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, new_separator) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = G_OBJECT(webkit_context_menu_item_new_separator());
  wrap(obj, return_value);
}

/**
 * static Gtk4\WebKitContextMenuItem::new_with_submenu(string $label, WebKitContextMenu $submenu):
 * WebKitContextMenuItem
 *
 * Creates a new #WebKitContextMenuItem using the given $label with a submenu.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, new_with_submenu) {
  zend_string *label;
  zval *submenu;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_STR(label)
  Z_PARAM_OBJECT_OF_CLASS(submenu, class_for_gtype(WEBKIT_TYPE_CONTEXT_MENU))
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_utf8(label, 1)) RETURN_THROWS();
  GObject *submenu_o = unwrap(submenu, WEBKIT_TYPE_CONTEXT_MENU);
  if (submenu_o == nullptr) RETURN_THROWS();
  GObject *obj = G_OBJECT(
      webkit_context_menu_item_new_with_submenu(ZSTR_VAL(label), WEBKIT_CONTEXT_MENU(submenu_o)));
  wrap(obj, return_value);
}

/**
 * Gtk4\WebKitContextMenuItem::get_gaction(): ?GAction
 *
 * Gets the action associated to $item as a #GAction.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, get_gaction) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  GAction *phpgtk_ret = webkit_context_menu_item_get_gaction(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitContextMenuItem::get_gaction_target(): mixed
 *
 * Gets the target #GVariant associated with $item.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, get_gaction_target) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  GVariant *phpgtk_ret = webkit_context_menu_item_get_gaction_target(self);
  if (phpgtk_ret == nullptr) RETURN_NULL();
  variant_to_php(phpgtk_ret, return_value);
}

/**
 * Gtk4\WebKitContextMenuItem::get_stock_action(): WebKitContextMenuAction
 *
 * Gets the #WebKitContextMenuAction of $item.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, get_stock_action) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  enum_to_php(WEBKIT_TYPE_CONTEXT_MENU_ACTION, webkit_context_menu_item_get_stock_action(self),
              return_value);
}

/**
 * Gtk4\WebKitContextMenuItem::get_submenu(): ?WebKitContextMenu
 *
 * Gets the submenu of $item.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, get_submenu) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  WebKitContextMenu *phpgtk_ret = webkit_context_menu_item_get_submenu(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitContextMenuItem::get_title(): string
 *
 * Gets the title of $item.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, get_title) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  const char *phpgtk_ret = webkit_context_menu_item_get_title(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitContextMenuItem::is_separator(): bool
 *
 * Checks whether $item is a separator.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, is_separator) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  RETURN_BOOL(webkit_context_menu_item_is_separator(self));
}

/**
 * Gtk4\WebKitContextMenuItem::set_submenu(?WebKitContextMenu $submenu): void
 *
 * Sets or replaces the $item submenu.
 */
ZEND_METHOD(Gtk4_WebKitContextMenuItem, set_submenu) {
  zval *submenu = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(submenu, class_for_gtype(WEBKIT_TYPE_CONTEXT_MENU))
  ZEND_PARSE_PARAMETERS_END();
  WebKitContextMenuItem *self = PHPGTK_SELF(WebKitContextMenuItem, WEBKIT_TYPE_CONTEXT_MENU_ITEM);
  GObject *submenu_o = nullptr;
  if (submenu != nullptr) {
    submenu_o = unwrap(submenu, WEBKIT_TYPE_CONTEXT_MENU);
    if (submenu_o == nullptr) RETURN_THROWS();
  }
  webkit_context_menu_item_set_submenu(
      self, submenu_o != nullptr ? WEBKIT_CONTEXT_MENU(submenu_o) : nullptr);
}
