// GENERATED by gen/gir.php from WebKit.WebsitePolicies - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\WebKitWebsitePolicies
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"
#include "core/enums.h"
#include "core/subtype.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitWebsitePolicies::__construct()
 *
 * Create a new #WebKitWebsitePolicies.
 */
ZEND_METHOD(Gtk4_WebKitWebsitePolicies, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
  GObject *obj = subtype_new(ZEND_THIS, nullptr);
  if (obj == nullptr) {
    if (EG(exception) != nullptr) RETURN_THROWS();
    obj = G_OBJECT(webkit_website_policies_new());
  }
  if (obj == nullptr) {
    zend_throw_error(nullptr,
                     "%s(): GTK refused to create the object (see the "
                     "CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  attach_new(object_from_zval(ZEND_THIS), obj);
}

/**
 * Gtk4\WebKitWebsitePolicies::get_autoplay_policy(): WebKitAutoplayPolicy
 *
 * Get the #WebKitWebsitePolicies:autoplay property.
 */
ZEND_METHOD(Gtk4_WebKitWebsitePolicies, get_autoplay_policy) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitWebsitePolicies *self = PHPGTK_SELF(WebKitWebsitePolicies, WEBKIT_TYPE_WEBSITE_POLICIES);
  enum_to_php(WEBKIT_TYPE_AUTOPLAY_POLICY, webkit_website_policies_get_autoplay_policy(self),
              return_value);
}
