// GENERATED by gen/gir.php from WebKit.PermissionStateQuery - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\WebKitPermissionStateQuery (boxed value type)
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>
#include "core/enums.h"

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\WebKitPermissionStateQuery::__construct()
 *
 * WebKitPermissionStateQuery values come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitPermissionStateQuery, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitPermissionStateQuery::finish(WebKitPermissionState $state): void
 *
 * Notify the web-engine of the selected permission state for the given query. This function should
 * only be called as a response to the `WebKitWebView::query-permission-state` signal.
 */
ZEND_METHOD(Gtk4_WebKitPermissionStateQuery, finish) {
  zval *state;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(state, enum_class_for_type(WEBKIT_TYPE_PERMISSION_STATE))
  ZEND_PARSE_PARAMETERS_END();
  WebKitPermissionStateQuery *self = PHPGTK_BOXED_SELF(WebKitPermissionStateQuery);
  gint state_v = 0;
  if (!enum_from_php(state, WEBKIT_TYPE_PERMISSION_STATE, &state_v)) RETURN_THROWS();
  webkit_permission_state_query_finish(self, static_cast<WebKitPermissionState>(state_v));
}

/**
 * Gtk4\WebKitPermissionStateQuery::get_name(): string
 *
 * Get the permission name for which access is being queried.
 */
ZEND_METHOD(Gtk4_WebKitPermissionStateQuery, get_name) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitPermissionStateQuery *self = PHPGTK_BOXED_SELF(WebKitPermissionStateQuery);
  const char *phpgtk_ret = webkit_permission_state_query_get_name(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitPermissionStateQuery::get_security_origin(): WebKitSecurityOrigin
 *
 * Get the permission origin for which access is being queried.
 */
ZEND_METHOD(Gtk4_WebKitPermissionStateQuery, get_security_origin) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitPermissionStateQuery *self = PHPGTK_BOXED_SELF(WebKitPermissionStateQuery);
  WebKitSecurityOrigin *phpgtk_ret = webkit_permission_state_query_get_security_origin(self);
  wrap_boxed(WEBKIT_TYPE_SECURITY_ORIGIN, phpgtk_ret, return_value);
}

namespace phpgtk {
// MINIT: bind the PHP class to WEBKIT_TYPE_PERMISSION_STATE_QUERY with its field table.
void register_WebKitPermissionStateQuery(zend_class_entry *ce) {
  register_boxed(BoxedClass{.type = WEBKIT_TYPE_PERMISSION_STATE_QUERY,
                            .ce = ce,
                            .fields = fields,
                            .read = read,
                            .write = write});
}
}  // namespace phpgtk
