// GENERATED by gen/gir.php from WebKit.InputMethodUnderline - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\WebKitInputMethodUnderline (boxed value type)
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\WebKitInputMethodUnderline::__construct(int $start_offset, int $end_offset)
 *
 * Create a new #WebKitInputMethodUnderline for the given range in preedit string
 */
ZEND_METHOD(Gtk4_WebKitInputMethodUnderline, __construct) {
  zend_long start_offset;
  zend_long end_offset;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_LONG(start_offset)
  Z_PARAM_LONG(end_offset)
  ZEND_PARSE_PARAMETERS_END();
  if (!phpgtk::check_range<guint>(start_offset, 1)) RETURN_THROWS();
  if (!phpgtk::check_range<guint>(end_offset, 2)) RETURN_THROWS();
  gpointer obj = webkit_input_method_underline_new(static_cast<guint>(start_offset),
                                                   static_cast<guint>(end_offset));
  if (obj == nullptr) {
    zend_throw_error(nullptr, "%s(): GTK refused to create the value (see the CRITICAL above)",
                     ZSTR_VAL(EX(func)->common.function_name));
    RETURN_THROWS();
  }
  boxed_adopt(boxed_from_zval(ZEND_THIS), WEBKIT_TYPE_INPUT_METHOD_UNDERLINE, obj);
}

/**
 * Gtk4\WebKitInputMethodUnderline::set_color(?GdkRGBA $rgba): void
 *
 * Set the color of the underline.
 */
ZEND_METHOD(Gtk4_WebKitInputMethodUnderline, set_color) {
  zval *rgba = nullptr;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS_OR_NULL(rgba, boxed_class_for_type(GDK_TYPE_RGBA)->ce)
  ZEND_PARSE_PARAMETERS_END();
  WebKitInputMethodUnderline *self = PHPGTK_BOXED_SELF(WebKitInputMethodUnderline);
  gpointer rgba_b = nullptr;
  if (rgba != nullptr) {
    rgba_b = unwrap_boxed(rgba, GDK_TYPE_RGBA);
    if (rgba_b == nullptr) RETURN_THROWS();
  }
  webkit_input_method_underline_set_color(self, static_cast<GdkRGBA *>(rgba_b));
}

namespace phpgtk {
// MINIT: bind the PHP class to WEBKIT_TYPE_INPUT_METHOD_UNDERLINE with its field table.
void register_WebKitInputMethodUnderline(zend_class_entry *ce) {
  register_boxed(BoxedClass{.type = WEBKIT_TYPE_INPUT_METHOD_UNDERLINE,
                            .ce = ce,
                            .fields = fields,
                            .read = read,
                            .write = write});
}
}  // namespace phpgtk
