// GENERATED by gen/gir.php from WebKit.OptionMenuItem - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\WebKitOptionMenuItem (boxed value type)
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\WebKitOptionMenuItem::__construct()
 *
 * WebKitOptionMenuItem values come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitOptionMenuItem::get_label(): string
 *
 * Get the label of a #WebKitOptionMenuItem.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, get_label) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  const char *phpgtk_ret = webkit_option_menu_item_get_label(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitOptionMenuItem::get_tooltip(): string
 *
 * Get the tooltip of a #WebKitOptionMenuItem.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, get_tooltip) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  const char *phpgtk_ret = webkit_option_menu_item_get_tooltip(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitOptionMenuItem::is_enabled(): bool
 *
 * Whether a #WebKitOptionMenuItem is enabled.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, is_enabled) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  RETURN_BOOL(webkit_option_menu_item_is_enabled(self));
}

/**
 * Gtk4\WebKitOptionMenuItem::is_group_child(): bool
 *
 * Whether a #WebKitOptionMenuItem is a group child.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, is_group_child) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  RETURN_BOOL(webkit_option_menu_item_is_group_child(self));
}

/**
 * Gtk4\WebKitOptionMenuItem::is_group_label(): bool
 *
 * Whether a #WebKitOptionMenuItem is a group label.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, is_group_label) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  RETURN_BOOL(webkit_option_menu_item_is_group_label(self));
}

/**
 * Gtk4\WebKitOptionMenuItem::is_selected(): bool
 *
 * Whether a #WebKitOptionMenuItem is the currently selected one.
 */
ZEND_METHOD(Gtk4_WebKitOptionMenuItem, is_selected) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitOptionMenuItem *self = PHPGTK_BOXED_SELF(WebKitOptionMenuItem);
  RETURN_BOOL(webkit_option_menu_item_is_selected(self));
}

namespace phpgtk {
// MINIT: bind the PHP class to WEBKIT_TYPE_OPTION_MENU_ITEM with its field table.
void register_WebKitOptionMenuItem(zend_class_entry *ce) {
  register_boxed(BoxedClass{.type = WEBKIT_TYPE_OPTION_MENU_ITEM,
                            .ce = ce,
                            .fields = fields,
                            .read = read,
                            .write = write});
}
}  // namespace phpgtk
