// GENERATED by gen/gir.php from WebKit.FileChooserRequest - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\WebKitFileChooserRequest
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"
#include "core/collections.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitFileChooserRequest::__construct()
 *
 * WebKitFileChooserRequest has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitFileChooserRequest::cancel(): void
 *
 * Ask WebKit to cancel the request.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, cancel) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  webkit_file_chooser_request_cancel(self);
}

/**
 * Gtk4\WebKitFileChooserRequest::get_mime_types(): array
 *
 * Get the list of MIME types the file chooser dialog should handle.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, get_mime_types) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  strv_to_php(webkit_file_chooser_request_get_mime_types(self), return_value);
}

/**
 * Gtk4\WebKitFileChooserRequest::get_mime_types_filter(): GtkFileFilter
 *
 * Get the filter currently associated with the request.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, get_mime_types_filter) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  GtkFileFilter *phpgtk_ret = webkit_file_chooser_request_get_mime_types_filter(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitFileChooserRequest::get_select_multiple(): bool
 *
 * Whether the file chooser should allow selecting multiple files.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, get_select_multiple) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  RETURN_BOOL(webkit_file_chooser_request_get_select_multiple(self));
}

/**
 * Gtk4\WebKitFileChooserRequest::get_selected_files(): array
 *
 * Get the list of selected files associated to the request.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, get_selected_files) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  strv_to_php(webkit_file_chooser_request_get_selected_files(self), return_value);
}

/**
 * Gtk4\WebKitFileChooserRequest::select_files(array $files): void
 *
 * Ask WebKit to select local files for upload and complete the request.
 */
ZEND_METHOD(Gtk4_WebKitFileChooserRequest, select_files) {
  zval *files;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_ARRAY(files)
  ZEND_PARSE_PARAMETERS_END();
  WebKitFileChooserRequest *self =
      PHPGTK_SELF(WebKitFileChooserRequest, WEBKIT_TYPE_FILE_CHOOSER_REQUEST);
  char **files_v = strv_from_php(files);
  if (files_v == nullptr) RETURN_THROWS();
  webkit_file_chooser_request_select_files(self, const_cast<const char **>(files_v));
  g_strfreev(files_v);
}
