// GENERATED by gen/gir.php from WebKit.BackForwardListItem - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\WebKitBackForwardListItem
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitBackForwardListItem::__construct()
 *
 * WebKitBackForwardListItem has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardListItem, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitBackForwardListItem::get_original_uri(): string
 *
 * Obtain the original URI of the item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardListItem, get_original_uri) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardListItem *self =
      PHPGTK_SELF(WebKitBackForwardListItem, WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM);
  const char *phpgtk_ret = webkit_back_forward_list_item_get_original_uri(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitBackForwardListItem::get_title(): string
 *
 * Obtain the title of the item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardListItem, get_title) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardListItem *self =
      PHPGTK_SELF(WebKitBackForwardListItem, WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM);
  const char *phpgtk_ret = webkit_back_forward_list_item_get_title(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}

/**
 * Gtk4\WebKitBackForwardListItem::get_uri(): string
 *
 * Obtain the URI of the item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardListItem, get_uri) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardListItem *self =
      PHPGTK_SELF(WebKitBackForwardListItem, WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM);
  const char *phpgtk_ret = webkit_back_forward_list_item_get_uri(self);
  if (phpgtk_ret == nullptr) RETURN_EMPTY_STRING();
  RETURN_STRING(phpgtk_ret);
}
