// GENERATED by gen/gir.php from WebKit.FormSubmissionRequest - do not edit (gen/overrides,
// gen/skip.txt). Gtk4\WebKitFormSubmissionRequest
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitFormSubmissionRequest::__construct()
 *
 * WebKitFormSubmissionRequest has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitFormSubmissionRequest, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitFormSubmissionRequest::submit(): void
 *
 * Continue the form submission.
 */
ZEND_METHOD(Gtk4_WebKitFormSubmissionRequest, submit) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitFormSubmissionRequest *self =
      PHPGTK_SELF(WebKitFormSubmissionRequest, WEBKIT_TYPE_FORM_SUBMISSION_REQUEST);
  webkit_form_submission_request_submit(self);
}
