// GENERATED by gen/gir.php from WebKit.BackForwardList - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\WebKitBackForwardList
#include "php_gtk4.h"
#include <webkit/webkit.h>
#include "core/object.h"
#include "core/collections.h"

using namespace phpgtk;

/**
 * Gtk4\WebKitBackForwardList::__construct()
 *
 * WebKitBackForwardList has no constructor in GTK: instances come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, __construct) {
  // Private: never called (object_init_ex() in wrap() skips constructors).
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * Gtk4\WebKitBackForwardList::get_back_item(): ?WebKitBackForwardListItem
 *
 * Returns the item that precedes the current item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_back_item) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  WebKitBackForwardListItem *phpgtk_ret = webkit_back_forward_list_get_back_item(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_back_list(): array
 *
 * Obtain the list of items preceding the current one.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_back_list) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  glist_to_php(webkit_back_forward_list_get_back_list(self), WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM,
               Transfer::Container, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_back_list_with_limit(int $limit): array
 *
 * Obtain a list up to some number of items preceding the current one.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_back_list_with_limit) {
  zend_long limit;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(limit)
  ZEND_PARSE_PARAMETERS_END();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  if (!phpgtk::check_range<guint>(limit, 1)) RETURN_THROWS();
  glist_to_php(webkit_back_forward_list_get_back_list_with_limit(self, static_cast<guint>(limit)),
               WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM, Transfer::Container, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_current_item(): ?WebKitBackForwardListItem
 *
 * Returns the current item in $back_forward_list.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_current_item) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  WebKitBackForwardListItem *phpgtk_ret = webkit_back_forward_list_get_current_item(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_forward_item(): ?WebKitBackForwardListItem
 *
 * Returns the item that follows the current item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_forward_item) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  WebKitBackForwardListItem *phpgtk_ret = webkit_back_forward_list_get_forward_item(self);
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_forward_list(): array
 *
 * Obtain the list of items following the current one.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_forward_list) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  glist_to_php(webkit_back_forward_list_get_forward_list(self), WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM,
               Transfer::Container, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_forward_list_with_limit(int $limit): array
 *
 * Obtain a list up to some number of items following the current one.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_forward_list_with_limit) {
  zend_long limit;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(limit)
  ZEND_PARSE_PARAMETERS_END();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  if (!phpgtk::check_range<guint>(limit, 1)) RETURN_THROWS();
  glist_to_php(
      webkit_back_forward_list_get_forward_list_with_limit(self, static_cast<guint>(limit)),
      WEBKIT_TYPE_BACK_FORWARD_LIST_ITEM, Transfer::Container, return_value);
}

/**
 * Gtk4\WebKitBackForwardList::get_length(): int
 *
 * Obtain the amount of items in the list.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_length) {
  ZEND_PARSE_PARAMETERS_NONE();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  RETURN_LONG(static_cast<zend_long>(webkit_back_forward_list_get_length(self)));
}

/**
 * Gtk4\WebKitBackForwardList::get_nth_item(int $index): ?WebKitBackForwardListItem
 *
 * Returns the item at a given index relative to the current item.
 */
ZEND_METHOD(Gtk4_WebKitBackForwardList, get_nth_item) {
  zend_long index;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_LONG(index)
  ZEND_PARSE_PARAMETERS_END();
  WebKitBackForwardList *self = PHPGTK_SELF(WebKitBackForwardList, WEBKIT_TYPE_BACK_FORWARD_LIST);
  if (!phpgtk::check_range<gint>(index, 1)) RETURN_THROWS();
  WebKitBackForwardListItem *phpgtk_ret =
      webkit_back_forward_list_get_nth_item(self, static_cast<gint>(index));
  wrap(phpgtk_ret != nullptr ? G_OBJECT(phpgtk_ret) : nullptr, return_value);
}
