<?php

/**
 * GENERATED by gen/gir.php from Graphene GIR - do not edit; edit gen/overrides, gen/skip.txt
 * or gen/allowlist.txt and regenerate (./ci.sh --only=gen --fix).
 *
 * @generate-class-entries
 * @generate-legacy-arginfo 80400
 */

namespace Gtk4;

/**
 * A point with two coordinates.
 *
 * @property float $x
 * @property float $y
 * @not-serializable
 */
final class GraphenePoint
{
    /** A value from its fields (all optional, zero by default). */
    public function __construct(float $x = 0.0, float $y = 0.0) {}

    /** Allocates a new #graphene_point_t structure. */
    public static function alloc(): GraphenePoint {}

    /** Checks if the two points $a and $b point to the same coordinates. */
    public function equal(GraphenePoint $b): bool {}

    /** Initializes $p to the given $x and $y coordinates. */
    public function init(float $x, float $y): GraphenePoint {}

    /** Initializes $p with the same coordinates of $src. */
    public function init_from_point(GraphenePoint $src): GraphenePoint {}

    /** Linearly interpolates the coordinates of $a and $b using the given $factor. */
    public function interpolate(GraphenePoint $b, float $factor): GraphenePoint {}

    /** Checks whether the two points $a and $b are within the threshold of $epsilon. */
    public function near(GraphenePoint $b, float $epsilon): bool {}

    /** Returns a point fixed at (0, 0). */
    public static function zero(): GraphenePoint {}
}

/**
 * The location and size of a rectangle region.
 * @not-serializable
 */
final class GrapheneRect
{
    /** GrapheneRect values come from GTK, never from `new`. */
    private function __construct() {}

    /** Checks whether a #graphene_rect_t contains the given coordinates. */
    public function contains_point(GraphenePoint $p): bool {}

    /** Checks whether a #graphene_rect_t fully contains the given rectangle. */
    public function contains_rect(GrapheneRect $b): bool {}

    /** Checks whether the two given rectangle are equal. */
    public function equal(GrapheneRect $b): bool {}

    /** Expands a #graphene_rect_t to contain the given #graphene_point_t. */
    public function expand(GraphenePoint $p): GrapheneRect {}

    /** Compute the area of given normalized rectangle. */
    public function get_area(): float {}

    /** Retrieves the coordinates of the bottom-left corner of the given rectangle. */
    public function get_bottom_left(): GraphenePoint {}

    /** Retrieves the coordinates of the bottom-right corner of the given rectangle. */
    public function get_bottom_right(): GraphenePoint {}

    /** Retrieves the coordinates of the center of the given rectangle. */
    public function get_center(): GraphenePoint {}

    /** Retrieves the normalized height of the given rectangle. */
    public function get_height(): float {}

    /** Retrieves the coordinates of the top-left corner of the given rectangle. */
    public function get_top_left(): GraphenePoint {}

    /** Retrieves the coordinates of the top-right corner of the given rectangle. */
    public function get_top_right(): GraphenePoint {}

    /** Retrieves the normalized width of the given rectangle. */
    public function get_width(): float {}

    /** Retrieves the normalized X coordinate of the origin of the given rectangle. */
    public function get_x(): float {}

    /** Retrieves the normalized Y coordinate of the origin of the given rectangle. */
    public function get_y(): float {}

    /** Initializes the given #graphene_rect_t with the given values. */
    public function init(float $x, float $y, float $width, float $height): GrapheneRect {}

    /** Initializes $r using the given $src rectangle. */
    public function init_from_rect(GrapheneRect $src): GrapheneRect {}

    /** Linearly interpolates the origin and size of the two given rectangles. */
    public function interpolate(GrapheneRect $b, float $factor): GrapheneRect {}

    /** Computes the intersection of the two given rectangles. */
    public function intersection(GrapheneRect $b): ?GrapheneRect {}

    /**
     * Rounds the origin of the given rectangle to its nearest integer value and and recompute the
     * size so that the rectangle is large enough to contain all the conrners of the original
     * rectangle.
     */
    public function round_extents(): GrapheneRect {}

    /**
     * Scales the size and origin of a rectangle horizontaly by $s_h, and vertically by $s_v. The
     * result $res is normalized.
     */
    public function scale(float $s_h, float $s_v): GrapheneRect {}

    /** Computes the union of the two given rectangles. */
    public function union(GrapheneRect $b): GrapheneRect {}

    /** Allocates a new #graphene_rect_t. */
    public static function alloc(): GrapheneRect {}

    /** Returns a degenerate rectangle with origin fixed at (0, 0) and a size of 0, 0. */
    public static function zero(): GrapheneRect {}

    /**
     * Shrink the rectangle by $d_x on each vertical edge and $d_y on each horizontal one.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `inset_r()` form, which leaves the
     * receiver alone - and is why `inset_r()` itself is not bound separately.
     */
    public function inset(float $d_x, float $d_y): GrapheneRect {}

    /**
     * The same rectangle with a non-negative width and height.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `normalize_r()` form, which leaves the
     * receiver alone - and is why `normalize_r()` itself is not bound separately.
     */
    public function normalize(): GrapheneRect {}

    /**
     * Move the rectangle by $d_x and $d_y.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `offset_r()` form, which leaves the
     * receiver alone - and is why `offset_r()` itself is not bound separately.
     */
    public function offset(float $d_x, float $d_y): GrapheneRect {}
}

/**
 * A size.
 *
 * @property float $width
 * @property float $height
 * @not-serializable
 */
final class GrapheneSize
{
    /** A value from its fields (all optional, zero by default). */
    public function __construct(float $width = 0.0, float $height = 0.0) {}

    /** Allocates a new #graphene_size_t. */
    public static function alloc(): GrapheneSize {}

    /** Checks whether the two give #graphene_size_t are equal. */
    public function equal(GrapheneSize $b): bool {}

    /** Initializes a #graphene_size_t using the given $width and $height. */
    public function init(float $width, float $height): GrapheneSize {}

    /** Initializes a #graphene_size_t using the width and height of the given $src. */
    public function init_from_size(GrapheneSize $src): GrapheneSize {}

    /**
     * Linearly interpolates the two given #graphene_size_t using the given interpolation $factor.
     */
    public function interpolate(GrapheneSize $b, float $factor): GrapheneSize {}

    /** Scales the components of a #graphene_size_t using the given $factor. */
    public function scale(float $factor): GrapheneSize {}

    /**
     * A constant pointer to a zero #graphene_size_t, useful for equality checks and
     * interpolations.
     */
    public static function zero(): GrapheneSize {}
}
