// GENERATED by gen/gir.php from Graphene.Size - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GrapheneSize (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {"width", "height", nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  auto *value = static_cast<graphene_size_t *>(data);
  if (strcmp(field, "width") == 0) {
    ZVAL_DOUBLE(rv, value->width);
    return true;
  }
  if (strcmp(field, "height") == 0) {
    ZVAL_DOUBLE(rv, value->height);
    return true;
  }
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  auto *value = static_cast<graphene_size_t *>(data);
  if (strcmp(field, "width") == 0) {
    double d = 0;
    if (boxed_field_double(v, "Gtk4\\GrapheneSize", "width", &d))
      value->width = static_cast<float>(d);
    return true;
  }
  if (strcmp(field, "height") == 0) {
    double d = 0;
    if (boxed_field_double(v, "Gtk4\\GrapheneSize", "height", &d))
      value->height = static_cast<float>(d);
    return true;
  }
  return false;
}

}  // namespace

/**
 * Gtk4\GrapheneSize::__construct(float $width = 0.0, float $height = 0.0)
 *
 * A value from its fields (all optional, zero by default).
 */
ZEND_METHOD(Gtk4_GrapheneSize, __construct) {
  double width = 0;
  double height = 0;
  ZEND_PARSE_PARAMETERS_START(0, 2)
  Z_PARAM_OPTIONAL
  Z_PARAM_DOUBLE(width)
  Z_PARAM_DOUBLE(height)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t value{};
  value.width = static_cast<float>(width);
  value.height = static_cast<float>(height);
  boxed_adopt(boxed_from_zval(ZEND_THIS), GRAPHENE_TYPE_SIZE,
              g_boxed_copy(GRAPHENE_TYPE_SIZE, &value));
}

/**
 * static Gtk4\GrapheneSize::alloc(): GrapheneSize
 *
 * Allocates a new #graphene_size_t.
 */
ZEND_METHOD(Gtk4_GrapheneSize, alloc) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer phpgtk_ret = graphene_size_alloc();
  wrap_boxed(GRAPHENE_TYPE_SIZE, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GRAPHENE_TYPE_SIZE, phpgtk_ret);
}

/**
 * Gtk4\GrapheneSize::equal(GrapheneSize $b): bool
 *
 * Checks whether the two give #graphene_size_t are equal.
 */
ZEND_METHOD(Gtk4_GrapheneSize, equal) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_SIZE)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t *self = PHPGTK_BOXED_SELF(graphene_size_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_SIZE);
  if (b_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(graphene_size_equal(self, static_cast<graphene_size_t *>(b_b)));
}

/**
 * Gtk4\GrapheneSize::init(float $width, float $height): GrapheneSize
 *
 * Initializes a #graphene_size_t using the given $width and $height.
 */
ZEND_METHOD(Gtk4_GrapheneSize, init) {
  double width;
  double height;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_DOUBLE(width)
  Z_PARAM_DOUBLE(height)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t *self = PHPGTK_BOXED_SELF(graphene_size_t);
  graphene_size_t *phpgtk_ret =
      graphene_size_init(self, static_cast<float>(width), static_cast<float>(height));
  wrap_boxed(GRAPHENE_TYPE_SIZE, phpgtk_ret, return_value);
}

/**
 * Gtk4\GrapheneSize::init_from_size(GrapheneSize $src): GrapheneSize
 *
 * Initializes a #graphene_size_t using the width and height of the given $src.
 */
ZEND_METHOD(Gtk4_GrapheneSize, init_from_size) {
  zval *src;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(src, boxed_class_for_type(GRAPHENE_TYPE_SIZE)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t *self = PHPGTK_BOXED_SELF(graphene_size_t);
  gpointer src_b = unwrap_boxed(src, GRAPHENE_TYPE_SIZE);
  if (src_b == nullptr) RETURN_THROWS();
  graphene_size_t *phpgtk_ret =
      graphene_size_init_from_size(self, static_cast<graphene_size_t *>(src_b));
  wrap_boxed(GRAPHENE_TYPE_SIZE, phpgtk_ret, return_value);
}

/**
 * Gtk4\GrapheneSize::interpolate(GrapheneSize $b, float $factor): GrapheneSize
 *
 * Linearly interpolates the two given #graphene_size_t using the given interpolation $factor.
 */
ZEND_METHOD(Gtk4_GrapheneSize, interpolate) {
  zval *b;
  double factor;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_SIZE)->ce)
  Z_PARAM_DOUBLE(factor)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t *self = PHPGTK_BOXED_SELF(graphene_size_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_SIZE);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_size_t res{};
  graphene_size_interpolate(self, static_cast<graphene_size_t *>(b_b), factor, &res);
  wrap_boxed(GRAPHENE_TYPE_SIZE, &res, return_value);
}

/**
 * Gtk4\GrapheneSize::scale(float $factor): GrapheneSize
 *
 * Scales the components of a #graphene_size_t using the given $factor.
 */
ZEND_METHOD(Gtk4_GrapheneSize, scale) {
  double factor;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(factor)
  ZEND_PARSE_PARAMETERS_END();
  graphene_size_t *self = PHPGTK_BOXED_SELF(graphene_size_t);
  graphene_size_t res{};
  graphene_size_scale(self, static_cast<float>(factor), &res);
  wrap_boxed(GRAPHENE_TYPE_SIZE, &res, return_value);
}

/**
 * static Gtk4\GrapheneSize::zero(): GrapheneSize
 *
 * A constant pointer to a zero #graphene_size_t, useful for equality checks and interpolations.
 */
ZEND_METHOD(Gtk4_GrapheneSize, zero) {
  ZEND_PARSE_PARAMETERS_NONE();
  const graphene_size_t *phpgtk_ret = graphene_size_zero();
  wrap_boxed(GRAPHENE_TYPE_SIZE, phpgtk_ret, return_value);
}

namespace phpgtk {
// MINIT: bind the PHP class to GRAPHENE_TYPE_SIZE with its field table.
void register_GrapheneSize(zend_class_entry *ce) {
  register_boxed(BoxedClass{.type = GRAPHENE_TYPE_SIZE,
                            .ce = ce,
                            .fields = fields,
                            .read = read,
                            .write = write,
                            .equal = [](gconstpointer a, gconstpointer b) {
                              return graphene_size_equal(static_cast<const graphene_size_t *>(a),
                                                         static_cast<const graphene_size_t *>(b)) !=
                                     FALSE;
                            }});
}
}  // namespace phpgtk
