<?php

/**
 * GENERATED by gen/gir.php from Graphene GIR - do not edit; edit gen/overrides, gen/skip.txt
 * or gen/allowlist.txt and regenerate (./ci.sh --only=gen --fix).
 *
 * @generate-class-entries
 * @generate-legacy-arginfo 80400
 */

namespace Gtk4;

/**
 * A structure capable of holding a 4x4 matrix.
 * @not-serializable
 */
final class GrapheneMatrix
{
    /** GrapheneMatrix values come from GTK, never from `new`. */
    private function __construct() {}

    /** Allocates a new #graphene_matrix_t. */
    public static function alloc(): GrapheneMatrix {}

    /** Computes the determinant of the given matrix. */
    public function determinant(): float {}

    /** Checks whether the two given #graphene_matrix_t matrices are equal. */
    public function equal(GrapheneMatrix $b): bool {}

    /** Checks whether the two given #graphene_matrix_t matrices are byte-by-byte equal. */
    public function equal_fast(GrapheneMatrix $b): bool {}

    /** Retrieves the given row vector at $index_ inside a matrix. */
    public function get_row(int $index): GrapheneVec4 {}

    /** Retrieves the value at the given $row and $col index. */
    public function get_value(int $row, int $col): float {}

    /** Retrieves the scaling factor on the X axis in $m. */
    public function get_x_scale(): float {}

    /** Retrieves the translation component on the X axis from $m. */
    public function get_x_translation(): float {}

    /** Retrieves the scaling factor on the Y axis in $m. */
    public function get_y_scale(): float {}

    /** Retrieves the translation component on the Y axis from $m. */
    public function get_y_translation(): float {}

    /** Retrieves the scaling factor on the Z axis in $m. */
    public function get_z_scale(): float {}

    /** Retrieves the translation component on the Z axis from $m. */
    public function get_z_translation(): float {}

    /** Initializes a #graphene_matrix_t from the values of an affine transformation matrix. */
    public function init_from_2d(float $xx, float $yx, float $xy, float $yy, float $x_0, float $y_0): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t using the values of the given matrix. */
    public function init_from_matrix(GrapheneMatrix $src): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with the given four row vectors. */
    public function init_from_vec4(GrapheneVec4 $v0, GrapheneVec4 $v1, GrapheneVec4 $v2, GrapheneVec4 $v3): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t compatible with #graphene_frustum_t. */
    public function init_frustum(float $left, float $right, float $bottom, float $top, float $z_near, float $z_far): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with the identity matrix. */
    public function init_identity(): GrapheneMatrix {}

    /**
     * Initializes a #graphene_matrix_t so that it positions the "camera" at the given $eye
     * coordinates towards an object at the $center coordinates. The top of the camera is aligned
     * to the direction of the $up vector.
     */
    public function init_look_at(GrapheneVec3 $eye, GrapheneVec3 $center, GrapheneVec3 $up): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with an orthographic projection. */
    public function init_ortho(float $left, float $right, float $top, float $bottom, float $z_near, float $z_far): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with a perspective projection. */
    public function init_perspective(float $fovy, float $aspect, float $z_near, float $z_far): GrapheneMatrix {}

    /**
     * Initializes $m to represent a rotation of $angle degrees on the axis represented by the
     * $axis vector.
     */
    public function init_rotate(float $angle, GrapheneVec3 $axis): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with the given scaling factors. */
    public function init_scale(float $x, float $y, float $z): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with a skew transformation with the given factors. */
    public function init_skew(float $x_skew, float $y_skew): GrapheneMatrix {}

    /** Initializes a #graphene_matrix_t with a translation to the given coordinates. */
    public function init_translate(GraphenePoint3D $p): GrapheneMatrix {}

    /**
     * Linearly interpolates the two given #graphene_matrix_t by interpolating the decomposed
     * transformations separately.
     */
    public function interpolate(GrapheneMatrix $b, float $factor): GrapheneMatrix {}

    /** Inverts the given matrix. */
    public function inverse(): ?GrapheneMatrix {}

    /**
     * Checks whether the given #graphene_matrix_t is compatible with an a 2D affine transformation
     * matrix.
     */
    public function is_2d(): bool {}

    /** Checks whether a #graphene_matrix_t has a visible back face. */
    public function is_backface_visible(): bool {}

    /** Checks whether the given #graphene_matrix_t is the identity matrix. */
    public function is_identity(): bool {}

    /** Checks whether a matrix is singular. */
    public function is_singular(): bool {}

    /** Multiplies two #graphene_matrix_t. */
    public function multiply(GrapheneMatrix $b): GrapheneMatrix {}

    /**
     * Compares the two given #graphene_matrix_t matrices and checks whether their values are
     * within the given $epsilon of each other.
     */
    public function near(GrapheneMatrix $b, float $epsilon): bool {}

    /** Normalizes the given #graphene_matrix_t. */
    public function normalize(): GrapheneMatrix {}

    /** Applies a perspective of $depth to the matrix. */
    public function perspective(float $depth): GrapheneMatrix {}

    /** Prints the contents of a matrix to the standard error stream. */
    public function print(): void {}

    /** Projects a #graphene_point_t using the matrix $m. */
    public function project_point(GraphenePoint $p): GraphenePoint {}

    /** Projects a #graphene_rect_t using the given matrix. */
    public function project_rect_bounds(GrapheneRect $r): GrapheneRect {}

    /** Adds a rotation transformation to $m, using the given $angle and $axis vector. */
    public function rotate(float $angle, GrapheneVec3 $axis): void {}

    /** Adds a rotation transformation around the X axis to $m, using the given $angle. */
    public function rotate_x(float $angle): void {}

    /** Adds a rotation transformation around the Y axis to $m, using the given $angle. */
    public function rotate_y(float $angle): void {}

    /** Adds a rotation transformation around the Z axis to $m, using the given $angle. */
    public function rotate_z(float $angle): void {}

    /** Adds a scaling transformation to $m, using the three given factors. */
    public function scale(float $factor_x, float $factor_y, float $factor_z): void {}

    /** Adds a skew of $factor on the X and Y axis to the given matrix. */
    public function skew_xy(float $factor): void {}

    /** Adds a skew of $factor on the X and Z axis to the given matrix. */
    public function skew_xz(float $factor): void {}

    /** Adds a skew of $factor on the Y and Z axis to the given matrix. */
    public function skew_yz(float $factor): void {}

    /**
     * Converts a #graphene_matrix_t to an affine transformation matrix, if the given matrix is
     * compatible.
     *
     * @return array{float, float, float, float, float, float}|null
     */
    public function to_2d(): ?array {}

    /** Transforms each corner of a #graphene_rect_t using the given matrix $m. */
    public function transform_bounds(GrapheneRect $r): GrapheneRect {}

    /** Transforms the given #graphene_point_t using the matrix $m. */
    public function transform_point(GraphenePoint $p): GraphenePoint {}

    /** Transforms the given #graphene_point3d_t using the matrix $m. */
    public function transform_point3d(GraphenePoint3D $p): GraphenePoint3D {}

    /** Transforms the given #graphene_vec3_t using the matrix $m. */
    public function transform_vec3(GrapheneVec3 $v): GrapheneVec3 {}

    /** Transforms the given #graphene_vec4_t using the matrix $m. */
    public function transform_vec4(GrapheneVec4 $v): GrapheneVec4 {}

    /**
     * Adds a translation transformation to $m using the coordinates of the given
     * #graphene_point3d_t.
     */
    public function translate(GraphenePoint3D $pos): void {}

    /** Transposes the given matrix. */
    public function transpose(): GrapheneMatrix {}

    /** Unprojects the given $point using the $projection matrix and a $modelview matrix. */
    public function unproject_point3d(GrapheneMatrix $modelview, GraphenePoint3D $point): GraphenePoint3D {}

    /**
     * Undoes the transformation on the corners of a #graphene_rect_t using the given matrix,
     * within the given axis aligned rectangular $bounds.
     */
    public function untransform_bounds(GrapheneRect $r, GrapheneRect $bounds): GrapheneRect {}

    /**
     * Undoes the transformation of a #graphene_point_t using the given matrix, within the given
     * axis aligned rectangular $bounds.
     */
    public function untransform_point(GraphenePoint $p, GrapheneRect $bounds): ?GraphenePoint {}
}

/**
 * A point with two coordinates.
 *
 * @property float $x
 * @property float $y
 * @not-serializable
 */
final class GraphenePoint
{
    /** A value from its fields (all optional, zero by default). */
    public function __construct(float $x = 0.0, float $y = 0.0) {}

    /** Allocates a new #graphene_point_t structure. */
    public static function alloc(): GraphenePoint {}

    /** Checks if the two points $a and $b point to the same coordinates. */
    public function equal(GraphenePoint $b): bool {}

    /** Initializes $p to the given $x and $y coordinates. */
    public function init(float $x, float $y): GraphenePoint {}

    /** Initializes $p with the same coordinates of $src. */
    public function init_from_point(GraphenePoint $src): GraphenePoint {}

    /** Initializes $p with the coordinates inside the given #graphene_vec2_t. */
    public function init_from_vec2(GrapheneVec2 $src): GraphenePoint {}

    /** Linearly interpolates the coordinates of $a and $b using the given $factor. */
    public function interpolate(GraphenePoint $b, float $factor): GraphenePoint {}

    /** Checks whether the two points $a and $b are within the threshold of $epsilon. */
    public function near(GraphenePoint $b, float $epsilon): bool {}

    /** Stores the coordinates of the given #graphene_point_t into a #graphene_vec2_t. */
    public function to_vec2(): GrapheneVec2 {}

    /** Returns a point fixed at (0, 0). */
    public static function zero(): GraphenePoint {}
}

/**
 * A point with three components: X, Y, and Z.
 *
 * @property float $x
 * @property float $y
 * @property float $z
 * @not-serializable
 */
final class GraphenePoint3D
{
    /** A value from its fields (all optional, zero by default). */
    public function __construct(float $x = 0.0, float $y = 0.0, float $z = 0.0) {}

    /** Allocates a #graphene_point3d_t structure. */
    public static function alloc(): GraphenePoint3D {}

    /** Computes the cross product of the two given #graphene_point3d_t. */
    public function cross(GraphenePoint3D $b): GraphenePoint3D {}

    /** Computes the dot product of the two given #graphene_point3d_t. */
    public function dot(GraphenePoint3D $b): float {}

    /** Checks whether two given points are equal. */
    public function equal(GraphenePoint3D $b): bool {}

    /** Initializes a #graphene_point3d_t with the given coordinates. */
    public function init(float $x, float $y, float $z): GraphenePoint3D {}

    /** Initializes a #graphene_point3d_t using the coordinates of another #graphene_point3d_t. */
    public function init_from_point(GraphenePoint3D $src): GraphenePoint3D {}

    /** Initializes a #graphene_point3d_t using the components of a #graphene_vec3_t. */
    public function init_from_vec3(GrapheneVec3 $v): GraphenePoint3D {}

    /**
     * Linearly interpolates each component of $a and $b using the provided $factor, and places the
     * result in $res.
     */
    public function interpolate(GraphenePoint3D $b, float $factor): GraphenePoint3D {}

    /**
     * Computes the length of the vector represented by the coordinates of the given
     * #graphene_point3d_t.
     */
    public function length(): float {}

    /** Checks whether the two points are near each other, within an $epsilon factor. */
    public function near(GraphenePoint3D $b, float $epsilon): bool {}

    /**
     * Computes the normalization of the vector represented by the coordinates of the given
     * #graphene_point3d_t.
     */
    public function normalize(): GraphenePoint3D {}

    /**
     * Normalizes the coordinates of a #graphene_point3d_t using the given viewport and clipping
     * planes.
     */
    public function normalize_viewport(GrapheneRect $viewport, float $z_near, float $z_far): GraphenePoint3D {}

    /** Scales the coordinates of the given #graphene_point3d_t by the given $factor. */
    public function scale(float $factor): GraphenePoint3D {}

    /** Stores the coordinates of a #graphene_point3d_t into a #graphene_vec3_t. */
    public function to_vec3(): GrapheneVec3 {}

    /** Retrieves a constant point with all three coordinates set to 0. */
    public static function zero(): GraphenePoint3D {}
}

/**
 * The location and size of a rectangle region.
 * @not-serializable
 */
final class GrapheneRect
{
    /** GrapheneRect values come from GTK, never from `new`. */
    private function __construct() {}

    /** Checks whether a #graphene_rect_t contains the given coordinates. */
    public function contains_point(GraphenePoint $p): bool {}

    /** Checks whether a #graphene_rect_t fully contains the given rectangle. */
    public function contains_rect(GrapheneRect $b): bool {}

    /** Checks whether the two given rectangle are equal. */
    public function equal(GrapheneRect $b): bool {}

    /** Expands a #graphene_rect_t to contain the given #graphene_point_t. */
    public function expand(GraphenePoint $p): GrapheneRect {}

    /** Compute the area of given normalized rectangle. */
    public function get_area(): float {}

    /** Retrieves the coordinates of the bottom-left corner of the given rectangle. */
    public function get_bottom_left(): GraphenePoint {}

    /** Retrieves the coordinates of the bottom-right corner of the given rectangle. */
    public function get_bottom_right(): GraphenePoint {}

    /** Retrieves the coordinates of the center of the given rectangle. */
    public function get_center(): GraphenePoint {}

    /** Retrieves the normalized height of the given rectangle. */
    public function get_height(): float {}

    /** Retrieves the coordinates of the top-left corner of the given rectangle. */
    public function get_top_left(): GraphenePoint {}

    /** Retrieves the coordinates of the top-right corner of the given rectangle. */
    public function get_top_right(): GraphenePoint {}

    /** Retrieves the normalized width of the given rectangle. */
    public function get_width(): float {}

    /** Retrieves the normalized X coordinate of the origin of the given rectangle. */
    public function get_x(): float {}

    /** Retrieves the normalized Y coordinate of the origin of the given rectangle. */
    public function get_y(): float {}

    /** Initializes the given #graphene_rect_t with the given values. */
    public function init(float $x, float $y, float $width, float $height): GrapheneRect {}

    /** Initializes $r using the given $src rectangle. */
    public function init_from_rect(GrapheneRect $src): GrapheneRect {}

    /** Linearly interpolates the origin and size of the two given rectangles. */
    public function interpolate(GrapheneRect $b, float $factor): GrapheneRect {}

    /** Computes the intersection of the two given rectangles. */
    public function intersection(GrapheneRect $b): ?GrapheneRect {}

    /**
     * Rounds the origin of the given rectangle to its nearest integer value and and recompute the
     * size so that the rectangle is large enough to contain all the conrners of the original
     * rectangle.
     */
    public function round_extents(): GrapheneRect {}

    /**
     * Scales the size and origin of a rectangle horizontaly by $s_h, and vertically by $s_v. The
     * result $res is normalized.
     */
    public function scale(float $s_h, float $s_v): GrapheneRect {}

    /** Computes the union of the two given rectangles. */
    public function union(GrapheneRect $b): GrapheneRect {}

    /** Allocates a new #graphene_rect_t. */
    public static function alloc(): GrapheneRect {}

    /** Returns a degenerate rectangle with origin fixed at (0, 0) and a size of 0, 0. */
    public static function zero(): GrapheneRect {}

    /**
     * Shrink the rectangle by $d_x on each vertical edge and $d_y on each horizontal one.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `inset_r()` form, which leaves the
     * receiver alone - and is why `inset_r()` itself is not bound separately.
     */
    public function inset(float $d_x, float $d_y): GrapheneRect {}

    /**
     * The same rectangle with a non-negative width and height.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `normalize_r()` form, which leaves the
     * receiver alone - and is why `normalize_r()` itself is not bound separately.
     */
    public function normalize(): GrapheneRect {}

    /**
     * Move the rectangle by $d_x and $d_y.
     *
     * graphene's plain form writes into the rectangle it is given and hands the same one back;
     * a boxed handle here is a *value* (clone and compare by value), so a method that silently
     * rewrote the receiver would break that. This is the `offset_r()` form, which leaves the
     * receiver alone - and is why `offset_r()` itself is not bound separately.
     */
    public function offset(float $d_x, float $d_y): GrapheneRect {}
}

/**
 * A size.
 *
 * @property float $width
 * @property float $height
 * @not-serializable
 */
final class GrapheneSize
{
    /** A value from its fields (all optional, zero by default). */
    public function __construct(float $width = 0.0, float $height = 0.0) {}

    /** Allocates a new #graphene_size_t. */
    public static function alloc(): GrapheneSize {}

    /** Checks whether the two give #graphene_size_t are equal. */
    public function equal(GrapheneSize $b): bool {}

    /** Initializes a #graphene_size_t using the given $width and $height. */
    public function init(float $width, float $height): GrapheneSize {}

    /** Initializes a #graphene_size_t using the width and height of the given $src. */
    public function init_from_size(GrapheneSize $src): GrapheneSize {}

    /**
     * Linearly interpolates the two given #graphene_size_t using the given interpolation $factor.
     */
    public function interpolate(GrapheneSize $b, float $factor): GrapheneSize {}

    /** Scales the components of a #graphene_size_t using the given $factor. */
    public function scale(float $factor): GrapheneSize {}

    /**
     * A constant pointer to a zero #graphene_size_t, useful for equality checks and
     * interpolations.
     */
    public static function zero(): GrapheneSize {}
}

/**
 * A structure capable of holding a vector with two dimensions, x and y.
 * @not-serializable
 */
final class GrapheneVec2
{
    /** GrapheneVec2 values come from GTK, never from `new`. */
    private function __construct() {}

    /** Allocates a new #graphene_vec2_t structure. */
    public static function alloc(): GrapheneVec2 {}

    /**
     * Adds each component of the two passed vectors and places each result into the components of
     * $res.
     */
    public function add(GrapheneVec2 $b): GrapheneVec2 {}

    /**
     * Divides each component of the first operand $a by the corresponding component of the second
     * operand $b, and places the results into the vector $res.
     */
    public function divide(GrapheneVec2 $b): GrapheneVec2 {}

    /** Computes the dot product of the two given vectors. */
    public function dot(GrapheneVec2 $b): float {}

    /** Checks whether the two given #graphene_vec2_t are equal. */
    public function equal(GrapheneVec2 $v2): bool {}

    /** Retrieves the X component of the #graphene_vec2_t. */
    public function get_x(): float {}

    /** Retrieves the Y component of the #graphene_vec2_t. */
    public function get_y(): float {}

    /** Initializes a #graphene_vec2_t using the given values. */
    public function init(float $x, float $y): GrapheneVec2 {}

    /** Copies the contents of $src into $v. */
    public function init_from_vec2(GrapheneVec2 $src): GrapheneVec2 {}

    /** Linearly interpolates $v1 and $v2 using the given $factor. */
    public function interpolate(GrapheneVec2 $v2, float $factor): GrapheneVec2 {}

    /** Computes the length of the given vector. */
    public function length(): float {}

    /** Compares the two given vectors and places the maximum values of each component into $res. */
    public function max(GrapheneVec2 $b): GrapheneVec2 {}

    /** Compares the two given vectors and places the minimum values of each component into $res. */
    public function min(GrapheneVec2 $b): GrapheneVec2 {}

    /**
     * Multiplies each component of the two passed vectors and places each result into the
     * components of $res.
     */
    public function multiply(GrapheneVec2 $b): GrapheneVec2 {}

    /**
     * Compares the two given #graphene_vec2_t vectors and checks whether their values are within
     * the given $epsilon.
     */
    public function near(GrapheneVec2 $v2, float $epsilon): bool {}

    /** Negates the given #graphene_vec2_t. */
    public function negate(): GrapheneVec2 {}

    /** Computes the normalized vector for the given vector $v. */
    public function normalize(): GrapheneVec2 {}

    /** Multiplies all components of the given vector with the given scalar $factor. */
    public function scale(float $factor): GrapheneVec2 {}

    /**
     * Subtracts from each component of the first operand $a the corresponding component of the
     * second operand $b and places each result into the components of $res.
     */
    public function subtract(GrapheneVec2 $b): GrapheneVec2 {}

    /** Retrieves a constant vector with (1, 1) components. */
    public static function one(): GrapheneVec2 {}

    /** Retrieves a constant vector with (1, 0) components. */
    public static function x_axis(): GrapheneVec2 {}

    /** Retrieves a constant vector with (0, 1) components. */
    public static function y_axis(): GrapheneVec2 {}

    /** Retrieves a constant vector with (0, 0) components. */
    public static function zero(): GrapheneVec2 {}
}

/**
 * A structure capable of holding a vector with three dimensions: x, y, and z.
 * @not-serializable
 */
final class GrapheneVec3
{
    /** GrapheneVec3 values come from GTK, never from `new`. */
    private function __construct() {}

    /** Allocates a new #graphene_vec3_t structure. */
    public static function alloc(): GrapheneVec3 {}

    /** Adds each component of the two given vectors. */
    public function add(GrapheneVec3 $b): GrapheneVec3 {}

    /** Computes the cross product of the two given vectors. */
    public function cross(GrapheneVec3 $b): GrapheneVec3 {}

    /**
     * Divides each component of the first operand $a by the corresponding component of the second
     * operand $b, and places the results into the vector $res.
     */
    public function divide(GrapheneVec3 $b): GrapheneVec3 {}

    /** Computes the dot product of the two given vectors. */
    public function dot(GrapheneVec3 $b): float {}

    /** Checks whether the two given #graphene_vec3_t are equal. */
    public function equal(GrapheneVec3 $v2): bool {}

    /** Retrieves the first component of the given vector $v. */
    public function get_x(): float {}

    /**
     * Creates a #graphene_vec2_t that contains the first and second components of the given
     * #graphene_vec3_t.
     */
    public function get_xy(): GrapheneVec2 {}

    /**
     * Creates a #graphene_vec3_t that contains the first two components of the given
     * #graphene_vec3_t, and the third component set to 0.
     */
    public function get_xy0(): GrapheneVec3 {}

    /**
     * Converts a #graphene_vec3_t in a #graphene_vec4_t using 0.0 as the value for the fourth
     * component of the resulting vector.
     */
    public function get_xyz0(): GrapheneVec4 {}

    /**
     * Converts a #graphene_vec3_t in a #graphene_vec4_t using 1.0 as the value for the fourth
     * component of the resulting vector.
     */
    public function get_xyz1(): GrapheneVec4 {}

    /**
     * Converts a #graphene_vec3_t in a #graphene_vec4_t using $w as the value of the fourth
     * component of the resulting vector.
     */
    public function get_xyzw(float $w): GrapheneVec4 {}

    /** Retrieves the second component of the given vector $v. */
    public function get_y(): float {}

    /** Retrieves the third component of the given vector $v. */
    public function get_z(): float {}

    /** Initializes a #graphene_vec3_t using the given values. */
    public function init(float $x, float $y, float $z): GrapheneVec3 {}

    /** Initializes a #graphene_vec3_t with the values of another #graphene_vec3_t. */
    public function init_from_vec3(GrapheneVec3 $src): GrapheneVec3 {}

    /** Linearly interpolates $v1 and $v2 using the given $factor. */
    public function interpolate(GrapheneVec3 $v2, float $factor): GrapheneVec3 {}

    /** Retrieves the length of the given vector $v. */
    public function length(): float {}

    /**
     * Compares each component of the two given vectors and creates a vector that contains the
     * maximum values.
     */
    public function max(GrapheneVec3 $b): GrapheneVec3 {}

    /**
     * Compares each component of the two given vectors and creates a vector that contains the
     * minimum values.
     */
    public function min(GrapheneVec3 $b): GrapheneVec3 {}

    /** Multiplies each component of the two given vectors. */
    public function multiply(GrapheneVec3 $b): GrapheneVec3 {}

    /**
     * Compares the two given #graphene_vec3_t vectors and checks whether their values are within
     * the given $epsilon.
     */
    public function near(GrapheneVec3 $v2, float $epsilon): bool {}

    /** Negates the given #graphene_vec3_t. */
    public function negate(): GrapheneVec3 {}

    /** Normalizes the given #graphene_vec3_t. */
    public function normalize(): GrapheneVec3 {}

    /** Multiplies all components of the given vector with the given scalar $factor. */
    public function scale(float $factor): GrapheneVec3 {}

    /**
     * Subtracts from each component of the first operand $a the corresponding component of the
     * second operand $b and places each result into the components of $res.
     */
    public function subtract(GrapheneVec3 $b): GrapheneVec3 {}

    /** Provides a constant pointer to a vector with three components, all sets to 1. */
    public static function one(): GrapheneVec3 {}

    /**
     * Provides a constant pointer to a vector with three components with values set to (1, 0, 0).
     */
    public static function x_axis(): GrapheneVec3 {}

    /**
     * Provides a constant pointer to a vector with three components with values set to (0, 1, 0).
     */
    public static function y_axis(): GrapheneVec3 {}

    /**
     * Provides a constant pointer to a vector with three components with values set to (0, 0, 1).
     */
    public static function z_axis(): GrapheneVec3 {}

    /** Provides a constant pointer to a vector with three components, all sets to 0. */
    public static function zero(): GrapheneVec3 {}
}

/**
 * A structure capable of holding a vector with four dimensions: x, y, z, and w.
 * @not-serializable
 */
final class GrapheneVec4
{
    /** GrapheneVec4 values come from GTK, never from `new`. */
    private function __construct() {}

    /** Allocates a new #graphene_vec4_t structure. */
    public static function alloc(): GrapheneVec4 {}

    /** Adds each component of the two given vectors. */
    public function add(GrapheneVec4 $b): GrapheneVec4 {}

    /**
     * Divides each component of the first operand $a by the corresponding component of the second
     * operand $b, and places the results into the vector $res.
     */
    public function divide(GrapheneVec4 $b): GrapheneVec4 {}

    /** Computes the dot product of the two given vectors. */
    public function dot(GrapheneVec4 $b): float {}

    /** Checks whether the two given #graphene_vec4_t are equal. */
    public function equal(GrapheneVec4 $v2): bool {}

    /** Retrieves the value of the fourth component of the given #graphene_vec4_t. */
    public function get_w(): float {}

    /** Retrieves the value of the first component of the given #graphene_vec4_t. */
    public function get_x(): float {}

    /**
     * Creates a #graphene_vec2_t that contains the first two components of the given
     * #graphene_vec4_t.
     */
    public function get_xy(): GrapheneVec2 {}

    /**
     * Creates a #graphene_vec3_t that contains the first three components of the given
     * #graphene_vec4_t.
     */
    public function get_xyz(): GrapheneVec3 {}

    /** Retrieves the value of the second component of the given #graphene_vec4_t. */
    public function get_y(): float {}

    /** Retrieves the value of the third component of the given #graphene_vec4_t. */
    public function get_z(): float {}

    /** Initializes a #graphene_vec4_t using the given values. */
    public function init(float $x, float $y, float $z, float $w): GrapheneVec4 {}

    /**
     * Initializes a #graphene_vec4_t using the components of a #graphene_vec2_t and the values of
     * $z and $w.
     */
    public function init_from_vec2(GrapheneVec2 $src, float $z, float $w): GrapheneVec4 {}

    /**
     * Initializes a #graphene_vec4_t using the components of a #graphene_vec3_t and the value of
     * $w.
     */
    public function init_from_vec3(GrapheneVec3 $src, float $w): GrapheneVec4 {}

    /** Initializes a #graphene_vec4_t using the components of another #graphene_vec4_t. */
    public function init_from_vec4(GrapheneVec4 $src): GrapheneVec4 {}

    /** Linearly interpolates $v1 and $v2 using the given $factor. */
    public function interpolate(GrapheneVec4 $v2, float $factor): GrapheneVec4 {}

    /** Computes the length of the given #graphene_vec4_t. */
    public function length(): float {}

    /**
     * Compares each component of the two given vectors and creates a vector that contains the
     * maximum values.
     */
    public function max(GrapheneVec4 $b): GrapheneVec4 {}

    /**
     * Compares each component of the two given vectors and creates a vector that contains the
     * minimum values.
     */
    public function min(GrapheneVec4 $b): GrapheneVec4 {}

    /** Multiplies each component of the two given vectors. */
    public function multiply(GrapheneVec4 $b): GrapheneVec4 {}

    /**
     * Compares the two given #graphene_vec4_t vectors and checks whether their values are within
     * the given $epsilon.
     */
    public function near(GrapheneVec4 $v2, float $epsilon): bool {}

    /** Negates the given #graphene_vec4_t. */
    public function negate(): GrapheneVec4 {}

    /** Normalizes the given #graphene_vec4_t. */
    public function normalize(): GrapheneVec4 {}

    /** Multiplies all components of the given vector with the given scalar $factor. */
    public function scale(float $factor): GrapheneVec4 {}

    /**
     * Subtracts from each component of the first operand $a the corresponding component of the
     * second operand $b and places each result into the components of $res.
     */
    public function subtract(GrapheneVec4 $b): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with all its components set to 1. */
    public static function one(): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with its components set to (0, 0, 0, 1). */
    public static function w_axis(): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with its components set to (1, 0, 0, 0). */
    public static function x_axis(): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with its components set to (0, 1, 0, 0). */
    public static function y_axis(): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with its components set to (0, 0, 1, 0). */
    public static function z_axis(): GrapheneVec4 {}

    /** Retrieves a pointer to a #graphene_vec4_t with all its components set to 0. */
    public static function zero(): GrapheneVec4 {}
}
