// GENERATED by gen/gir.php from Graphene.Vec2 - do not edit (gen/overrides, gen/skip.txt).
// Gtk4\GrapheneVec2 (boxed value type)
#include "php_gtk4.h"
#include "core/boxed.h"
#include "core/object.h"
#include <cstring>

using namespace phpgtk;

namespace {

const char *const fields[] = {nullptr};

// Boxed field reader: the public scalar fields as PHP properties.
bool read(gpointer data, const char *field, zval *rv) {
  (void)data;
  (void)field;
  (void)rv;
  return false;
}

// Boxed field writer: each field converts like a parameter of its type (core/boxed).
bool write(gpointer data, const char *field, zval *v) {
  (void)data;
  (void)field;
  (void)v;
  return false;
}

}  // namespace

/**
 * Gtk4\GrapheneVec2::__construct()
 *
 * GrapheneVec2 values come from GTK, never from `new`.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, __construct) {
  ZEND_PARSE_PARAMETERS_NONE();
}

/**
 * static Gtk4\GrapheneVec2::alloc(): GrapheneVec2
 *
 * Allocates a new #graphene_vec2_t structure.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, alloc) {
  ZEND_PARSE_PARAMETERS_NONE();
  gpointer phpgtk_ret = graphene_vec2_alloc();
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
  if (phpgtk_ret != nullptr) g_boxed_free(GRAPHENE_TYPE_VEC2, phpgtk_ret);
}

/**
 * Gtk4\GrapheneVec2::add(GrapheneVec2 $b): GrapheneVec2
 *
 * Adds each component of the two passed vectors and places each result into the components of
 * $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, add) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_add(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::divide(GrapheneVec2 $b): GrapheneVec2
 *
 * Divides each component of the first operand $a by the corresponding component of the second
 * operand $b, and places the results into the vector $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, divide) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_divide(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::dot(GrapheneVec2 $b): float
 *
 * Computes the dot product of the two given vectors.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, dot) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  RETURN_DOUBLE(graphene_vec2_dot(self, static_cast<graphene_vec2_t *>(b_b)));
}

/**
 * Gtk4\GrapheneVec2::equal(GrapheneVec2 $v2): bool
 *
 * Checks whether the two given #graphene_vec2_t are equal.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, equal) {
  zval *v2;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(v2, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer v2_b = unwrap_boxed(v2, GRAPHENE_TYPE_VEC2);
  if (v2_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(graphene_vec2_equal(self, static_cast<graphene_vec2_t *>(v2_b)));
}

/**
 * Gtk4\GrapheneVec2::get_x(): float
 *
 * Retrieves the X component of the #graphene_vec2_t.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, get_x) {
  ZEND_PARSE_PARAMETERS_NONE();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  RETURN_DOUBLE(graphene_vec2_get_x(self));
}

/**
 * Gtk4\GrapheneVec2::get_y(): float
 *
 * Retrieves the Y component of the #graphene_vec2_t.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, get_y) {
  ZEND_PARSE_PARAMETERS_NONE();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  RETURN_DOUBLE(graphene_vec2_get_y(self));
}

/**
 * Gtk4\GrapheneVec2::init(float $x, float $y): GrapheneVec2
 *
 * Initializes a #graphene_vec2_t using the given values.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, init) {
  double x;
  double y;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_DOUBLE(x)
  Z_PARAM_DOUBLE(y)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  graphene_vec2_t *phpgtk_ret =
      graphene_vec2_init(self, static_cast<float>(x), static_cast<float>(y));
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

/**
 * Gtk4\GrapheneVec2::init_from_vec2(GrapheneVec2 $src): GrapheneVec2
 *
 * Copies the contents of $src into $v.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, init_from_vec2) {
  zval *src;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(src, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer src_b = unwrap_boxed(src, GRAPHENE_TYPE_VEC2);
  if (src_b == nullptr) RETURN_THROWS();
  graphene_vec2_t *phpgtk_ret =
      graphene_vec2_init_from_vec2(self, static_cast<graphene_vec2_t *>(src_b));
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

/**
 * Gtk4\GrapheneVec2::interpolate(GrapheneVec2 $v2, float $factor): GrapheneVec2
 *
 * Linearly interpolates $v1 and $v2 using the given $factor.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, interpolate) {
  zval *v2;
  double factor;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(v2, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  Z_PARAM_DOUBLE(factor)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer v2_b = unwrap_boxed(v2, GRAPHENE_TYPE_VEC2);
  if (v2_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_interpolate(self, static_cast<graphene_vec2_t *>(v2_b), factor, &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::length(): float
 *
 * Computes the length of the given vector.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, length) {
  ZEND_PARSE_PARAMETERS_NONE();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  RETURN_DOUBLE(graphene_vec2_length(self));
}

/**
 * Gtk4\GrapheneVec2::max(GrapheneVec2 $b): GrapheneVec2
 *
 * Compares the two given vectors and places the maximum values of each component into $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, max) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_max(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::min(GrapheneVec2 $b): GrapheneVec2
 *
 * Compares the two given vectors and places the minimum values of each component into $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, min) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_min(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::multiply(GrapheneVec2 $b): GrapheneVec2
 *
 * Multiplies each component of the two passed vectors and places each result into the components
 * of $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, multiply) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_multiply(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::near(GrapheneVec2 $v2, float $epsilon): bool
 *
 * Compares the two given #graphene_vec2_t vectors and checks whether their values are within the
 * given $epsilon.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, near) {
  zval *v2;
  double epsilon;
  ZEND_PARSE_PARAMETERS_START(2, 2)
  Z_PARAM_OBJECT_OF_CLASS(v2, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  Z_PARAM_DOUBLE(epsilon)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer v2_b = unwrap_boxed(v2, GRAPHENE_TYPE_VEC2);
  if (v2_b == nullptr) RETURN_THROWS();
  RETURN_BOOL(
      graphene_vec2_near(self, static_cast<graphene_vec2_t *>(v2_b), static_cast<float>(epsilon)));
}

/**
 * Gtk4\GrapheneVec2::negate(): GrapheneVec2
 *
 * Negates the given #graphene_vec2_t.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, negate) {
  ZEND_PARSE_PARAMETERS_NONE();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  graphene_vec2_t res{};
  graphene_vec2_negate(self, &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::normalize(): GrapheneVec2
 *
 * Computes the normalized vector for the given vector $v.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, normalize) {
  ZEND_PARSE_PARAMETERS_NONE();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  graphene_vec2_t res{};
  graphene_vec2_normalize(self, &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::scale(float $factor): GrapheneVec2
 *
 * Multiplies all components of the given vector with the given scalar $factor.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, scale) {
  double factor;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_DOUBLE(factor)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  graphene_vec2_t res{};
  graphene_vec2_scale(self, static_cast<float>(factor), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * Gtk4\GrapheneVec2::subtract(GrapheneVec2 $b): GrapheneVec2
 *
 * Subtracts from each component of the first operand $a the corresponding component of the second
 * operand $b and places each result into the components of $res.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, subtract) {
  zval *b;
  ZEND_PARSE_PARAMETERS_START(1, 1)
  Z_PARAM_OBJECT_OF_CLASS(b, boxed_class_for_type(GRAPHENE_TYPE_VEC2)->ce)
  ZEND_PARSE_PARAMETERS_END();
  graphene_vec2_t *self = PHPGTK_BOXED_SELF(graphene_vec2_t);
  gpointer b_b = unwrap_boxed(b, GRAPHENE_TYPE_VEC2);
  if (b_b == nullptr) RETURN_THROWS();
  graphene_vec2_t res{};
  graphene_vec2_subtract(self, static_cast<graphene_vec2_t *>(b_b), &res);
  wrap_boxed(GRAPHENE_TYPE_VEC2, &res, return_value);
}

/**
 * static Gtk4\GrapheneVec2::one(): GrapheneVec2
 *
 * Retrieves a constant vector with (1, 1) components.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, one) {
  ZEND_PARSE_PARAMETERS_NONE();
  const graphene_vec2_t *phpgtk_ret = graphene_vec2_one();
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

/**
 * static Gtk4\GrapheneVec2::x_axis(): GrapheneVec2
 *
 * Retrieves a constant vector with (1, 0) components.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, x_axis) {
  ZEND_PARSE_PARAMETERS_NONE();
  const graphene_vec2_t *phpgtk_ret = graphene_vec2_x_axis();
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

/**
 * static Gtk4\GrapheneVec2::y_axis(): GrapheneVec2
 *
 * Retrieves a constant vector with (0, 1) components.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, y_axis) {
  ZEND_PARSE_PARAMETERS_NONE();
  const graphene_vec2_t *phpgtk_ret = graphene_vec2_y_axis();
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

/**
 * static Gtk4\GrapheneVec2::zero(): GrapheneVec2
 *
 * Retrieves a constant vector with (0, 0) components.
 */
ZEND_METHOD(Gtk4_GrapheneVec2, zero) {
  ZEND_PARSE_PARAMETERS_NONE();
  const graphene_vec2_t *phpgtk_ret = graphene_vec2_zero();
  wrap_boxed(GRAPHENE_TYPE_VEC2, phpgtk_ret, return_value);
}

namespace phpgtk {
// MINIT: bind the PHP class to GRAPHENE_TYPE_VEC2 with its field table.
void register_GrapheneVec2(zend_class_entry *ce) {
  register_boxed(BoxedClass{.type = GRAPHENE_TYPE_VEC2,
                            .ce = ce,
                            .fields = fields,
                            .read = read,
                            .write = write,
                            .equal = [](gconstpointer a, gconstpointer b) {
                              return graphene_vec2_equal(static_cast<const graphene_vec2_t *>(a),
                                                         static_cast<const graphene_vec2_t *>(b)) !=
                                     FALSE;
                            }});
}
}  // namespace phpgtk
