// GENERATED by gen/gir.php - prototypes of the interface method implementations.
// gen_stub declares none for an interface's (abstract) methods, but the ZEND_MALIAS
// entries of the implementing classes point at these. Include before the arginfo.
#pragma once
#include "php_gtk4.h"

void register_vfuncs_GtkAdjustment();
void register_vfuncs_GtkApplication();
void register_vfuncs_GtkButton();
void register_vfuncs_GtkCheckButton();
void register_vfuncs_GtkDrawingArea();
void register_vfuncs_GtkEditable();
ZEND_METHOD(Gtk4_GtkEditable, delegate_get_accessible_platform_state);
ZEND_METHOD(Gtk4_GtkEditable, delete_selection);
ZEND_METHOD(Gtk4_GtkEditable, delete_text);
ZEND_METHOD(Gtk4_GtkEditable, finish_delegate);
ZEND_METHOD(Gtk4_GtkEditable, get_alignment);
ZEND_METHOD(Gtk4_GtkEditable, get_chars);
ZEND_METHOD(Gtk4_GtkEditable, get_delegate);
ZEND_METHOD(Gtk4_GtkEditable, get_editable);
ZEND_METHOD(Gtk4_GtkEditable, get_enable_undo);
ZEND_METHOD(Gtk4_GtkEditable, get_max_width_chars);
ZEND_METHOD(Gtk4_GtkEditable, get_position);
ZEND_METHOD(Gtk4_GtkEditable, get_selection_bounds);
ZEND_METHOD(Gtk4_GtkEditable, get_text);
ZEND_METHOD(Gtk4_GtkEditable, get_width_chars);
ZEND_METHOD(Gtk4_GtkEditable, init_delegate);
ZEND_METHOD(Gtk4_GtkEditable, select_region);
ZEND_METHOD(Gtk4_GtkEditable, set_alignment);
ZEND_METHOD(Gtk4_GtkEditable, set_editable);
ZEND_METHOD(Gtk4_GtkEditable, set_enable_undo);
ZEND_METHOD(Gtk4_GtkEditable, set_max_width_chars);
ZEND_METHOD(Gtk4_GtkEditable, set_position);
ZEND_METHOD(Gtk4_GtkEditable, set_text);
ZEND_METHOD(Gtk4_GtkEditable, set_width_chars);
void register_vfuncs_GtkEntry();
void register_vfuncs_GtkEntryBuffer();
void register_vfuncs_GtkFilter();
ZEND_METHOD(Gtk4_GtkOrientable, get_orientation);
ZEND_METHOD(Gtk4_GtkOrientable, set_orientation);
void register_vfuncs_GtkPopover();
void register_vfuncs_GtkRange();
namespace phpgtk {
void register_GtkRequisition(zend_class_entry *ce);
}  // namespace phpgtk
ZEND_METHOD(Gtk4_GtkRoot, get_display);
ZEND_METHOD(Gtk4_GtkRoot, get_focus);
ZEND_METHOD(Gtk4_GtkRoot, set_focus);
void register_vfuncs_GtkScale();
ZEND_METHOD(Gtk4_GtkScrollable, get_hadjustment);
ZEND_METHOD(Gtk4_GtkScrollable, get_hscroll_policy);
ZEND_METHOD(Gtk4_GtkScrollable, get_vadjustment);
ZEND_METHOD(Gtk4_GtkScrollable, get_vscroll_policy);
ZEND_METHOD(Gtk4_GtkScrollable, set_hadjustment);
ZEND_METHOD(Gtk4_GtkScrollable, set_hscroll_policy);
ZEND_METHOD(Gtk4_GtkScrollable, set_vadjustment);
ZEND_METHOD(Gtk4_GtkScrollable, set_vscroll_policy);
void register_vfuncs_GtkSorter();
void register_vfuncs_GtkTextBuffer();
namespace phpgtk {
void register_GtkTextIter(zend_class_entry *ce);
}  // namespace phpgtk
void register_vfuncs_GtkTextView();
void register_vfuncs_GtkWidget();
void register_vfuncs_GtkWindow();
namespace phpgtk {
void register_PangoFontDescription(zend_class_entry *ce);
}  // namespace phpgtk
void register_vfuncs_GAction();
ZEND_METHOD(Gtk4_GAction, activate);
ZEND_METHOD(Gtk4_GAction, change_state);
ZEND_METHOD(Gtk4_GAction, get_enabled);
ZEND_METHOD(Gtk4_GAction, get_name);
ZEND_METHOD(Gtk4_GAction, get_parameter_type);
ZEND_METHOD(Gtk4_GAction, get_state);
ZEND_METHOD(Gtk4_GAction, get_state_hint);
ZEND_METHOD(Gtk4_GAction, get_state_type);
void register_vfuncs_GActionGroup();
ZEND_METHOD(Gtk4_GActionGroup, action_added);
ZEND_METHOD(Gtk4_GActionGroup, action_enabled_changed);
ZEND_METHOD(Gtk4_GActionGroup, action_removed);
ZEND_METHOD(Gtk4_GActionGroup, action_state_changed);
ZEND_METHOD(Gtk4_GActionGroup, activate_action);
ZEND_METHOD(Gtk4_GActionGroup, change_action_state);
ZEND_METHOD(Gtk4_GActionGroup, get_action_enabled);
ZEND_METHOD(Gtk4_GActionGroup, get_action_parameter_type);
ZEND_METHOD(Gtk4_GActionGroup, get_action_state);
ZEND_METHOD(Gtk4_GActionGroup, get_action_state_hint);
ZEND_METHOD(Gtk4_GActionGroup, get_action_state_type);
ZEND_METHOD(Gtk4_GActionGroup, has_action);
ZEND_METHOD(Gtk4_GActionGroup, list_actions);
void register_vfuncs_GActionMap();
ZEND_METHOD(Gtk4_GActionMap, add_action);
ZEND_METHOD(Gtk4_GActionMap, lookup_action);
ZEND_METHOD(Gtk4_GActionMap, remove_action);
void register_vfuncs_GApplication();
void register_vfuncs_GAsyncResult();
ZEND_METHOD(Gtk4_GAsyncResult, get_source_object);
ZEND_METHOD(Gtk4_GAsyncResult, legacy_propagate_error);
void register_vfuncs_GCancellable();
void register_vfuncs_GListModel();
ZEND_METHOD(Gtk4_GListModel, get_item_type);
ZEND_METHOD(Gtk4_GListModel, get_n_items);
ZEND_METHOD(Gtk4_GListModel, get_item);
ZEND_METHOD(Gtk4_GListModel, items_changed);
void register_vfuncs_GMenuModel();
void register_vfuncs_GdkPaintable();
ZEND_METHOD(Gtk4_GdkPaintable, compute_concrete_size);
ZEND_METHOD(Gtk4_GdkPaintable, get_current_image);
ZEND_METHOD(Gtk4_GdkPaintable, get_flags);
ZEND_METHOD(Gtk4_GdkPaintable, get_intrinsic_aspect_ratio);
ZEND_METHOD(Gtk4_GdkPaintable, get_intrinsic_height);
ZEND_METHOD(Gtk4_GdkPaintable, get_intrinsic_width);
ZEND_METHOD(Gtk4_GdkPaintable, invalidate_contents);
ZEND_METHOD(Gtk4_GdkPaintable, invalidate_size);
